// Generated by GitHub Copilot
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { AssignmentsPanel } from "@/components/jobs/AssignmentsPanel";

export default async function AssignmentsPage({
	params,
}: {
	params: Promise<{ id: string }>;
}) {
	const { id } = await params;
	const supabase = await createClient();
	const t = await getTranslations("panels.assignments");

	const [
		{ data: job },
		{ data: assignments },
		{ data: vendors },
		{ data: crew },
	] = await Promise.all([
		supabase
			.from("jobs")
			.select("id, job_number, move_date")
			.eq("id", id)
			.single(),
		supabase
			.from("job_assignments")
			.select(
				"id, assignment_type, role, vendor_id, crew_id, vendors(name), crew(name)",
			)
			.eq("job_id", id),
		supabase
			.from("vendors")
			.select("id, name")
			.eq("is_active", true)
			.order("name"),
		supabase
			.from("crew")
			.select("id, name, daily_rate")
			.eq("is_active", true)
			.order("name"),
	]);

	if (!job) notFound();

	return (
		<div className="space-y-6 max-w-2xl">
			<div className="flex items-center gap-3">
				<Link
					href={`/jobs/${id}`}
					className="text-sm text-brand-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
				>
					← {job.job_number}
				</Link>
				<h1 className="text-2xl font-bold text-gray-900 dark:text-white">
					{t("title")}
				</h1>
			</div>

			<AssignmentsPanel
				jobId={id}
				moveDate={job.move_date}
				assignments={assignments ?? []}
				vendors={vendors ?? []}
				crewList={crew ?? []}
			/>
		</div>
	);
}
