// Generated by GitHub Copilot

/**
 * Helpers to derive typed PDF settings from the flat system_settings key→value map.
 * Use `buildCompanySettings`, `buildProposalTemplateSettings`, and
 * `buildInvoiceTemplateSettings` in server components before passing to PDF props.
 */

/** Company identity — appears on every PDF. */
export interface CompanySettings {
	name: string;
	tagline: string;
}

/** Proposal-specific template content. */
export interface ProposalTemplateSettings {
	/** Multi-line terms & conditions text. */
	terms: string;
	signatureName: string;
	signatureRole: string;
}

/** Invoice-specific template content. */
export interface InvoiceTemplateSettings {
	footerNote: string;
}

const DEFAULTS: Record<string, string> = {
	company_name: "IM Moving",
	company_tagline: "Professional Relocation Services",
	proposal_terms: [
		"1. This proposal is valid for 7 days from the date of issue.",
		"2. A down payment of 50% is required to confirm the booking.",
		"3. Remaining balance is due on the day of the move before unloading.",
		"4. Prices may be revised if the scope of work changes significantly.",
		"5. IM Moving is not liable for pre-existing damage to items.",
		"6. Cancellation less than 48 hours before the move date may incur a penalty.",
	].join("\n"),
	proposal_signature_name: "IM Moving Operations",
	proposal_signature_role: "Authorized Signatory",
	invoice_footer_note: "Thank you for your business",
};

function get(map: Record<string, string>, key: string): string {
	return map[key] ?? DEFAULTS[key] ?? "";
}

/** Build company identity settings from the raw key→value map. */
export function buildCompanySettings(
	map: Record<string, string>,
): CompanySettings {
	return {
		name: get(map, "company_name"),
		tagline: get(map, "company_tagline"),
	};
}

/** Build proposal template settings from the raw key→value map. */
export function buildProposalTemplateSettings(
	map: Record<string, string>,
): ProposalTemplateSettings {
	return {
		terms: get(map, "proposal_terms"),
		signatureName: get(map, "proposal_signature_name"),
		signatureRole: get(map, "proposal_signature_role"),
	};
}

/** Build invoice template settings from the raw key→value map. */
export function buildInvoiceTemplateSettings(
	map: Record<string, string>,
): InvoiceTemplateSettings {
	return {
		footerNote: get(map, "invoice_footer_note"),
	};
}
