// Generated by GitHub Copilot
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { ExpensePanel } from "@/components/jobs/ExpensePanel";

export default async function ExpensesPage({
	params,
}: {
	params: Promise<{ id: string }>;
}) {
	const { id } = await params;
	const supabase = await createClient();
	const t = await getTranslations("pages.jobDetail");

	const [{ data: job }, { data: expenses }] = await Promise.all([
		supabase.from("jobs").select("id, job_number").eq("id", id).single(),
		supabase
			.from("expenses")
			.select("id, category, description, amount, incurred_at, receipt_url")
			.eq("job_id", id)
			.order("incurred_at", { ascending: false }),
	]);

	if (!job) notFound();

	return (
		<div className="space-y-6 max-w-lg">
			<div className="flex items-center gap-3">
				<Link
					href={`/jobs/${id}`}
					className="text-sm text-brand-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
				>
					← {job.job_number}
				</Link>
				<h1 className="text-2xl font-bold text-gray-900 dark:text-white">
					{t("expenses")}
				</h1>
			</div>

			<ExpensePanel jobId={id} expenses={expenses ?? []} />
		</div>
	);
}
