"use client";
// Generated by GitHub Copilot
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";
import { NumericInput } from "@/components/shared/NumericInput";

type CrewRow = {
	id: string;
	name: string;
	phone: string | null;
	skills: string[] | null;
	daily_rate: number | null;
	availability_status: string | null;
	emergency_contact: string | null;
	notes: string | null;
	is_active: boolean;
};

const SKILL_OPTIONS: { value: string; tKey: string }[] = [
	{ value: "Loading", tKey: "loading" },
	{ value: "Unloading", tKey: "unloading" },
	{ value: "Packing", tKey: "packing" },
	{ value: "Assembly", tKey: "assembly" },
	{ value: "Driving", tKey: "driving" },
	{ value: "Supervision", tKey: "supervision" },
];
const AVAIL_OPTS: { value: string; tKey: string }[] = [
	{ value: "available", tKey: "available" },
	{ value: "on_job", tKey: "on_job" },
	{ value: "unavailable", tKey: "unavailable" },
];

/**
 * Create or edit a crew member.
 */
export function CrewForm({ member }: { member?: CrewRow }) {
	const router = useRouter();
	const t = useTranslations("forms.crew");
	const tButtons = useTranslations("common.buttons");
	const tActions = useTranslations("actions");
	const tErrors = useTranslations("common.errors");
	const tHints = useTranslations("common.hints");
	const tSkill = useTranslations("entity.skill");
	const tAvail = useTranslations("entity.availability");
	const isEdit = Boolean(member);

	const [form, setForm] = useState({
		name: member?.name ?? "",
		phone: member?.phone ?? "",
		skills: member?.skills ?? [],
		daily_rate: member?.daily_rate?.toString() ?? "",
		availability_status: member?.availability_status ?? "available",
		emergency_contact: member?.emergency_contact ?? "",
		notes: member?.notes ?? "",
		is_active: member?.is_active ?? true,
	});
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	function toggleSkill(s: string) {
		setForm((p) => ({
			...p,
			skills: p.skills.includes(s)
				? p.skills.filter((x) => x !== s)
				: [...p.skills, s],
		}));
	}

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		if (!form.name.trim()) {
			setError(tErrors("nameRequired"));
			return;
		}
		setSaving(true);
		setError(null);

		const payload = {
			name: form.name.trim(),
			phone: form.phone.trim() || null,
			skills: form.skills.length ? form.skills : null,
			daily_rate: form.daily_rate ? Number(form.daily_rate) : null,
			availability_status: form.availability_status,
			emergency_contact: form.emergency_contact.trim() || null,
			notes: form.notes.trim() || null,
			is_active: form.is_active,
		};

		const supabase = createClient();

		if (isEdit && member) {
			const { error: err } = await supabase
				.from("crew")
				.update(payload)
				.eq("id", member.id);
			if (err) {
				setError(err.message);
				setSaving(false);
				return;
			}
			router.push(`/crew/${member.id}`);
		} else {
			const { data, error: err } = await supabase
				.from("crew")
				.insert(payload)
				.select("id")
				.single();
			if (err || !data) {
				setError(err?.message ?? "Error");
				setSaving(false);
				return;
			}
			router.push(`/crew/${data.id}`);
		}
	}

	return (
		<form onSubmit={handleSubmit} className="max-w-lg space-y-5" noValidate>
			{error && (
				<div
					role="alert"
					className="rounded bg-red-50 dark:bg-red-900/20 border border-red-200 px-3 py-2 text-sm text-red-700 dark:text-red-300"
				>
					{error}
				</div>
			)}

			<div>
				<label
					htmlFor="c-name"
					className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
				>
					{t("name")}{" "}
					<span aria-hidden="true" className="text-red-500">
						*
					</span>
				</label>
				<input
					id="c-name"
					type="text"
					required
					value={form.name}
					onChange={(e) => setForm((p) => ({ ...p, name: e.target.value }))}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<div className="grid grid-cols-2 gap-4">
				<div>
					<label
						htmlFor="c-phone"
						className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
					>
						{t("phone")}
					</label>
					<input
						id="c-phone"
						type="tel"
						value={form.phone}
						onChange={(e) => setForm((p) => ({ ...p, phone: e.target.value }))}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>
				<div>
					<label
						htmlFor="c-rate"
						className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
					>
						{t("dailyRate")}{" "}
						<span className="text-gray-400 font-normal">{tHints("idr")}</span>
					</label>
					<NumericInput
						id="c-rate"
						value={Number(form.daily_rate) || 0}
						onChange={(v) => setForm((p) => ({ ...p, daily_rate: v > 0 ? String(v) : "" }))}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>
			</div>

			<div>
				<span className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">
					{t("skills")}
				</span>
				<div role="group" aria-label={t("skills")} className="flex flex-wrap gap-2">
					{SKILL_OPTIONS.map((s) => (
						<label
							key={s.value}
							className="flex items-center gap-1.5 cursor-pointer select-none"
						>
							<input
								type="checkbox"
								checked={form.skills.includes(s.value)}
								onChange={() => toggleSkill(s.value)}
								className="rounded border-gray-400 text-brand-600 focus:ring-brand-500"
							/>
							<span className="text-sm">{tSkill(s.tKey)}</span>
						</label>
					))}
				</div>
			</div>

			<div>
				<label
					htmlFor="c-avail"
					className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
				>
					{t("availability")}
				</label>
				<select
					id="c-avail"
					value={form.availability_status}
					onChange={(e) =>
						setForm((p) => ({ ...p, availability_status: e.target.value }))
					}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				>
					{AVAIL_OPTS.map((o) => (
						<option key={o.value} value={o.value}>
							{tAvail(o.tKey)}
						</option>
					))}
				</select>
			</div>

			<div>
				<label
					htmlFor="c-emergency"
					className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
				>
					{t("emergencyContact")}
				</label>
				<input
					id="c-emergency"
					type="text"
					value={form.emergency_contact}
					onChange={(e) =>
						setForm((p) => ({ ...p, emergency_contact: e.target.value }))
					}
					placeholder={t("emergencyPlaceholder")}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<div>
				<label
					htmlFor="c-notes"
					className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
				>
					{t("notes")}
				</label>
				<textarea
					id="c-notes"
					rows={2}
					value={form.notes}
					onChange={(e) => setForm((p) => ({ ...p, notes: e.target.value }))}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<label className="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					checked={form.is_active}
					onChange={(e) =>
						setForm((p) => ({ ...p, is_active: e.target.checked }))
					}
					className="rounded border-gray-400 text-brand-600 focus:ring-brand-500"
				/>
				<span className="text-sm text-gray-700 dark:text-gray-300">{t("active")}</span>
			</label>

			<div className="flex gap-3 pt-2">
				<button
					type="submit"
					disabled={saving}
					className="rounded-lg bg-brand-600 px-5 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
				>
					{saving
						? tButtons("saving")
						: isEdit
							? tButtons("saveChanges")
							: tActions("addCrewMember")}
				</button>
				<button
					type="button"
					onClick={() => router.back()}
					className="rounded-lg border border-gray-300 dark:border-gray-700 px-5 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
				>
					{tButtons("cancel")}
				</button>
			</div>
		</form>
	);
}
