// Generated by GitHub Copilot
import { cn } from "@/lib/utils";

type BadgeVariant =
	| "gray"
	| "blue"
	| "green"
	| "yellow"
	| "red"
	| "purple"
	| "orange";

// Mapped onto the redesign's semantic tokens so every legacy StatusChip usage
// matches the new Badge automatically (theme-aware, no dark: variants).
const VARIANT_CLASSES: Record<BadgeVariant, string> = {
	gray: "bg-subtle text-ink-muted",
	blue: "bg-primary-subtle text-primary-text",
	green: "bg-success-bg text-success-text",
	yellow: "bg-warning-bg text-warning-text",
	red: "bg-danger-bg text-danger-text",
	purple: "bg-primary-subtle text-primary-text",
	orange: "bg-warning-bg text-warning-text",
};

/**
 * Status chip / badge component.
 * @param variant - colour scheme
 * @param label   - displayed text
 */
export function StatusChip({
	label,
	variant = "gray",
	className,
}: {
	label: string;
	variant?: BadgeVariant;
	className?: string;
}) {
	return (
		<span
			className={cn(
				"inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold",
				VARIANT_CLASSES[variant],
				className,
			)}
		>
			{label}
		</span>
	);
}

/** Map lead/proposal/job status strings to badge variants. */
export function leadStatusVariant(status: string): BadgeVariant {
	const map: Record<string, BadgeVariant> = {
		new: "blue",
		survey_scheduled: "purple",
		survey_done: "purple",
		estimating: "orange",
		proposal_sent: "yellow",
		converted: "green",
		closed_lost: "red",
	};
	return map[status] ?? "gray";
}

export function proposalStatusVariant(status: string): BadgeVariant {
	const map: Record<string, BadgeVariant> = {
		draft: "gray",
		sent: "blue",
		negotiating: "yellow",
		approved: "green",
		lost: "red",
		expired: "orange",
	};
	return map[status] ?? "gray";
}

export function jobStatusVariant(status: string): BadgeVariant {
	const map: Record<string, BadgeVariant> = {
		scheduled: "blue",
		in_progress: "yellow",
		completed: "green",
		closed: "gray",
		cancelled: "red",
	};
	return map[status] ?? "gray";
}

export function invoiceStatusVariant(status: string): BadgeVariant {
	const map: Record<string, BadgeVariant> = {
		draft: "gray",
		sent: "blue",
		partially_paid: "yellow",
		paid: "green",
		overdue: "red",
		cancelled: "gray",
	};
	return map[status] ?? "gray";
}

export type Entity = "lead" | "job" | "proposal" | "invoice";

export const VARIANT_FOR_ENTITY: Record<
	Entity,
	(status: string) => BadgeVariant
> = {
	lead: leadStatusVariant,
	job: jobStatusVariant,
	proposal: proposalStatusVariant,
	invoice: invoiceStatusVariant,
};
