// Generated by GitHub Copilot
import { cn } from "@/lib/utils";

type BadgeVariant =
	| "gray"
	| "blue"
	| "green"
	| "yellow"
	| "red"
	| "purple"
	| "orange";

const VARIANT_CLASSES: Record<BadgeVariant, string> = {
	gray: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300",
	blue: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300",
	green: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300",
	yellow:
		"bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300",
	red: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300",
	purple:
		"bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300",
	orange:
		"bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300",
};

/**
 * Status chip / badge component.
 * @param variant - colour scheme
 * @param label   - displayed text
 */
export function StatusChip({
	label,
	variant = "gray",
	className,
}: {
	label: string;
	variant?: BadgeVariant;
	className?: string;
}) {
	return (
		<span
			className={cn(
				"inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold",
				VARIANT_CLASSES[variant],
				className,
			)}
		>
			{label}
		</span>
	);
}

/** Map lead/proposal/job status strings to badge variants. */
export function leadStatusVariant(status: string): BadgeVariant {
	const map: Record<string, BadgeVariant> = {
		new: "blue",
		survey_scheduled: "purple",
		survey_done: "purple",
		estimating: "orange",
		proposal_sent: "yellow",
		converted: "green",
		closed_lost: "red",
	};
	return map[status] ?? "gray";
}

export function proposalStatusVariant(status: string): BadgeVariant {
	const map: Record<string, BadgeVariant> = {
		draft: "gray",
		sent: "blue",
		negotiating: "yellow",
		approved: "green",
		lost: "red",
		expired: "orange",
	};
	return map[status] ?? "gray";
}

export function jobStatusVariant(status: string): BadgeVariant {
	const map: Record<string, BadgeVariant> = {
		scheduled: "blue",
		in_progress: "yellow",
		completed: "green",
		closed: "gray",
		cancelled: "red",
	};
	return map[status] ?? "gray";
}

export function invoiceStatusVariant(status: string): BadgeVariant {
	const map: Record<string, BadgeVariant> = {
		draft: "gray",
		sent: "blue",
		partially_paid: "yellow",
		paid: "green",
		overdue: "red",
		cancelled: "gray",
	};
	return map[status] ?? "gray";
}

export type Entity = "lead" | "job" | "proposal" | "invoice";

export const VARIANT_FOR_ENTITY: Record<
	Entity,
	(status: string) => BadgeVariant
> = {
	lead: leadStatusVariant,
	job: jobStatusVariant,
	proposal: proposalStatusVariant,
	invoice: invoiceStatusVariant,
};
