"use client";
// Generated by GitHub Copilot
import { buildWhatsAppLink, cn } from "@/lib/utils";
import { MessageCircle } from "lucide-react";
import { useTranslations } from "next-intl";

/**
 * Renders a button that opens WhatsApp with a pre-filled message.
 * Uses the wa.me deeplink — no WhatsApp Business API required.
 *
 * @security Opens an external URL; phone and message are validated/encoded.
 */
export function WhatsAppButton({
	phone,
	message,
	label,
	className,
}: {
	phone: string;
	message: string;
	label?: string;
	className?: string;
}) {
	const t = useTranslations("common.actions");
	const visibleLabel = label ?? t("sendViaWhatsapp");
	const href = buildWhatsAppLink(phone, message);

	return (
		<a
			href={href}
			target="_blank"
			rel="noopener noreferrer"
			className={cn(
				"inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium bg-green-500 text-white hover:bg-green-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-500 transition-colors",
				className,
			)}
			aria-label={visibleLabel}
		>
			<MessageCircle size={16} aria-hidden="true" />
			{visibleLabel}
		</a>
	);
}
