"use client";
// Generated by GitHub Copilot
import { useTranslations } from "next-intl";
import { formatDate, formatRupiah } from "@/lib/utils";
import { Card } from "@/components/ui";

type Revision = {
	id: string;
	version_number: number;
	price: number;
	changed_by: string | null;
	note: string | null;
	created_at: string;
};

/**
 * Displays the revision timeline for negotiation tracking.
 */
export function NegotiationHistory({
	revisions,
	status,
}: {
	proposalId: string;
	revisions: Revision[];
	status: string;
}) {
	const t = useTranslations("panels.negotiation");
	if (revisions.length === 0 && status === "draft") return null;

	return (
		<Card
			aria-label="Negotiation history"
			className="p-5"
		>
			<h2 className="text-xs font-semibold text-ink-muted uppercase tracking-wide mb-4">
				{t("title")}
			</h2>

			{revisions.length === 0 ? (
				<p className="text-sm text-ink-faint">{t("empty")}</p>
			) : (
				<ol className="space-y-3">
					{revisions.map((rev, idx) => (
						<li key={rev.id} className="flex gap-3">
							{/* Timeline dot */}
							<div className="flex flex-col items-center">
								<div
									className={`w-2.5 h-2.5 rounded-full mt-1 ${idx === revisions.length - 1 ? "bg-primary" : "bg-line-strong"}`}
									aria-hidden="true"
								/>
								{idx < revisions.length - 1 && (
									<div
										className="flex-1 w-px bg-line my-1"
										aria-hidden="true"
									/>
								)}
							</div>
							{/* Content */}
							<div className="pb-3 min-w-0">
								<div className="flex items-baseline gap-2 flex-wrap">
									<span className="text-sm font-semibold tabular-nums text-ink">
										{formatRupiah(rev.price)}
									</span>
									<span className="text-xs text-ink-muted capitalize">
										by {rev.changed_by ?? "—"}
									</span>
									<span className="text-xs text-ink-faint">
										{formatDate(rev.created_at)}
									</span>
								</div>
								{rev.note && (
									<p className="text-xs text-ink-muted mt-0.5">
										{rev.note}
									</p>
								)}
							</div>
						</li>
					))}
				</ol>
			)}
		</Card>
	);
}
