"use client";
// Generated by GitHub Copilot
import { Document, Font, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { formatRupiah, toRomanMonth } from "@/lib/utils";

// Register a system fallback font to avoid blank-text bugs on some renderers
Font.registerHyphenationCallback((word) => [word]);

const styles = StyleSheet.create({
	page: {
		fontSize: 10,
		fontFamily: "Helvetica",
		paddingTop: 40,
		paddingBottom: 50,
		paddingHorizontal: 48,
		color: "#1f2937",
	},
	headerRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 20,
	},
	company: { fontSize: 18, fontFamily: "Helvetica-Bold", color: "#1d4ed8" },
	companyTagline: { fontSize: 8, color: "#6b7280", marginTop: 2 },
	proposalTitle: {
		fontSize: 13,
		fontFamily: "Helvetica-Bold",
		textAlign: "right",
	},
	proposalMeta: {
		fontSize: 8,
		color: "#6b7280",
		textAlign: "right",
		marginTop: 2,
	},
	divider: {
		borderBottomWidth: 1,
		borderBottomColor: "#e5e7eb",
		marginVertical: 12,
	},
	section: { marginBottom: 14 },
	sectionTitle: {
		fontSize: 9,
		fontFamily: "Helvetica-Bold",
		color: "#6b7280",
		textTransform: "uppercase",
		letterSpacing: 0.8,
		marginBottom: 6,
	},
	row: { flexDirection: "row", marginBottom: 3 },
	label: { flex: 1, color: "#6b7280" },
	value: { flex: 2, fontFamily: "Helvetica-Bold" },
	tableHeader: {
		flexDirection: "row",
		backgroundColor: "#eff6ff",
		paddingVertical: 5,
		paddingHorizontal: 6,
		borderRadius: 3,
		marginBottom: 2,
	},
	tableHeaderCell: { fontFamily: "Helvetica-Bold", color: "#1d4ed8" },
	tableRow: {
		flexDirection: "row",
		paddingVertical: 4,
		paddingHorizontal: 6,
		borderBottomWidth: 0.5,
		borderBottomColor: "#f3f4f6",
	},
	totalRow: {
		flexDirection: "row",
		paddingVertical: 6,
		paddingHorizontal: 6,
		backgroundColor: "#eff6ff",
		borderRadius: 3,
		marginTop: 4,
	},
	totalLabel: { flex: 1, fontFamily: "Helvetica-Bold", fontSize: 11 },
	totalValue: { fontFamily: "Helvetica-Bold", fontSize: 11, color: "#1d4ed8" },
	terms: { fontSize: 8, color: "#9ca3af", lineHeight: 1.6 },
	footer: { position: "absolute", bottom: 24, left: 48, right: 48 },
	footerText: { fontSize: 7, color: "#d1d5db", textAlign: "center" },
	signature: {
		marginTop: 32,
		flexDirection: "row",
		justifyContent: "flex-end",
	},
	signBox: { width: 160, alignItems: "center" },
	signLine: {
		borderBottomWidth: 1,
		borderBottomColor: "#374151",
		width: 120,
		marginBottom: 4,
	},
	signName: { fontFamily: "Helvetica-Bold", fontSize: 9 },
	signRole: { fontSize: 8, color: "#6b7280" },
});

type Outputs = {
	vehicle_cost?: number;
	manpower_cost?: number;
	food_cost?: number;
	packing_cost?: number;
	toll_cost?: number;
	operational_buffer?: number;
	adjusted_cost?: number;
	final_profit?: number;
	internal_target_price?: number;
	initial_offer_price?: number;
};

export interface ProposalPDFProps {
	proposal: {
		proposal_number: string;
		final_price: number | null;
		created_at: string;
		approved_at: string | null;
	};
	customer: { name: string; phone: string | null; email: string | null };
	lead: {
		pickup_address: string | null;
		destination_address: string | null;
		preferred_date: string | null;
	};
	outputs: Outputs;
	/** Company identity from system_settings. */
	company: { name: string; tagline: string };
	/** Proposal template content from system_settings. */
	template: { terms: string; signatureName: string; signatureRole: string };
}

/**
 * PDF document for a proposal.
 * Rendered entirely client-side via @react-pdf/renderer.
 */
export function ProposalPDF({
	proposal,
	customer,
	lead,
	outputs,
	company,
	template,
}: ProposalPDFProps) {
	const date = new Date(proposal.created_at);
	const displayDate = `${date.getDate()} ${date.toLocaleString("en", { month: "long" })} ${date.getFullYear()}`;

	const lineItems = [
		{ label: "Transportation (vehicle)", value: outputs.vehicle_cost },
		{ label: "Manpower", value: outputs.manpower_cost },
		{ label: "Meals & refreshments", value: outputs.food_cost },
		{ label: "Packing materials", value: outputs.packing_cost },
		{ label: "Toll & parking", value: outputs.toll_cost },
		{ label: "Operational buffer", value: outputs.operational_buffer },
	].filter((r) => (r.value ?? 0) > 0);

	return (
		<Document title={`Proposal ${proposal.proposal_number}`} author={company.name}>
			<Page size="A4" style={styles.page}>
				{/* Header */}
				<View style={styles.headerRow}>
					<View>
						<Text style={styles.company}>{company.name}</Text>
						<Text style={styles.companyTagline}>{company.tagline}</Text>
					</View>
					<View>
						<Text style={styles.proposalTitle}>PROPOSAL</Text>
						<Text style={styles.proposalMeta}>{proposal.proposal_number}</Text>
						<Text style={styles.proposalMeta}>{displayDate}</Text>
					</View>
				</View>

				<View style={styles.divider} />

				{/* Customer + Move info */}
				<View style={{ flexDirection: "row", gap: 24, marginBottom: 14 }}>
					<View style={{ flex: 1 }}>
						<Text style={styles.sectionTitle}>Prepared for</Text>
						<Text style={{ fontFamily: "Helvetica-Bold", fontSize: 11 }}>{customer.name}</Text>
						{customer.phone && (
							<Text style={{ color: "#6b7280", fontSize: 9, marginTop: 2 }}>{customer.phone}</Text>
						)}
						{customer.email && (
							<Text style={{ color: "#6b7280", fontSize: 9 }}>{customer.email}</Text>
						)}
					</View>
					<View style={{ flex: 1 }}>
						<Text style={styles.sectionTitle}>Move details</Text>
						{lead.pickup_address && (
							<View style={styles.row}>
								<Text style={styles.label}>From</Text>
								<Text style={styles.value}>{lead.pickup_address}</Text>
							</View>
						)}
						{lead.destination_address && (
							<View style={styles.row}>
								<Text style={styles.label}>To</Text>
								<Text style={styles.value}>{lead.destination_address}</Text>
							</View>
						)}
						{lead.preferred_date && (
							<View style={styles.row}>
								<Text style={styles.label}>Preferred date</Text>
								<Text style={styles.value}>{lead.preferred_date}</Text>
							</View>
						)}
					</View>
				</View>

				<View style={styles.divider} />

				{/* Pricing table */}
				<View style={styles.section}>
					<Text style={styles.sectionTitle}>Pricing breakdown</Text>
					<View style={styles.tableHeader}>
						<Text style={[styles.tableHeaderCell, { flex: 1 }]}>Description</Text>
						<Text style={[styles.tableHeaderCell, { width: 100, textAlign: "right" }]}>Amount</Text>
					</View>
					{lineItems.map((item) => (
						<View key={item.label} style={styles.tableRow}>
							<Text style={{ flex: 1 }}>{item.label}</Text>
							<Text
								style={{
									width: 100,
									textAlign: "right",
									fontFamily: "Helvetica",
								}}
							>
								{formatRupiah(item.value ?? 0)}
							</Text>
						</View>
					))}
					<View style={styles.totalRow}>
						<Text style={styles.totalLabel}>Total</Text>
						<Text style={styles.totalValue}>
							{formatRupiah(proposal.final_price ?? outputs.initial_offer_price ?? 0)}
						</Text>
					</View>
				</View>

				<View style={styles.divider} />

				{/* Terms */}
				<View style={styles.section}>
					<Text style={styles.sectionTitle}>Terms & Conditions</Text>
					<Text style={styles.terms}>{template.terms}</Text>
				</View>

				{/* Signature */}
				<View style={styles.signature}>
					<View style={styles.signBox}>
						<View style={styles.signLine} />
						<Text style={styles.signName}>{template.signatureName}</Text>
						<Text style={styles.signRole}>{template.signatureRole}</Text>
					</View>
				</View>

				{/* Footer */}
				<View style={styles.footer} fixed>
					<Text style={styles.footerText}>
						{company.name} · Confidential · {proposal.proposal_number}
					</Text>
				</View>
			</Page>
		</Document>
	);
}

/**
 * Helper: builds the `toRomanMonth`-based proposal number display string.
 */
export function buildProposalFilename(proposalNumber: string) {
	return `Proposal_${proposalNumber.replace(/\//g, "-")}.pdf`;
}

// Re-export toRomanMonth used by filename builder
export { toRomanMonth };
