"use client";
// Generated by GitHub Copilot
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";
import { syncJobToCalendar } from "@/lib/gcal/actions";
import Link from "next/link";
import { formatRupiah } from "@/lib/utils";
import { NumericInput } from "@/components/shared/NumericInput";
import { WhatsAppButton } from "@/components/shared/WhatsAppButton";

type Proposal = {
	id: string;
	status: string;
	final_price: number | null;
	pdf_url: string | null;
	lead_id: string;
};

type Lead = {
	id: string;
	pickup_address: string | null;
	destination_address: string | null;
	preferred_date: string | null;
} | null;

type Customer = {
	id: string;
	name: string;
	phone: string | null;
} | null;

type Job = { id: string; job_number: string; status: string } | null;

/**
 * Proposal action panel — buttons change based on proposal.status.
 */
export function ProposalActionPanel({
	proposal,
	lead,
	customer,
	hasEstimation,
	job,
}: {
	proposal: Proposal;
	lead: Lead;
	customer: Customer;
	hasEstimation: boolean;
	job: Job;
}) {
	const router = useRouter();
	const t = useTranslations("panels.proposalActions");
	const [isPending, startTransition] = useTransition();
	const [showCounterModal, setShowCounterModal] = useState(false);
	const [showLostModal, setShowLostModal] = useState(false);
	const [showJobModal, setShowJobModal] = useState(false);
	const [error, setError] = useState<string | null>(null);

	// ── Mark as Sent ────────────────────────────────────────────────
	async function handleMarkSent() {
		setError(null);
		const supabase = createClient();
		// Get current max version
		const { data: revs } = await supabase
			.from("proposal_revisions")
			.select("version_number")
			.eq("proposal_id", proposal.id)
			.order("version_number", { ascending: false })
			.limit(1);

		const nextVersion = (revs?.[0]?.version_number ?? 0) + 1;

		const [updateRes, revRes] = await Promise.all([
			supabase
				.from("proposals")
				.update({ status: "sent" })
				.eq("id", proposal.id),
			supabase.from("proposal_revisions").insert({
				proposal_id: proposal.id,
				version_number: nextVersion,
				price: proposal.final_price ?? 0,
				changed_by: "operator",
				note: "Initial proposal sent",
			}),
		]);

		if (updateRes.error || revRes.error) {
			setError(updateRes.error?.message ?? revRes.error?.message ?? "Error");
			return;
		}

		// Update lead status
		await supabase
			.from("leads")
			.update({ status: "proposal_sent" })
			.eq("id", proposal.lead_id);
		startTransition(() => router.refresh());
	}

	// ── Mark Approved ───────────────────────────────────────────────
	async function handleMarkApproved() {
		setError(null);
		const supabase = createClient();
		const { data: revs } = await supabase
			.from("proposal_revisions")
			.select("version_number")
			.eq("proposal_id", proposal.id)
			.order("version_number", { ascending: false })
			.limit(1);

		const nextVersion = (revs?.[0]?.version_number ?? 0) + 1;

		await Promise.all([
			supabase
				.from("proposals")
				.update({
					status: "approved",
					approved_at: new Date().toISOString(),
				})
				.eq("id", proposal.id),
			supabase.from("proposal_revisions").insert({
				proposal_id: proposal.id,
				version_number: nextVersion,
				price: proposal.final_price ?? 0,
				changed_by: "operator",
				note: "Approved by customer",
			}),
		]);

		startTransition(() => router.refresh());
	}

	// ── WhatsApp message templates ──────────────────────────────────
	const waMessage = customer?.phone
		? `Halo ${customer.name}, berikut proposal pindahan dari IM Moving:%0A%0ANo. Proposal: ${proposal.id}%0ATotal: Rp ${proposal.final_price?.toLocaleString("id-ID") ?? "?"}%0A%0ASilakan dicek dan konfirmasi. Terima kasih.`
		: "";

	return (
		<div className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-5 space-y-4">
			<h2 className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">
				{t("title")}
			</h2>

			{error && (
				<div
					role="alert"
					className="rounded bg-red-50 dark:bg-red-900/20 border border-red-200 px-3 py-2 text-xs text-red-700 dark:text-red-300"
				>
					{error}
				</div>
			)}

			{/* ── DRAFT ── */}
			{proposal.status === "draft" && (
				<div className="space-y-2">
					<Link
						href={`/estimations/new?proposal_id=${proposal.id}`}
						className="block w-full text-center rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{hasEstimation ? t("editEstimation") : t("createEstimation")}
					</Link>
					{hasEstimation && (
						<button
							type="button"
							onClick={handleMarkSent}
							disabled={isPending || !proposal.final_price}
							className="w-full rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{t("markAsSent")}
						</button>
					)}
				</div>
			)}

			{/* ── SENT / NEGOTIATING ── */}
			{(proposal.status === "sent" || proposal.status === "negotiating") && (
				<div className="space-y-2">
					{customer?.phone && (
						<WhatsAppButton
							phone={customer.phone}
							message={waMessage}
							label={t("sendViaWhatsapp")}
							className="w-full justify-center"
						/>
					)}
					<button
						type="button"
						onClick={() => setShowCounterModal(true)}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{t("recordCounterOffer")}
					</button>
					<button
						type="button"
						onClick={handleMarkApproved}
						disabled={isPending}
						className="w-full rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{t("markApproved")}
					</button>
					<button
						type="button"
						onClick={() => setShowLostModal(true)}
						className="w-full rounded-lg border border-red-300 dark:border-red-800 px-4 py-2 text-sm font-medium text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 transition-colors"
					>
						{t("markLost")}
					</button>
				</div>
			)}

			{/* ── APPROVED ── */}
			{proposal.status === "approved" && !job && (
				<div className="space-y-2">
					<div className="text-sm text-green-600 dark:text-green-400 font-medium">
						✓ {t("approved")} —{" "}
						{proposal.final_price ? formatRupiah(proposal.final_price) : "—"}
					</div>
					<button
						type="button"
						onClick={() => setShowJobModal(true)}
						className="w-full rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{t("convertToJob")}
					</button>
				</div>
			)}

			{/* ── JOB CREATED ── */}
			{job && (
				<div className="space-y-2">
					<p className="text-sm text-gray-500 dark:text-gray-400">
						{t("jobCreated")}
					</p>
					<Link
						href={`/jobs/${job.id}`}
						className="block w-full text-center rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{t("viewJobWith", { number: job.job_number })}
					</Link>
				</div>
			)}

			{/* ── LOST / EXPIRED ── */}
			{(proposal.status === "lost" || proposal.status === "expired") && (
				<p className="text-sm text-gray-500">{t("noFurtherActions")}</p>
			)}

			{/* Modals */}
			{showCounterModal && (
				<CounterOfferModal
					proposalId={proposal.id}
					currentPrice={proposal.final_price ?? 0}
					onClose={() => setShowCounterModal(false)}
					onDone={() => {
						setShowCounterModal(false);
						startTransition(() => router.refresh());
					}}
				/>
			)}
			{showLostModal && (
				<MarkLostModal
					proposalId={proposal.id}
					leadId={proposal.lead_id}
					onClose={() => setShowLostModal(false)}
					onDone={() => {
						setShowLostModal(false);
						startTransition(() => router.refresh());
					}}
				/>
			)}
			{showJobModal && (
				<ConvertToJobModal
					proposalId={proposal.id}
					leadId={proposal.lead_id}
					preferredDate={lead?.preferred_date ?? null}
					revenue={proposal.final_price ?? 0}
					customerName={customer?.name ?? ""}
					onClose={() => setShowJobModal(false)}
				/>
			)}
		</div>
	);
}

// ── Counter-offer Modal ───────────────────────────────────────────────────────
function CounterOfferModal({
	proposalId,
	currentPrice,
	onClose,
	onDone,
}: {
	proposalId: string;
	currentPrice: number;
	onClose: () => void;
	onDone: () => void;
}) {
	const tModal = useTranslations("modals.counterOffer");
	const tButtons = useTranslations("common.buttons");
	const tErrors = useTranslations("common.errors");
	const [form, setForm] = useState({ who: "customer", price: "", note: "" });
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		if (!form.price) {
			setError(tErrors("priceRequired"));
			return;
		}
		setSaving(true);
		try {
			const supabase = createClient();
			const { data: revs } = await supabase
				.from("proposal_revisions")
				.select("version_number")
				.eq("proposal_id", proposalId)
				.order("version_number", { ascending: false })
				.limit(1);

			const nextVersion = (revs?.[0]?.version_number ?? 0) + 1;

			await Promise.all([
				supabase.from("proposal_revisions").insert({
					proposal_id: proposalId,
					version_number: nextVersion,
					price: Number(form.price),
					changed_by: form.who,
					note: form.note.trim() || null,
				}),
				supabase
					.from("proposals")
					.update({
						status: "negotiating",
						final_price: Number(form.price),
					})
					.eq("id", proposalId),
			]);
			onDone();
		} catch (err: unknown) {
			setError(err instanceof Error ? err.message : "Error");
		} finally {
			setSaving(false);
		}
	}

	return (
		<div
			role="dialog"
			aria-modal="true"
			aria-labelledby="counter-title"
			className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4"
		>
			<div className="w-full max-w-sm rounded-xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-6 shadow-xl space-y-4">
				<h3
					id="counter-title"
					className="text-base font-semibold text-gray-900 dark:text-white"
				>
					{tModal("title")}
				</h3>
				{error && (
					<div role="alert" className="text-xs text-red-600 dark:text-red-400">
						{error}
					</div>
				)}
				<form onSubmit={handleSubmit} className="space-y-4">
					<div>
						<label className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">
							{tModal("proposedBy")}
						</label>
						<select
							value={form.who}
							onChange={(e) => setForm((p) => ({ ...p, who: e.target.value }))}
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						>
							<option value="customer">{tModal("customer")}</option>
							<option value="operator">{tModal("operator")}</option>
						</select>
					</div>
					<div>
						<label className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">
							{tModal("newPrice")}{" "}
							<span aria-hidden="true" className="text-red-500">
								*
							</span>
						</label>
						<NumericInput
							value={Number(form.price) || 0}
							onChange={(v) => setForm((p) => ({ ...p, price: v > 0 ? String(v) : "" }))}
							placeholder={new Intl.NumberFormat("id-ID").format(currentPrice)}
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						/>
					</div>
					<div>
						<label className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">
							{tModal("note")}
						</label>
						<input
							type="text"
							value={form.note}
							onChange={(e) => setForm((p) => ({ ...p, note: e.target.value }))}
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						/>
					</div>
					<div className="flex gap-2">
						<button
							type="submit"
							disabled={saving}
							className="flex-1 rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{saving ? tButtons("saving") : tButtons("save")}
						</button>
						<button
							type="button"
							onClick={onClose}
							className="flex-1 rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{tButtons("cancel")}
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}

// ── Mark Lost Modal ──────────────────────────────────────────────────────────
function MarkLostModal({
	proposalId,
	leadId,
	onClose,
	onDone,
}: {
	proposalId: string;
	leadId: string;
	onClose: () => void;
	onDone: () => void;
}) {
	const tModal = useTranslations("modals.markLost");
	const tButtons = useTranslations("common.buttons");
	const [reason, setReason] = useState("Price too high");
	const [note, setNote] = useState("");
	const [saving, setSaving] = useState(false);

	// Value strings are stored verbatim in the DB — preserve them. Labels are translated.
	const REASONS: { value: string; labelKey: "priceTooHigh" | "wentWithCompetitor" | "noResponse" | "other" }[] = [
		{ value: "Price too high", labelKey: "priceTooHigh" },
		{ value: "Went with competitor", labelKey: "wentWithCompetitor" },
		{ value: "No response", labelKey: "noResponse" },
		{ value: "Other", labelKey: "other" },
	];

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setSaving(true);
		const supabase = createClient();
		const fullReason = reason === "Other" ? note : reason;
		await Promise.all([
			supabase
				.from("proposals")
				.update({ status: "lost", closed_reason: fullReason })
				.eq("id", proposalId),
			supabase.from("leads").update({ status: "closed_lost" }).eq("id", leadId),
		]);
		onDone();
	}

	return (
		<div
			role="dialog"
			aria-modal="true"
			aria-labelledby="lost-title"
			className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4"
		>
			<div className="w-full max-w-sm rounded-xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-6 shadow-xl space-y-4">
				<h3
					id="lost-title"
					className="text-base font-semibold text-gray-900 dark:text-white"
				>
					{tModal("title")}
				</h3>
				<form onSubmit={handleSubmit} className="space-y-4">
					<div>
						<label className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">
							{tModal("reason")}
						</label>
						<select
							value={reason}
							onChange={(e) => setReason(e.target.value)}
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						>
							{REASONS.map((r) => (
								<option key={r.value} value={r.value}>
									{tModal(`reasons.${r.labelKey}`)}
								</option>
							))}
						</select>
					</div>
					{reason === "Other" && (
						<div>
							<label className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">
								{tModal("note")}{" "}
								<span aria-hidden="true" className="text-red-500">
									*
								</span>
							</label>
							<input
								type="text"
								required
								value={note}
								onChange={(e) => setNote(e.target.value)}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							/>
						</div>
					)}
					<div className="flex gap-2">
						<button
							type="submit"
							disabled={saving}
							className="flex-1 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 transition-colors"
						>
							{saving ? tButtons("saving") : tModal("confirm")}
						</button>
						<button
							type="button"
							onClick={onClose}
							className="flex-1 rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{tButtons("cancel")}
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}

// ── Convert to Job Modal ──────────────────────────────────────────────────────
function ConvertToJobModal({
	proposalId,
	leadId,
	preferredDate,
	revenue,
	customerName,
	onClose,
}: {
	proposalId: string;
	leadId: string;
	preferredDate: string | null;
	revenue: number;
	customerName: string;
	onClose: () => void;
}) {
	const router = useRouter();
	const tModal = useTranslations("modals.convertToJob");
	const tButtons = useTranslations("common.buttons");
	const tErrors = useTranslations("common.errors");
	const tHints = useTranslations("common.hints");
	const [moveDate, setMoveDate] = useState(preferredDate ?? "");
	const [moveTime, setMoveTime] = useState("");
	const [moveEndDate, setMoveEndDate] = useState("");
	const [moveEndTime, setMoveEndTime] = useState("");
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	async function handleConfirm(e: React.FormEvent) {
		e.preventDefault();
		if (!moveDate) {
			setError(tErrors("moveDateRequired"));
			return;
		}
		setSaving(true);
		try {
			const supabase = createClient();

			// Generate job number
			const year = new Date().getFullYear();
			const { count } = await supabase
				.from("jobs")
				.select("*", { count: "exact", head: true });
			const seq = String((count ?? 0) + 1).padStart(4, "0");
			const jobNumber = `JOB-${year}-${seq}`;

			const { data: newJob, error: jobErr } = await supabase
				.from("jobs")
				.insert({
					proposal_id: proposalId,
					job_number: jobNumber,
					status: "scheduled",
					move_date: moveDate,
					move_time: moveTime || null,
					move_end_date: moveEndDate || null,
					move_end_time: moveEndTime || null,
					revenue: revenue,
				})
				.select("id")
				.single();

			if (jobErr) throw jobErr;

			await supabase
				.from("leads")
				.update({ status: "converted" })
				.eq("id", leadId);

			// Best-effort calendar push — never block job creation on it.
			if (newJob?.id) {
				void syncJobToCalendar(newJob.id).catch(() => {});
			}

			router.push(`/jobs/${newJob.id}`);
		} catch (err: unknown) {
			setError(err instanceof Error ? err.message : "Error");
			setSaving(false);
		}
	}

	return (
		<div
			role="dialog"
			aria-modal="true"
			aria-labelledby="job-title"
			className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4"
		>
			<div className="w-full max-w-sm rounded-xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-6 shadow-xl space-y-4">
				<h3
					id="job-title"
					className="text-base font-semibold text-gray-900 dark:text-white"
				>
					{tModal("title", { name: customerName })}
				</h3>
				{error && (
					<div role="alert" className="text-xs text-red-600 dark:text-red-400">
						{error}
					</div>
				)}
				<form onSubmit={handleConfirm} className="space-y-4">
					<div className="grid grid-cols-2 gap-3">
						<div>
							<label className="block text-xs font-medium mb-1 text-gray-700 dark:text-gray-300">
								{tModal("startDate")}{" "}
								<span aria-hidden="true" className="text-red-500">
									*
								</span>
							</label>
							<input
								type="date"
								required
								value={moveDate}
								onChange={(e) => setMoveDate(e.target.value)}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							/>
						</div>
						<div>
							<label className="block text-xs font-medium mb-1 text-gray-700 dark:text-gray-300">
								{tModal("startTime")}
							</label>
							<input
								type="time"
								value={moveTime}
								onChange={(e) => setMoveTime(e.target.value)}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							/>
						</div>
					</div>
					<div className="grid grid-cols-2 gap-3">
						<div>
							<label className="block text-xs font-medium mb-1 text-gray-700 dark:text-gray-300">
								{tModal("endDate")}{" "}
								<span className="text-gray-400 font-normal">
									{tModal("endDateHint")}
								</span>
							</label>
							<input
								type="date"
								min={moveDate || undefined}
								value={moveEndDate}
								onChange={(e) => setMoveEndDate(e.target.value)}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							/>
						</div>
						<div>
							<label className="block text-xs font-medium mb-1 text-gray-700 dark:text-gray-300">
								{tModal("endTime")}{" "}
								<span className="text-gray-400 font-normal">
									{tHints("optionalParen")}
								</span>
							</label>
							<input
								type="time"
								value={moveEndTime}
								onChange={(e) => setMoveEndTime(e.target.value)}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							/>
						</div>
					</div>
					<p className="text-sm text-gray-500 dark:text-gray-400">
						{tModal("revenueLockedAt", { amount: formatRupiah(revenue) })}
					</p>
					<div className="flex gap-2">
						<button
							type="submit"
							disabled={saving}
							className="flex-1 rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{saving ? tModal("creating") : tModal("createJob")}
						</button>
						<button
							type="button"
							onClick={onClose}
							className="flex-1 rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{tButtons("cancel")}
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}
