// Generated by GitHub Copilot
// MarginCalc pricing logic ported from https://github.com/dondonudon/MarginCalc
// Engine version must be bumped when pricing logic changes.

export const ENGINE_VERSION = '2.2.0'

export type VehicleType = 'pickup' | 'box_truck'

export interface EstimationInputs {
  vehicle_type:    VehicleType
  vehicle_cost:    number  // direct entry; pre-filled from settings when type changes
  crew_count:      number
  crew_day_rate:   number  // per-crew per-day rate
  food_per_crew:   number  // meal value per crew per meal
  packing_service: boolean
  toll_estimate:   number
  other_cost:      number
  is_out_of_town:  boolean
  meals_count:     number  // default 3 for out-of-town, 1 in-town
}

export interface EstimationSettings {
  vehicle_rate_pickup:          number
  vehicle_rate_box_truck:       number
  crew_day_rate:                number
  food_per_crew:                number
  operational_buffer_pct:       number  // e.g. 10 → 10%
  negotiation_buffer_pct:       number  // e.g. 3  → 3%
  packing_bubble_per_roll:      number
  packing_stretchfilm_per_roll: number
  min_target_profit:            number
}

export interface EstimationOutputs {
  vehicle_cost:           number
  manpower_cost:          number
  food_cost:              number
  packing_cost:           number
  toll_cost:              number
  other_cost:             number
  job_cost:               number
  operational_buffer:     number
  adjusted_cost:          number
  margin_pct:             number
  margin_profit:          number
  minimum_profit:         number
  final_profit:           number
  internal_target_price:  number
  initial_offer_price:    number
  effective_crew_count:   number
}

// ── Tiered margin (from MarginCalc) ──────────────────────────────────────────
/**
 * Returns the margin rate for the given adjusted cost.
 */
function getMarginRate(adjustedCost: number): number {
  if (adjustedCost < 1_000_000)  return 0.45
  if (adjustedCost < 3_000_000)  return 0.35
  if (adjustedCost < 7_000_000)  return 0.25
  if (adjustedCost < 15_000_000) return 0.20
  return 0.15
}

/**
 * Returns the minimum profit floor for the given adjusted cost.
 */
function getMinimumProfit(adjustedCost: number): number {
  if (adjustedCost < 1_000_000)  return 300_000
  if (adjustedCost < 3_000_000)  return 500_000
  if (adjustedCost < 7_000_000)  return 750_000
  if (adjustedCost < 15_000_000) return 1_300_000
  return 2_100_000
}

/** Round up to nearest 50,000 IDR. */
function roundUp50k(value: number): number {
  return Math.ceil(value / 50_000) * 50_000
}

// ── Core calculation ─────────────────────────────────────────────────────────
/**
 * Runs the MarginCalc estimation engine.
 * Pure function — no side effects. Safe to call on every form change.
 */
export function calculate(
  inputs: EstimationInputs,
  settings: EstimationSettings
): EstimationOutputs {
  const vehicleCost = inputs.vehicle_cost

  // Out-of-town: +1 crew for destination unloading; meals multiply
  const effectiveCrew  = inputs.is_out_of_town ? inputs.crew_count + 1 : inputs.crew_count
  const mealsCount     = inputs.is_out_of_town ? inputs.meals_count : 1
  const manpowerCost   = effectiveCrew * inputs.crew_day_rate
  const foodCost       = effectiveCrew * inputs.food_per_crew * mealsCount

  const jobCost = vehicleCost + manpowerCost + foodCost + inputs.toll_estimate + inputs.other_cost

  const operationalBuffer = jobCost * (settings.operational_buffer_pct / 100)
  const adjustedCost      = jobCost + operationalBuffer

  const marginRate   = getMarginRate(adjustedCost)
  const marginProfit = adjustedCost * marginRate
  const minProfit    = getMinimumProfit(adjustedCost)
  const finalProfit  = Math.max(marginProfit, minProfit)

  const negotiationBuffer  = settings.negotiation_buffer_pct / 100
  const internalTarget     = roundUp50k(adjustedCost + finalProfit)
  const initialOfferPrice  = roundUp50k(internalTarget * (1 + negotiationBuffer))

  return {
    vehicle_cost:          vehicleCost,
    manpower_cost:         manpowerCost,
    food_cost:             foodCost,
    packing_cost:          0, // packing calculated separately
    toll_cost:             inputs.toll_estimate,
    other_cost:            inputs.other_cost,
    job_cost:              jobCost,
    operational_buffer:    operationalBuffer,
    adjusted_cost:         adjustedCost,
    margin_pct:            marginRate * 100,
    margin_profit:         marginProfit,
    minimum_profit:        minProfit,
    final_profit:          finalProfit,
    internal_target_price: internalTarget,
    initial_offer_price:   initialOfferPrice,
    effective_crew_count:  effectiveCrew,
  }
}

// ── Settings helpers ─────────────────────────────────────────────────────────

/**
 * Parse system_settings rows into a typed EstimationSettings object.
 * Falls back to sensible defaults if a key is missing.
 */
export function parseSettings(
  rows: Array<{ key: string; value: string }>
): EstimationSettings {
  const map = Object.fromEntries(rows.map((r) => [r.key, Number(r.value)]))
  return {
    vehicle_rate_pickup:          map['vehicle_rate_pickup']          ?? 500_000,
    vehicle_rate_box_truck:       map['vehicle_rate_box_truck']       ?? 800_000,
    crew_day_rate:                map['crew_day_rate']                ?? 175_000,
    food_per_crew:                map['food_per_crew']                ?? 35_000,
    operational_buffer_pct:       map['operational_buffer_pct']       ?? 10,
    negotiation_buffer_pct:       map['negotiation_buffer_pct']       ?? 3,
    packing_bubble_per_roll:      map['packing_bubble_per_roll']      ?? 50_000,
    packing_stretchfilm_per_roll: map['packing_stretchfilm_per_roll'] ?? 35_000,
    min_target_profit:            map['min_target_profit']            ?? 500_000,
  }
}
