// Generated by GitHub Copilot
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { formatDate, formatRupiah } from "@/lib/utils";
import {
	buildCompanySettings,
	buildProposalTemplateSettings,
} from "@/lib/pdfSettings";
import {
	StatusChip,
	proposalStatusVariant,
} from "@/components/shared/StatusChip";
import { ProposalActionPanel } from "@/components/proposals/ProposalActionPanel";
import { ProposalDuplicateButton } from "@/components/proposals/ProposalDuplicateButton";
import { NegotiationHistory } from "@/components/proposals/NegotiationHistory";
import { ProposalPDFDownloadButton } from "@/components/proposals/ProposalPDFDownloadButton";

export default async function ProposalDetailPage({
	params,
}: {
	params: Promise<{ id: string }>;
}) {
	const { id } = await params;
	const supabase = await createClient();
	const t = await getTranslations("pages.proposalDetail");
	const tStatus = await getTranslations("status.proposal");
	const tJob = await getTranslations("pages.jobDetail");

	const [
		{ data: proposal },
		{ data: revisions },
		{ data: estimation },
		{ data: job },
		{ data: settingsRows },
	] = await Promise.all([
		supabase
			.from("proposals")
			.select(`
        *,
        leads(
          id, pickup_address, destination_address, preferred_date,
          customers(id, name, phone, email)
        )
      `)
			.eq("id", id)
			.single(),
		supabase
			.from("proposal_revisions")
			.select("*")
			.eq("proposal_id", id)
			.order("version_number"),
		supabase
			.from("estimations")
			.select("id, outputs, inputs, settings_snapshot")
			.eq("proposal_id", id)
			.maybeSingle(),
		supabase
			.from("jobs")
			.select("id, job_number, status")
			.eq("proposal_id", id)
			.maybeSingle(),
		supabase
			.from("system_settings")
			.select("key, value")
			.in("key", [
				"company_name",
				"company_tagline",
				"proposal_terms",
				"proposal_signature_name",
				"proposal_signature_role",
			]),
	]);

	if (!proposal) notFound();

	const settingsMap = Object.fromEntries(
		(settingsRows ?? []).map((s) => [s.key, s.value]),
	);
	const pdfCompany = buildCompanySettings(settingsMap);
	const pdfTemplate = buildProposalTemplateSettings(settingsMap);

	const lead = proposal.leads as {
		id: string;
		pickup_address: string | null;
		destination_address: string | null;
		preferred_date: string | null;
		customers: {
			id: string;
			name: string;
			phone: string | null;
			email: string | null;
		} | null;
	} | null;

	const customer =
		(lead?.customers as {
			id: string;
			name: string;
			phone: string | null;
			email: string | null;
		} | null) ?? null;
	const estimationOutputs = (estimation?.outputs ?? {}) as Record<
		string,
		number
	>;

	return (
		<div className="space-y-6">
			{/* Header */}
			<div className="flex items-start justify-between flex-wrap gap-4">
				<div>
					<div className="flex items-center gap-3 mb-1">
						<h1 className="text-2xl font-bold font-mono text-gray-900 dark:text-white">
							{proposal.proposal_number}
						</h1>
						<StatusChip
							label={tStatus(proposal.status as never)}
							variant={proposalStatusVariant(proposal.status)}
						/>
					</div>
					<p className="text-sm text-gray-500 dark:text-gray-400">
						{customer?.name ?? "—"} ·{" "}
						{t("created", { date: formatDate(proposal.created_at) })}
						{proposal.approved_at &&
							` · ${t("approved", { date: formatDate(proposal.approved_at) })}`}
					</p>
				</div>
				<div className="flex items-center gap-3 flex-wrap">
					{lead && (
						<Link
							href={`/leads/${lead.id}`}
							className="text-sm text-brand-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
						>
							{t("viewLead")}
						</Link>
					)}
					{lead && (proposal.status === "lost" || proposal.status === "expired") && (
						<ProposalDuplicateButton
							proposalId={proposal.id}
							leadId={lead.id}
							serviceType={proposal.service_type ?? "DOM"}
						/>
					)}
					{customer && lead && (
						<ProposalPDFDownloadButton
							pdfProps={{
								proposal: {
									proposal_number: proposal.proposal_number,
									final_price: proposal.final_price,
									created_at: proposal.created_at,
									approved_at: proposal.approved_at,
								},
								customer: {
									name: customer.name,
									phone: customer.phone,
									email: customer.email,
								},
								lead: {
									pickup_address: lead.pickup_address,
									destination_address: lead.destination_address,
									preferred_date: lead.preferred_date,
								},
								outputs: estimationOutputs,
								company: pdfCompany,
								template: pdfTemplate,
							}}
						/>
					)}
				</div>
			</div>

			<div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
				{/* Left: estimation + negotiation */}
				<div className="lg:col-span-2 space-y-6">
					{/* Move summary */}
					{lead && (
						<section className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-5 grid grid-cols-2 gap-4 text-sm">
							<div>
								<p className="text-gray-500 dark:text-gray-400">
									{tJob("pickup")}
								</p>
								<p className="font-medium mt-0.5">
									{lead.pickup_address ?? "—"}
								</p>
							</div>
							<div>
								<p className="text-gray-500 dark:text-gray-400">
									{tJob("destination")}
								</p>
								<p className="font-medium mt-0.5">
									{lead.destination_address ?? "—"}
								</p>
							</div>
							{lead.preferred_date && (
								<div>
									<p className="text-gray-500 dark:text-gray-400">
										{t("preferredDate")}
									</p>
									<p className="font-medium mt-0.5">
										{formatDate(lead.preferred_date)}
									</p>
								</div>
							)}
							{proposal.final_price && (
								<div>
									<p className="text-gray-500 dark:text-gray-400">
										{t("finalPrice")}
									</p>
									<p className="text-lg font-bold mt-0.5 text-brand-600">
										{formatRupiah(proposal.final_price)}
									</p>
								</div>
							)}
						</section>
					)}

					{/* Estimation snapshot */}
					{estimation && (
						<section className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-5">
							<div className="flex items-center justify-between mb-3">
								<h2 className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">
									{t("estimationBreakdown")}
								</h2>
								{proposal.status === "draft" && (
									<Link
										href={`/estimations/new?proposal_id=${id}`}
										className="text-xs text-brand-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
									>
										{t("editEstimation")}
									</Link>
								)}
							</div>
							<EstimationSnapshot
								outputs={estimation.outputs as Record<string, number>}
							/>
						</section>
					)}

					{/* Negotiation history */}
					<NegotiationHistory
						proposalId={id}
						revisions={revisions ?? []}
						status={proposal.status}
					/>
				</div>

				{/* Right: action panel */}
				<div className="lg:col-span-1">
					<ProposalActionPanel
						proposal={{
							id: proposal.id,
							status: proposal.status,
							final_price: proposal.final_price,
							pdf_url: proposal.pdf_url,
							lead_id: (lead as { id: string } | null)?.id ?? "",
						}}
						lead={lead}
						customer={customer}
						hasEstimation={Boolean(estimation)}
						job={job}
					/>
				</div>
			</div>
		</div>
	);
}

async function EstimationSnapshot({
	outputs,
}: {
	outputs: Record<string, number>;
}) {
	const t = await getTranslations("pages.proposalDetail.breakdown");
	const rows: Array<[string, string]> = [
		["vehicle", "vehicle_cost"],
		["manpower", "manpower_cost"],
		["food", "food_cost"],
		["toll", "toll_cost"],
		["operationalBuffer", "operational_buffer"],
		["adjustedCost", "adjusted_cost"],
		["finalProfit", "final_profit"],
		["internalTarget", "internal_target_price"],
		["offerPrice", "initial_offer_price"],
	];

	return (
		<table className="w-full text-sm">
			<tbody className="divide-y divide-gray-100 dark:divide-gray-800">
				{rows
					.filter(([, key]) => outputs[key] > 0)
					.map(([labelKey, key]) => (
						<tr key={key}>
							<td className="py-1.5 text-gray-600 dark:text-gray-400">
								{t(labelKey as never)}
							</td>
							<td className="py-1.5 text-right tabular-nums font-medium">
								{formatRupiah(outputs[key])}
							</td>
						</tr>
					))}
			</tbody>
		</table>
	);
}
