"use client";
// Generated by GitHub Copilot
import { useState, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";

type Customer = { id: string; name: string; phone: string | null };

/**
 * Create new lead form.
 * Supports pre-selecting a customer via ?customer_id= query param.
 */
export default function NewLeadPage() {
	const router = useRouter();
	const sp = useSearchParams();
	const preselectedCustomerId = sp.get("customer_id");
	const t = useTranslations("forms.lead");
	const tButtons = useTranslations("common.buttons");
	const tLeadType = useTranslations("entity.leadType");
	const tChannel = useTranslations("entity.originChannel");

	const [customers, setCustomers] = useState<Customer[]>([]);
	const [form, setForm] = useState({
		customer_id: preselectedCustomerId ?? "",
		pickup_address: "",
		destination_address: "",
		preferred_date: "",
		lead_type: "whatsapp",
		origin_channel: "whatsapp",
		notes: "",
		// New customer inline fields
		new_customer_name: "",
		new_customer_phone: "",
	});
	const [createNewCustomer, setCreateNewCustomer] = useState(
		!preselectedCustomerId,
	);
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	useEffect(() => {
		const supabase = createClient();
		supabase
			.from("customers")
			.select("id, name, phone")
			.order("name")
			.then(({ data }) => setCustomers(data ?? []));
	}, []);

	function handleChange(
		e: React.ChangeEvent<
			HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
		>,
	) {
		setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
	}

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setError(null);
		setSaving(true);

		try {
			const supabase = createClient();
			let customerId = form.customer_id;

			// Create new customer if needed
			if (createNewCustomer) {
				if (!form.new_customer_name.trim())
					throw new Error("Customer name is required.");
				const { data: newCust, error: custErr } = await supabase
					.from("customers")
					.insert({
						name: form.new_customer_name.trim(),
						phone: form.new_customer_phone.trim() || null,
					})
					.select("id")
					.single();
				if (custErr) throw custErr;
				customerId = newCust.id;
			} else {
				if (!customerId) throw new Error("Please select a customer.");
			}

			const { data: lead, error: leadErr } = await supabase
				.from("leads")
				.insert({
					customer_id: customerId,
					pickup_address: form.pickup_address.trim() || null,
					destination_address: form.destination_address.trim() || null,
					preferred_date: form.preferred_date || null,
					lead_type: form.lead_type as
						| "whatsapp"
						| "onsite"
						| "returning"
						| "corporate",
					origin_channel: form.origin_channel as
						| "whatsapp"
						| "call"
						| "referral"
						| "walkin",
					notes: form.notes.trim() || null,
					status: "new",
				})
				.select("id")
				.single();
			if (leadErr) throw leadErr;

			router.push(`/leads/${lead.id}`);
		} catch (err: unknown) {
			setError(err instanceof Error ? err.message : "An error occurred.");
		} finally {
			setSaving(false);
		}
	}

	return (
		<div className="space-y-6">
			<h1 className="text-2xl font-bold text-gray-900 dark:text-white">
				{t("newTitle")}
			</h1>

			<form onSubmit={handleSubmit} className="space-y-5 max-w-lg" noValidate>
				{error && (
					<div
						role="alert"
						className="rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 px-4 py-3 text-sm text-red-700 dark:text-red-300"
					>
						{error}
					</div>
				)}

				{/* Customer selection */}
				<fieldset className="space-y-3">
					<legend className="text-sm font-medium text-gray-700 dark:text-gray-300">
						{t("customer")}
					</legend>
					<div className="flex gap-4">
						<label className="flex items-center gap-2 text-sm">
							<input
								type="radio"
								name="customer_mode"
								checked={!createNewCustomer}
								onChange={() => setCreateNewCustomer(false)}
								className="text-brand-600"
							/>
							{t("existingCustomer")}
						</label>
						<label className="flex items-center gap-2 text-sm">
							<input
								type="radio"
								name="customer_mode"
								checked={createNewCustomer}
								onChange={() => setCreateNewCustomer(true)}
								className="text-brand-600"
							/>
							{t("newCustomer")}
						</label>
					</div>

					{createNewCustomer ? (
						<div className="space-y-3 pl-1">
							<div>
								<label
									htmlFor="new_customer_name"
									className="block text-sm text-gray-600 dark:text-gray-400 mb-1"
								>
									{t("name")}{" "}
									<span aria-hidden="true" className="text-red-500">
										*
									</span>
								</label>
								<input
									id="new_customer_name"
									name="new_customer_name"
									type="text"
									value={form.new_customer_name}
									onChange={handleChange}
									className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
								/>
							</div>
							<div>
								<label
									htmlFor="new_customer_phone"
									className="block text-sm text-gray-600 dark:text-gray-400 mb-1"
								>
									{t("phone")}
								</label>
								<input
									id="new_customer_phone"
									name="new_customer_phone"
									type="tel"
									value={form.new_customer_phone}
									onChange={handleChange}
									className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
								/>
							</div>
						</div>
					) : (
						<select
							name="customer_id"
							value={form.customer_id}
							onChange={handleChange}
							aria-label="Select existing customer"
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						>
							<option value="">— Select customer —</option>
							{customers.map((c) => (
								<option key={c.id} value={c.id}>
									{c.name}
									{c.phone ? ` (${c.phone})` : ""}
								</option>
							))}
						</select>
					)}
				</fieldset>

				{/* Addresses */}
				<div>
					<label
						htmlFor="pickup_address"
						className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
					>
						{t("pickup")}
					</label>
					<input
						id="pickup_address"
						name="pickup_address"
						type="text"
						value={form.pickup_address}
						onChange={handleChange}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>

				<div>
					<label
						htmlFor="destination_address"
						className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
					>
						{t("destination")}
					</label>
					<input
						id="destination_address"
						name="destination_address"
						type="text"
						value={form.destination_address}
						onChange={handleChange}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>

				<div>
					<label
						htmlFor="preferred_date"
						className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
					>
						{t("preferredDate")}
					</label>
					<input
						id="preferred_date"
						name="preferred_date"
						type="date"
						value={form.preferred_date}
						onChange={handleChange}
						className="rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>

				{/* Lead metadata */}
				<div className="grid grid-cols-2 gap-4">
					<div>
						<label
							htmlFor="lead_type"
							className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
						>
							{t("leadType")}
						</label>
						<select
							id="lead_type"
							name="lead_type"
							value={form.lead_type}
							onChange={handleChange}
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						>
							{(["whatsapp", "onsite", "returning", "corporate"] as const).map(
								(v) => (
									<option key={v} value={v}>
										{tLeadType(v)}
									</option>
								),
							)}
						</select>
					</div>
					<div>
						<label
							htmlFor="origin_channel"
							className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
						>
							{t("originChannel")}
						</label>
						<select
							id="origin_channel"
							name="origin_channel"
							value={form.origin_channel}
							onChange={handleChange}
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						>
							{(["whatsapp", "call", "referral", "walkin"] as const).map(
								(v) => (
									<option key={v} value={v}>
										{tChannel(v)}
									</option>
								),
							)}
						</select>
					</div>
				</div>

				<div>
					<label
						htmlFor="notes"
						className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
					>
						{t("notes")}
					</label>
					<textarea
						id="notes"
						name="notes"
						rows={3}
						value={form.notes}
						onChange={handleChange}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none"
					/>
				</div>

				<div className="flex gap-3">
					<button
						type="submit"
						disabled={saving}
						className="rounded-lg bg-brand-600 px-5 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{saving ? tButtons("saving") : t("createLead")}
					</button>
					<button
						type="button"
						onClick={() => router.back()}
						className="rounded-lg border border-gray-300 dark:border-gray-700 px-5 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{tButtons("cancel")}
					</button>
				</div>
			</form>
		</div>
	);
}
