"use client";
// Generated by GitHub Copilot
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";
import Link from "next/link";
import { ArrowLeft, Loader2 } from "lucide-react";

const LEAD_TYPES = ["whatsapp", "onsite", "returning", "corporate"] as const;
const CHANNELS = ["whatsapp", "call", "referral", "walkin"] as const;

/**
 * Lead edit form — loads existing lead and updates it on submit.
 * Customer is not changeable after creation.
 */
export default function EditLeadPage({ params }: { params: { id: string } }) {
	const { id } = params;
	const router = useRouter();
	const t = useTranslations("forms.lead");
	const tButtons = useTranslations("common.buttons");
	const tJob = useTranslations("forms.job");
	const tLeadType = useTranslations("entity.leadType");
	const tChannel = useTranslations("entity.originChannel");

	const [form, setForm] = useState({
		pickup_address: "",
		destination_address: "",
		preferred_date: "",
		lead_type: "whatsapp",
		origin_channel: "whatsapp",
		notes: "",
	});
	const [customerName, setCustomerName] = useState("");
	const [loading, setLoading] = useState(true);
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	useEffect(() => {
		const supabase = createClient();
		supabase
			.from("leads")
			.select("*, customers(name)")
			.eq("id", id)
			.single()
			.then(({ data, error: err }) => {
				if (err || !data) {
					setError("Lead not found.");
					setLoading(false);
					return;
				}
				const c = data.customers as { name: string } | null;
				setCustomerName(c?.name ?? "");
				setForm({
					pickup_address: data.pickup_address ?? "",
					destination_address: data.destination_address ?? "",
					preferred_date: data.preferred_date ?? "",
					lead_type: data.lead_type ?? "whatsapp",
					origin_channel: data.origin_channel ?? "whatsapp",
					notes: data.notes ?? "",
				});
				setLoading(false);
			});
	}, [id]);

	function handleChange(
		e: React.ChangeEvent<
			HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
		>,
	) {
		setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
	}

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setError(null);
		setSaving(true);
		try {
			const supabase = createClient();
			const { error: err } = await supabase
				.from("leads")
				.update({
					pickup_address: form.pickup_address.trim() || null,
					destination_address: form.destination_address.trim() || null,
					preferred_date: form.preferred_date || null,
					lead_type: form.lead_type as (typeof LEAD_TYPES)[number],
					origin_channel: form.origin_channel as (typeof CHANNELS)[number],
					notes: form.notes.trim() || null,
				})
				.eq("id", id);
			if (err) throw err;
			router.push(`/leads/${id}`);
		} catch (err: unknown) {
			setError(err instanceof Error ? err.message : "Save failed.");
		} finally {
			setSaving(false);
		}
	}

	const inputClass =
		"w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-300 bg-white transition-colors";

	if (loading) {
		return (
			<div className="flex items-center justify-center h-40 text-slate-400">
				<Loader2 size={20} className="animate-spin" aria-hidden="true" />
			</div>
		);
	}

	return (
		<div className="max-w-lg mx-auto space-y-5">
			<Link
				href={`/leads/${id}`}
				className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
			>
				<ArrowLeft size={15} aria-hidden="true" />
				{tJob("backToLead")}
			</Link>

			<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
				<h1 className="text-xl font-bold text-slate-800 mb-1">
					{t("editTitle")}
				</h1>
				{customerName && (
					<p className="text-sm text-slate-500 mb-5">
						{t("customer")}:{" "}
						<span className="font-medium text-slate-700">{customerName}</span>
					</p>
				)}

				{error && (
					<div
						role="alert"
						className="mb-4 rounded-xl bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-700"
					>
						{error}
					</div>
				)}

				<form onSubmit={handleSubmit} className="space-y-4" noValidate>
					{/* Pickup address */}
					<div>
						<label
							htmlFor="pickup_address"
							className="block text-sm font-medium text-slate-700 mb-1.5"
						>
							{t("pickup")}
						</label>
						<input
							id="pickup_address"
							name="pickup_address"
							type="text"
							value={form.pickup_address}
							onChange={handleChange}
							className={inputClass}
						/>
					</div>

					{/* Destination address */}
					<div>
						<label
							htmlFor="destination_address"
							className="block text-sm font-medium text-slate-700 mb-1.5"
						>
							{t("destination")}
						</label>
						<input
							id="destination_address"
							name="destination_address"
							type="text"
							value={form.destination_address}
							onChange={handleChange}
							className={inputClass}
						/>
					</div>

					{/* Preferred date */}
					<div>
						<label
							htmlFor="preferred_date"
							className="block text-sm font-medium text-slate-700 mb-1.5"
						>
							{t("preferredDate")}
						</label>
						<input
							id="preferred_date"
							name="preferred_date"
							type="date"
							value={form.preferred_date}
							onChange={handleChange}
							className={inputClass}
						/>
					</div>

					{/* Lead type + Channel */}
					<div className="grid grid-cols-2 gap-3">
						<div>
							<label
								htmlFor="lead_type"
								className="block text-sm font-medium text-slate-700 mb-1.5"
							>
								{t("leadType")}
							</label>
							<select
								id="lead_type"
								name="lead_type"
								value={form.lead_type}
								onChange={handleChange}
								className={inputClass}
							>
								{LEAD_TYPES.map((v) => (
									<option key={v} value={v}>
										{tLeadType(v)}
									</option>
								))}
							</select>
						</div>
						<div>
							<label
								htmlFor="origin_channel"
								className="block text-sm font-medium text-slate-700 mb-1.5"
							>
								{t("originChannel")}
							</label>
							<select
								id="origin_channel"
								name="origin_channel"
								value={form.origin_channel}
								onChange={handleChange}
								className={inputClass}
							>
								{CHANNELS.map((v) => (
									<option key={v} value={v}>
										{tChannel(v)}
									</option>
								))}
							</select>
						</div>
					</div>

					{/* Notes */}
					<div>
						<label
							htmlFor="notes"
							className="block text-sm font-medium text-slate-700 mb-1.5"
						>
							{t("notes")}
						</label>
						<textarea
							id="notes"
							name="notes"
							value={form.notes}
							onChange={handleChange}
							rows={4}
							className={inputClass + " resize-none"}
						/>
					</div>

					{/* Actions */}
					<div className="flex gap-3 pt-1">
						<Link
							href={`/leads/${id}`}
							className="flex-1 text-center rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
						>
							{tButtons("cancel")}
						</Link>
						<button
							type="submit"
							disabled={saving}
							className="flex-1 flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-700 disabled:opacity-60 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-400"
						>
							{saving && (
								<Loader2
									size={15}
									className="animate-spin"
									aria-hidden="true"
								/>
							)}
							{saving ? tButtons("saving") : tButtons("saveChanges")}
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}
