// Generated by GitHub Copilot
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, CalendarDays, User, ClipboardList } from "lucide-react";
import { formatDate } from "@/lib/utils";
import { SurveyDetailClient } from "@/components/surveys/SurveyDetailClient";
import { GCalRetryButton } from "@/components/shared/GCalRetryButton";

/**
 * Survey detail page — shows survey info, special items, media gallery,
 * access notes and general notes. Allows marking the survey as done.
 */
export default async function SurveyDetailPage({
	params,
}: {
	params: Promise<{ id: string }>;
}) {
	const { id } = await params;
	const supabase = await createClient();

	const [{ data: survey }, { data: media }] = await Promise.all([
		supabase
			.from("surveys")
			.select(
				"id, lead_id, scheduled_at, conducted_at, access_notes, special_items, notes, surveyor_id, gcal_event_id, leads(id, pickup_address, destination_address, customers(name))",
			)
			.eq("id", id)
			.single(),
		supabase
			.from("survey_media")
			.select("id, media_type, storage_path, caption, uploaded_at")
			.eq("survey_id", id)
			.order("uploaded_at"),
	]);

	if (!survey) notFound();

	const lead = survey.leads as {
		id: string;
		pickup_address: string | null;
		destination_address: string | null;
		customers: { name: string } | null;
	} | null;

	const customerName = lead?.customers?.name ?? "Unknown Customer";
	const isDone = !!survey.conducted_at;

	return (
		<div className="max-w-3xl mx-auto space-y-5">
			{/* Back link */}
			<Link
				href={`/leads/${survey.lead_id}`}
				className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
			>
				<ArrowLeft size={15} aria-hidden="true" />
				Back to Lead
			</Link>

			{/* Header */}
			<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
				<div className="flex items-start justify-between flex-wrap gap-4">
					<div>
						<h1 className="text-xl font-bold text-slate-800">{customerName}</h1>
						<p className="text-sm text-slate-500 mt-0.5">In-Home Survey</p>
					</div>
					<div className="flex items-center gap-2 flex-wrap">
						<GCalRetryButton
							kind="survey"
							id={survey.id}
							hasEvent={Boolean(survey.gcal_event_id)}
						/>
						<span
							className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-sm font-semibold ${
								isDone
									? "bg-green-100 text-green-700"
									: "bg-amber-100 text-amber-700"
							}`}
						>
							<span
								className="w-1.5 h-1.5 rounded-full bg-current opacity-70"
								aria-hidden="true"
							/>
							{isDone ? "Completed" : "Scheduled"}
						</span>
					</div>
				</div>

				<dl className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
					<div className="flex items-center gap-2 text-slate-600">
						<CalendarDays
							size={15}
							className="text-slate-400 shrink-0"
							aria-hidden="true"
						/>
						<div>
							<dt className="text-xs text-slate-400 leading-none mb-0.5">
								Scheduled
							</dt>
							<dd className="font-medium">{formatDate(survey.scheduled_at)}</dd>
						</div>
					</div>
					{survey.conducted_at && (
						<div className="flex items-center gap-2 text-slate-600">
							<CalendarDays
								size={15}
								className="text-green-400 shrink-0"
								aria-hidden="true"
							/>
							<div>
								<dt className="text-xs text-slate-400 leading-none mb-0.5">
									Completed
								</dt>
								<dd className="font-medium">
									{formatDate(survey.conducted_at)}
								</dd>
							</div>
						</div>
					)}
					{lead?.pickup_address && (
						<div className="flex items-start gap-2 text-slate-600">
							<User
								size={15}
								className="text-slate-400 shrink-0 mt-0.5"
								aria-hidden="true"
							/>
							<div>
								<dt className="text-xs text-slate-400 leading-none mb-0.5">
									Pickup
								</dt>
								<dd className="font-medium">{lead.pickup_address}</dd>
							</div>
						</div>
					)}
					{lead?.destination_address && (
						<div className="flex items-start gap-2 text-slate-600">
							<ClipboardList
								size={15}
								className="text-slate-400 shrink-0 mt-0.5"
								aria-hidden="true"
							/>
							<div>
								<dt className="text-xs text-slate-400 leading-none mb-0.5">
									Destination
								</dt>
								<dd className="font-medium">{lead.destination_address}</dd>
							</div>
						</div>
					)}
				</dl>
			</div>

			{/* Interactive client section: notes, items, media, actions */}
			<SurveyDetailClient
				survey={{
					id: survey.id,
					lead_id: survey.lead_id,
					access_notes: survey.access_notes,
					special_items: survey.special_items as {
						type: string;
						qty: number;
						note: string;
					}[],
					notes: survey.notes,
					conducted_at: survey.conducted_at,
				}}
				initialMedia={media ?? []}
			/>
		</div>
	);
}
