"use client";
import { Plus } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
// Generated by GitHub Copilot
import { useEffect, useState } from "react";
import { BottomNav } from "@/components/layout/BottomNav";
import { SectionTabs } from "@/components/layout/SectionTabs";
import { Sidebar } from "@/components/layout/Sidebar";
import { TopBar } from "@/components/layout/TopBar";
import { QuickLeadModal } from "@/components/leads/QuickLeadModal";
import { CommandPalette } from "@/components/shared/CommandPalette";

/** Maps list-page pathnames to their FAB action. Exact match only — detail and edit pages are excluded. */
const FAB_CONFIG: Record<string, { href: string; label: string }> = {
	"/leads": { href: "/leads/new", label: "New Lead" },
	"/customers": { href: "/customers/new", label: "New Customer" },
	"/fleet": { href: "/fleet/new", label: "New Fleet" },
	"/crew": { href: "/crew/new", label: "New Crew Member" },
};

/**
 * Client shell that owns both the sidebar-collapsed state (desktop) and the
 * mobile drawer open/close state. Persists desktop collapse in localStorage.
 */
export function DashboardShell({
	children,
	userEmail,
}: {
	children: React.ReactNode;
	userEmail: string | null | undefined;
}) {
	const [collapsed, setCollapsed] = useState(false);
	const [mobileOpen, setMobileOpen] = useState(false);
	const pathname = usePathname();
	const fab = FAB_CONFIG[pathname] ?? null;

	// Restore persisted desktop preference after hydration
	useEffect(() => {
		const stored = localStorage.getItem("sidebar-collapsed");
		if (stored !== null) setCollapsed(stored === "true");
	}, []);

	// Lock body scroll when mobile nav is open
	useEffect(() => {
		if (mobileOpen) {
			document.body.style.overflow = "hidden";
		} else {
			document.body.style.overflow = "";
		}
		return () => {
			document.body.style.overflow = "";
		};
	}, [mobileOpen]);

	function toggleDesktop() {
		setCollapsed((prev) => {
			const next = !prev;
			localStorage.setItem("sidebar-collapsed", String(next));
			return next;
		});
	}

	function closeMobile() {
		setMobileOpen(false);
	}

	return (
		<div className="flex min-h-screen bg-[var(--background)]">
			{/* Global ⌘K search palette + fast lead capture */}
			<CommandPalette />
			<QuickLeadModal />

			{/* Mobile overlay backdrop */}
			{mobileOpen && (
				<div
					className="fixed inset-0 z-40 bg-black/50 backdrop-blur-sm md:hidden"
					aria-hidden="true"
					onClick={closeMobile}
				/>
			)}

			<Sidebar
				collapsed={collapsed}
				onToggle={toggleDesktop}
				mobileOpen={mobileOpen}
				onMobileClose={closeMobile}
			/>

			<div className="flex-1 flex flex-col min-w-0 overflow-hidden">
				<TopBar
					userEmail={userEmail}
					onToggleSidebar={toggleDesktop}
					collapsed={collapsed}
					onMobileMenuOpen={() => setMobileOpen(true)}
				/>
				<main id="main-content" className="flex-1 overflow-y-auto p-4 pb-24 md:p-6" tabIndex={-1}>
					<SectionTabs />
					{children}
				</main>

				{/* Floating action button — only on list pages that support adding */}
				{fab && (
					<Link
						href={fab.href}
						aria-label={fab.label}
						className="fixed bottom-24 right-4 md:bottom-6 md:right-6 w-[52px] h-[52px] rounded-full bg-primary hover:bg-primary-hover text-primary-fg shadow-token-md flex items-center justify-center transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] focus-visible:ring-offset-2 z-30 hover:scale-105 active:scale-95"
					>
						<Plus size={22} aria-hidden="true" />
					</Link>
				)}

				{/* Mobile field-mode bottom navigation */}
				<BottomNav onMenu={() => setMobileOpen(true)} />
			</div>
		</div>
	);
}
