"use client";
// Generated by GitHub Copilot
import { createClient } from "@/lib/supabase/client";
import { cn } from "@/lib/utils";
import {
	BarChart3,
	Briefcase,
	CalendarDays,
	FileText,
	LayoutDashboard,
	LogOut,
	Receipt,
	Search,
	Settings,
	Truck,
	UserCheck,
	Users,
	X,
} from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useTranslations } from "next-intl";

type NavKey =
	| "dashboard"
	| "leads"
	| "proposals"
	| "jobs"
	| "calendar"
	| "customers"
	| "vendors"
	| "crew"
	| "invoices"
	| "reports";

type GroupKey = "pipeline" | "operations" | "resources" | "finance";

const NAV_GROUPS: Array<{
	groupKey: GroupKey;
	items: Array<{ href: string; key: NavKey; icon: typeof LayoutDashboard }>;
}> = [
	{
		groupKey: "pipeline",
		items: [
			{ href: "/leads", key: "leads", icon: Search },
			{ href: "/proposals", key: "proposals", icon: FileText },
		],
	},
	{
		groupKey: "operations",
		items: [
			{ href: "/jobs", key: "jobs", icon: Briefcase },
			{ href: "/calendar", key: "calendar", icon: CalendarDays },
		],
	},
	{
		groupKey: "resources",
		items: [
			{ href: "/customers", key: "customers", icon: Users },
			{ href: "/vendors", key: "vendors", icon: Truck },
			{ href: "/crew", key: "crew", icon: UserCheck },
		],
	},
	{
		groupKey: "finance",
		items: [
			{ href: "/invoices", key: "invoices", icon: Receipt },
			{ href: "/reports", key: "reports", icon: BarChart3 },
		],
	},
];

/**
 * Sidebar navigation — dark navy, violet active state, collapsible on desktop.
 * On mobile: fixed drawer that slides in from the left.
 */
export function Sidebar({
	collapsed,
	mobileOpen,
	onMobileClose,
}: {
	collapsed: boolean;
	onToggle: () => void;
	mobileOpen: boolean;
	onMobileClose: () => void;
}) {
	const pathname = usePathname();
	const router = useRouter();
	const t = useTranslations("nav");
	const tGroups = useTranslations("nav.groups");
	const tTopbar = useTranslations("topbar");

	async function handleLogout() {
		const supabase = createClient();
		await supabase.auth.signOut();
		router.push("/login");
	}

	function NavLink({
		href,
		navKey,
		icon: Icon,
	}: {
		href: string;
		navKey: NavKey | "settings";
		icon: typeof LayoutDashboard;
	}) {
		const label = t(navKey);
		const isActive =
			href === "/dashboard"
				? pathname === "/dashboard"
				: pathname.startsWith(href);
		return (
			<Link
				href={href}
				title={collapsed ? label : undefined}
				onClick={onMobileClose}
				className={cn(
					"flex items-center rounded-lg text-sm font-medium transition-all duration-150",
					collapsed
						? "md:justify-center md:w-10 md:h-10 md:mx-auto gap-3 px-3 py-2"
						: "gap-3 px-3 py-2",
					isActive
						? "bg-brand-600 text-white shadow-md shadow-brand-600/30"
						: "text-white/65 hover:bg-white/10 hover:text-white",
				)}
				aria-current={isActive ? "page" : undefined}
			>
				<Icon size={18} aria-hidden="true" className="shrink-0" />
				<span className={cn(collapsed && "md:hidden")}>{label}</span>
			</Link>
		);
	}

	return (
		<aside
			className={cn(
				// Mobile: fixed drawer, hidden off-screen by default
				"fixed inset-y-0 left-0 z-50 flex flex-col bg-[var(--sidebar)] text-white border-r border-white/[0.06] transition-transform duration-300 ease-in-out",
				"md:relative md:translate-x-0 md:z-auto",
				// Mobile open/close
				mobileOpen ? "translate-x-0" : "-translate-x-full md:translate-x-0",
				// Desktop width
				collapsed ? "md:w-16 w-[232px]" : "w-[232px]",
			)}
			aria-label="Main navigation"
		>
			{/* Brand */}
			<div
				className={cn(
					"flex items-center gap-3 px-4 py-5 border-b border-white/[0.06] shrink-0",
					collapsed && "md:justify-center md:px-0",
				)}
			>
				<div className="w-8 h-8 rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 flex items-center justify-center shrink-0 shadow-lg shadow-brand-900/40">
					<Truck size={15} className="text-white" aria-hidden="true" />
				</div>
				<div className={cn("overflow-hidden flex-1", collapsed && "md:hidden")}>
					<p className="text-[13px] font-bold text-white leading-tight whitespace-nowrap">
						Indo Mover
					</p>
					<p className="text-[10px] text-white/50 whitespace-nowrap">
						Operations Platform
					</p>
				</div>
				{/* Close button — mobile only */}
				<button
					type="button"
					onClick={onMobileClose}
					aria-label={tTopbar("openMenu")}
					className="md:hidden ml-auto p-1.5 rounded-lg text-white/40 hover:text-white/80 hover:bg-white/[0.06] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-400"
				>
					<X size={18} aria-hidden="true" />
				</button>
			</div>

			{/* Navigation */}
			<nav
				className="flex-1 overflow-y-auto py-3 scrollbar-thin"
				aria-label="Primary"
			>
				{/* Dashboard — standalone */}
				<div className={cn("mb-1", collapsed ? "px-2" : "px-3")}>
					<NavLink href="/dashboard" navKey="dashboard" icon={LayoutDashboard} />
				</div>

				{/* Grouped sections */}
				{NAV_GROUPS.map(({ groupKey, items }) => (
					<div key={groupKey} className={cn("mt-4", collapsed ? "px-2" : "px-3")}>
						{/* Group label — hidden when collapsed */}
						{!collapsed && (
							<p className="px-3 mb-1 text-[10px] font-semibold uppercase tracking-widest text-white/30 select-none">
								{tGroups(groupKey)}
							</p>
						)}
						{collapsed && (
							<div className="my-1 border-t border-white/[0.06]" />
						)}
						<div className="space-y-0.5">
							{items.map(({ href, key, icon }) => (
								<NavLink key={href} href={href} navKey={key} icon={icon} />
							))}
						</div>
					</div>
				))}

				{/* Divider before settings */}
				<div
					className={cn(
						"my-3 border-t border-white/[0.06]",
						collapsed ? "mx-2" : "mx-3",
					)}
				/>

				{/* Settings */}
				<div className={cn(collapsed ? "px-2" : "px-3")}>
					<NavLink href="/settings" navKey="settings" icon={Settings} />
				</div>
			</nav>

			{/* Bottom: sign out */}
			<div
				className={cn(
					"border-t border-white/[0.06] py-3 space-y-1",
					collapsed ? "px-2" : "px-3",
				)}
			>
				<button
					type="button"
					onClick={handleLogout}
					title={collapsed ? t("signOut") : undefined}
					className={cn(
						"flex items-center rounded-lg text-sm font-medium text-white/55 hover:bg-white/10 hover:text-white/85 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-400 w-full",
						collapsed
							? "md:justify-center md:w-10 md:h-10 md:mx-auto gap-2.5 px-3 py-2"
							: "gap-2.5 px-3 py-2",
					)}
				>
					<LogOut size={16} aria-hidden="true" />
					<span className={cn(collapsed && "md:hidden")}>{t("signOut")}</span>
				</button>
			</div>
		</aside>
	);
}
