"use client";
// Generated by GitHub Copilot
import { useState, useEffect } from "react";
import { Sun, Moon } from "lucide-react";

/**
 * Theme toggle button — persists "dark" | "light" in localStorage.
 * Falls back to the OS prefers-color-scheme on first visit.
 * Applies/removes the `dark` class on <html> immediately.
 *
 * Returns null before hydration to avoid flicker (the inline script in
 * app/layout.tsx has already applied the correct class server-side).
 */
export function ThemeToggle() {
	const [dark, setDark] = useState(false);
	const [mounted, setMounted] = useState(false);

	useEffect(() => {
		setMounted(true);
		// Read current state from the DOM (set by the inline script in layout.tsx)
		setDark(document.documentElement.classList.contains("dark"));
	}, []);

	function toggle() {
		const next = !dark;
		setDark(next);
		localStorage.setItem("theme", next ? "dark" : "light");
		document.documentElement.classList.toggle("dark", next);
	}

	// Avoid hydration mismatch — render nothing until client-side
	if (!mounted) {
		return <div className="w-8 h-8" aria-hidden="true" />;
	}

	return (
		<button
			type="button"
			onClick={toggle}
			aria-label={dark ? "Switch to light mode" : "Switch to dark mode"}
			aria-pressed={dark}
			className="w-8 h-8 flex items-center justify-center rounded-lg text-ink-faint hover:bg-subtle hover:text-ink transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]"
		>
			{dark ? (
				<Sun size={16} aria-hidden="true" />
			) : (
				<Moon size={16} aria-hidden="true" />
			)}
		</button>
	);
}
