"use client";
// Generated by GitHub Copilot
import { useEffect, useState } from "react";
import { Search, Menu, PanelLeftClose, PanelLeftOpen, Plus } from "lucide-react";
import { useTranslations } from "next-intl";
import { LocaleToggle } from "@/components/layout/LocaleToggle";
import { ThemeToggle } from "@/components/layout/ThemeToggle";
import { Button } from "@/components/ui";

/**
 * Top application bar with the global search trigger, sidebar toggle, theme,
 * and user avatar. The search button opens the ⌘K command palette (mounted at
 * the dashboard root) — it doesn't run an inline search itself.
 */
export function TopBar({
	userEmail,
	onToggleSidebar,
	collapsed,
	onMobileMenuOpen,
}: {
	userEmail?: string | null;
	onToggleSidebar?: () => void;
	collapsed?: boolean;
	onMobileMenuOpen?: () => void;
}) {
	const t = useTranslations("topbar");
	const tField = useTranslations("field");
	const initials = userEmail
		? userEmail.split("@")[0].slice(0, 2).toUpperCase()
		: "IM";

	// Detect platform so we show the right modifier label (⌘ on Mac, Ctrl elsewhere).
	const [isMac, setIsMac] = useState(true);
	useEffect(() => {
		setIsMac(
			typeof navigator !== "undefined" && /Mac|iPhone|iPad/.test(navigator.platform),
		);
	}, []);

	function openSearch() {
		window.dispatchEvent(new Event("imops:open-search"));
	}

	return (
		<header className="h-14 shrink-0 flex items-center gap-3 bg-surface backdrop-blur-sm border-b border-line shadow-token-sm px-4 sticky top-0 z-30">
			{/* Mobile hamburger */}
			{onMobileMenuOpen && (
				<button
					type="button"
					onClick={onMobileMenuOpen}
					aria-label={t("openMenu")}
					aria-expanded={false}
					className="md:hidden w-9 h-9 flex items-center justify-center rounded-lg text-ink-muted hover:bg-subtle hover:text-ink transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] shrink-0"
				>
					<Menu size={20} aria-hidden="true" />
				</button>
			)}

			{/* Desktop sidebar toggle */}
			{onToggleSidebar && (
				<button
					type="button"
					onClick={onToggleSidebar}
					aria-label={collapsed ? t("expandSidebar") : t("collapseSidebar")}
					className="hidden md:flex w-8 h-8 items-center justify-center rounded-lg text-ink-muted hover:bg-subtle hover:text-ink transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] shrink-0"
				>
					{collapsed ? (
						<PanelLeftOpen size={18} aria-hidden="true" />
					) : (
						<PanelLeftClose size={18} aria-hidden="true" />
					)}
				</button>
			)}

			{/* Search trigger — opens the ⌘K command palette */}
			<button
				type="button"
				onClick={openSearch}
				aria-label={`${t("searchPlaceholder")} (${isMac ? "⌘" : "Ctrl"}+K)`}
				aria-haspopup="dialog"
				className="flex-1 max-w-xs flex items-center gap-2 pl-3 pr-2 py-2 text-sm text-ink-muted bg-subtle hover:bg-surface-raised rounded-lg border border-line transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]"
			>
				<Search size={14} aria-hidden="true" className="shrink-0" />
				<span className="flex-1 text-left truncate">{t("searchPlaceholder")}</span>
				<kbd className="hidden sm:inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded bg-surface border border-line text-[10px] font-mono text-ink-muted">
					{isMac ? "⌘" : "Ctrl"} K
				</kbd>
			</button>

			<div className="ml-auto flex items-center gap-2">
				{/* Fast lead capture — opens the global QuickLeadModal */}
				<Button
					size="sm"
					onClick={() => window.dispatchEvent(new Event("imops:new-lead"))}
					className="hidden md:inline-flex"
				>
					<Plus size={15} aria-hidden="true" />
					{tField("newLead")}
				</Button>
				<LocaleToggle />
				<ThemeToggle />

				{/* Avatar */}
				<button
					type="button"
					aria-label={`${t("account")}: ${userEmail ?? "User"}`}
					className="w-9 h-9 ml-1 rounded-full bg-gradient-to-br from-brand-500 to-brand-700 text-white text-[11px] font-bold flex items-center justify-center shadow-token-sm hover:shadow-token-md hover:scale-105 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]"
				>
					{initials}
				</button>
			</div>
		</header>
	);
}
