"use client";
// Generated by GitHub Copilot
import { useEffect, useState } from "react";
import { Search, Menu, PanelLeftClose, PanelLeftOpen } from "lucide-react";
import { useTranslations } from "next-intl";
import { LocaleToggle } from "@/components/layout/LocaleToggle";
import { ThemeToggle } from "@/components/layout/ThemeToggle";

/**
 * Top application bar with the global search trigger, sidebar toggle, theme,
 * and user avatar. The search button opens the ⌘K command palette (mounted at
 * the dashboard root) — it doesn't run an inline search itself.
 */
export function TopBar({
	userEmail,
	onToggleSidebar,
	collapsed,
	onMobileMenuOpen,
}: {
	userEmail?: string | null;
	onToggleSidebar?: () => void;
	collapsed?: boolean;
	onMobileMenuOpen?: () => void;
}) {
	const t = useTranslations("topbar");
	const initials = userEmail
		? userEmail.split("@")[0].slice(0, 2).toUpperCase()
		: "IM";

	// Detect platform so we show the right modifier label (⌘ on Mac, Ctrl elsewhere).
	const [isMac, setIsMac] = useState(true);
	useEffect(() => {
		setIsMac(
			typeof navigator !== "undefined" && /Mac|iPhone|iPad/.test(navigator.platform),
		);
	}, []);

	function openSearch() {
		window.dispatchEvent(new Event("imops:open-search"));
	}

	return (
		<header className="h-14 shrink-0 flex items-center gap-3 bg-white dark:bg-[var(--sidebar)] backdrop-blur-sm border-b border-slate-200 dark:border-white/[0.10] shadow-sm px-4 sticky top-0 z-30">
			{/* Mobile hamburger */}
			{onMobileMenuOpen && (
				<button
					type="button"
					onClick={onMobileMenuOpen}
					aria-label={t("openMenu")}
					aria-expanded={false}
					className="md:hidden w-9 h-9 flex items-center justify-center rounded-lg text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-white/10 hover:text-slate-800 dark:hover:text-white transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 shrink-0"
				>
					<Menu size={20} aria-hidden="true" />
				</button>
			)}

			{/* Desktop sidebar toggle */}
			{onToggleSidebar && (
				<button
					type="button"
					onClick={onToggleSidebar}
					aria-label={collapsed ? t("expandSidebar") : t("collapseSidebar")}
					className="hidden md:flex w-8 h-8 items-center justify-center rounded-lg text-slate-500 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-white/10 hover:text-slate-700 dark:hover:text-white transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 shrink-0"
				>
					{collapsed ? (
						<PanelLeftOpen size={18} aria-hidden="true" />
					) : (
						<PanelLeftClose size={18} aria-hidden="true" />
					)}
				</button>
			)}

			{/* Search trigger — opens the ⌘K command palette */}
			<button
				type="button"
				onClick={openSearch}
				aria-label={`${t("searchPlaceholder")} (${isMac ? "⌘" : "Ctrl"}+K)`}
				aria-haspopup="dialog"
				className="flex-1 max-w-xs flex items-center gap-2 pl-3 pr-2 py-2 text-sm text-slate-500 dark:text-slate-300 bg-slate-100 dark:bg-white/[0.06] hover:bg-slate-200/70 dark:hover:bg-white/[0.10] rounded-lg border border-slate-200 dark:border-white/[0.12] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
			>
				<Search size={14} aria-hidden="true" className="shrink-0" />
				<span className="flex-1 text-left truncate">{t("searchPlaceholder")}</span>
				<kbd className="hidden sm:inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded bg-white dark:bg-white/[0.08] border border-slate-200 dark:border-white/[0.12] text-[10px] font-mono text-slate-500 dark:text-slate-300">
					{isMac ? "⌘" : "Ctrl"} K
				</kbd>
			</button>

			<div className="ml-auto flex items-center gap-2">
				<LocaleToggle />
				<ThemeToggle />

				{/* Avatar */}
				<button
					type="button"
					aria-label={`${t("account")}: ${userEmail ?? "User"}`}
					className="w-9 h-9 ml-1 rounded-full bg-gradient-to-br from-brand-500 to-brand-700 text-white text-[11px] font-bold flex items-center justify-center shadow-sm hover:shadow-md hover:scale-105 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
				>
					{initials}
				</button>
			</div>
		</header>
	);
}
