"use client";
import { FileText, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
// Generated by GitHub Copilot
import { useState } from "react";
import { Button, FormError } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import { toRomanMonth } from "@/lib/utils";

/**
 * Generates a draft invoice for a given job and redirects to its detail page.
 * Invoice number format: INV/{YEAR}/{ROMAN_MONTH}/{SEQ}
 * Total amount is pre-filled with the job revenue.
 */
export function GenerateInvoiceButton({
	jobId,
	jobRevenue,
}: {
	jobId: string;
	jobRevenue: number;
}) {
	const router = useRouter();
	const t = useTranslations("actions");
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);

	async function handleClick() {
		setLoading(true);
		setError(null);
		try {
			const supabase = createClient();
			const now = new Date();
			const year = now.getFullYear();
			const month = now.getMonth() + 1;
			const romanMonth = toRomanMonth(month);

			// Count invoices created this month to derive the next sequence number
			const monthStart = `${year}-${String(month).padStart(2, "0")}-01`;
			const nextMonth = month === 12 ? 1 : month + 1;
			const nextYear = month === 12 ? year + 1 : year;
			const monthEnd = `${nextYear}-${String(nextMonth).padStart(2, "0")}-01`;

			const { count } = await supabase
				.from("invoices")
				.select("id", { count: "exact", head: true })
				.gte("created_at", monthStart)
				.lt("created_at", monthEnd);

			const seq = String((count ?? 0) + 1).padStart(3, "0");
			const invoiceNumber = `INV/${year}/${romanMonth}/${seq}`;

			const { data, error: insertErr } = await supabase
				.from("invoices")
				.insert({
					job_id: jobId,
					invoice_number: invoiceNumber,
					total_amount: jobRevenue,
					paid_amount: 0,
					status: "draft",
				})
				.select("id")
				.single();

			if (insertErr) throw insertErr;
			router.push(`/invoices/${data.id}`);
		} catch (err: unknown) {
			setError(err instanceof Error ? err.message : "Failed to create invoice.");
			setLoading(false);
		}
	}

	return (
		<div>
			<Button
				type="button"
				variant="primary"
				size="md"
				onClick={handleClick}
				loading={loading}
				className="w-full"
				aria-label="Generate draft invoice for this job"
			>
				{loading ? (
					<>
						<Loader2 size={14} className="animate-spin" aria-hidden="true" />
						{t("generating")}
					</>
				) : (
					<>
						<FileText size={14} aria-hidden="true" />
						{t("generateInvoice")}
					</>
				)}
			</Button>
			{error && <FormError>{error}</FormError>}
		</div>
	);
}
