"use client";
// Generated by GitHub Copilot
import { Document, Font, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { formatDate, formatRupiah } from "@/lib/utils";

Font.registerHyphenationCallback((word) => [word]);

const BRAND = "#ea580c";
const NAVY = "#141d2e";
const GRAY = "#6b7280";
const LIGHT = "#f1f4f9";

const styles = StyleSheet.create({
	page: {
		fontSize: 10,
		fontFamily: "Helvetica",
		paddingTop: 40,
		paddingBottom: 50,
		paddingHorizontal: 48,
		color: "#1f2937",
	},
	headerRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 20,
	},
	company: { fontSize: 18, fontFamily: "Helvetica-Bold", color: NAVY },
	companyTagline: { fontSize: 8, color: GRAY, marginTop: 2 },
	invoiceTitle: {
		fontSize: 13,
		fontFamily: "Helvetica-Bold",
		color: BRAND,
		textAlign: "right",
	},
	invoiceMeta: { fontSize: 8, color: GRAY, textAlign: "right", marginTop: 2 },
	divider: {
		borderBottomWidth: 1,
		borderBottomColor: "#e5e7eb",
		marginVertical: 12,
	},
	section: { marginBottom: 14 },
	sectionTitle: {
		fontSize: 9,
		fontFamily: "Helvetica-Bold",
		color: GRAY,
		textTransform: "uppercase",
		letterSpacing: 0.8,
		marginBottom: 6,
	},
	row: { flexDirection: "row", marginBottom: 3 },
	label: { flex: 1, color: GRAY },
	value: { flex: 2, fontFamily: "Helvetica-Bold" },
	totalBox: {
		backgroundColor: LIGHT,
		borderRadius: 4,
		padding: 10,
		marginTop: 8,
	},
	totalRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 4,
	},
	totalLabel: { color: GRAY, fontSize: 9 },
	totalValue: { fontFamily: "Helvetica-Bold", fontSize: 9 },
	grandTotalRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginTop: 6,
		paddingTop: 6,
		borderTopWidth: 1,
		borderTopColor: "#d1d5db",
	},
	grandTotalLabel: { fontFamily: "Helvetica-Bold", fontSize: 11 },
	grandTotalValue: { fontFamily: "Helvetica-Bold", fontSize: 13, color: BRAND },
	balanceDueBox: {
		backgroundColor: BRAND,
		borderRadius: 4,
		padding: 8,
		marginTop: 6,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	balanceDueLabel: {
		fontFamily: "Helvetica-Bold",
		color: "#ffffff",
		fontSize: 10,
	},
	balanceDueValue: {
		fontFamily: "Helvetica-Bold",
		color: "#ffffff",
		fontSize: 14,
	},
	notes: { fontSize: 8, color: GRAY, lineHeight: 1.6, marginTop: 4 },
	footer: { position: "absolute", bottom: 24, left: 48, right: 48 },
	footerText: { fontSize: 7, color: "#d1d5db", textAlign: "center" },
	stamp: {
		position: "absolute",
		top: 40,
		right: 48,
		borderWidth: 2,
		borderColor: "#16a34a",
		borderRadius: 4,
		paddingVertical: 3,
		paddingHorizontal: 8,
		opacity: 0.6,
	},
	stampText: {
		fontFamily: "Helvetica-Bold",
		fontSize: 14,
		color: "#16a34a",
		letterSpacing: 1,
	},
});

/** Props required to render an invoice PDF. */
export interface InvoicePDFProps {
	invoice: {
		invoice_number: string;
		total_amount: number;
		paid_amount: number;
		status: string;
		due_date: string | null;
		notes: string | null;
		created_at: string;
	};
	job: {
		job_number: string;
		move_date: string | null;
	};
	customer: {
		name: string;
		phone: string | null;
		email: string | null;
	};
	/** Company identity from system_settings. */
	company: { name: string; tagline: string };
	/** Invoice template content from system_settings. */
	template: { footerNote: string };
}

/**
 * React-PDF document for invoices.
 * Only imported client-side via dynamic import to avoid SSR issues.
 */
export function InvoicePDF({ invoice, job, customer, company, template }: InvoicePDFProps) {
	const balance = invoice.total_amount - (invoice.paid_amount ?? 0);
	const isPaid = invoice.status === "paid";

	return (
		<Document title={invoice.invoice_number} author={company.name} subject="Invoice">
			<Page size="A4" style={styles.page}>
				{/* PAID stamp overlay */}
				{isPaid && (
					<View style={styles.stamp}>
						<Text style={styles.stampText}>PAID</Text>
					</View>
				)}

				{/* Header */}
				<View style={styles.headerRow}>
					<View>
						<Text style={styles.company}>{company.name}</Text>
						<Text style={styles.companyTagline}>{company.tagline}</Text>
					</View>
					<View>
						<Text style={styles.invoiceTitle}>INVOICE</Text>
						<Text style={styles.invoiceMeta}>{invoice.invoice_number}</Text>
						<Text style={styles.invoiceMeta}>Date: {formatDate(invoice.created_at)}</Text>
						{invoice.due_date && (
							<Text style={styles.invoiceMeta}>Due: {formatDate(invoice.due_date)}</Text>
						)}
					</View>
				</View>
				<View style={styles.divider} />

				{/* Bill To */}
				<View style={styles.section}>
					<Text style={styles.sectionTitle}>Bill To</Text>
					<View style={styles.row}>
						<Text style={styles.label}>Customer</Text>
						<Text style={styles.value}>{customer.name}</Text>
					</View>
					{customer.phone && (
						<View style={styles.row}>
							<Text style={styles.label}>Phone</Text>
							<Text style={styles.value}>{customer.phone}</Text>
						</View>
					)}
					{customer.email && (
						<View style={styles.row}>
							<Text style={styles.label}>Email</Text>
							<Text style={styles.value}>{customer.email}</Text>
						</View>
					)}
				</View>

				{/* Job Details */}
				<View style={styles.section}>
					<Text style={styles.sectionTitle}>Job Details</Text>
					<View style={styles.row}>
						<Text style={styles.label}>Job No.</Text>
						<Text style={styles.value}>{job.job_number}</Text>
					</View>
					{job.move_date && (
						<View style={styles.row}>
							<Text style={styles.label}>Move Date</Text>
							<Text style={styles.value}>{formatDate(job.move_date)}</Text>
						</View>
					)}
				</View>

				<View style={styles.divider} />

				{/* Amount Summary */}
				<View style={styles.totalBox}>
					<View style={styles.totalRow}>
						<Text style={styles.totalLabel}>Service Total</Text>
						<Text style={styles.totalValue}>{formatRupiah(invoice.total_amount)}</Text>
					</View>
					{invoice.paid_amount > 0 && (
						<View style={styles.totalRow}>
							<Text style={styles.totalLabel}>Amount Paid</Text>
							<Text style={{ ...styles.totalValue, color: "#16a34a" }}>
								− {formatRupiah(invoice.paid_amount)}
							</Text>
						</View>
					)}
					<View style={styles.grandTotalRow}>
						<Text style={styles.grandTotalLabel}>Total Due</Text>
						<Text style={styles.grandTotalValue}>{formatRupiah(invoice.total_amount)}</Text>
					</View>
				</View>

				{!isPaid && balance > 0 && (
					<View style={styles.balanceDueBox}>
						<Text style={styles.balanceDueLabel}>Balance Due</Text>
						<Text style={styles.balanceDueValue}>{formatRupiah(balance)}</Text>
					</View>
				)}

				{/* Notes */}
				{invoice.notes && (
					<View style={{ ...styles.section, marginTop: 16 }}>
						<Text style={styles.sectionTitle}>Notes</Text>
						<Text style={styles.notes}>{invoice.notes}</Text>
					</View>
				)}

				{/* Footer */}
				<View style={styles.footer}>
					<View style={styles.divider} />
					<Text style={styles.footerText}>
						{company.name} · {template.footerNote}
					</Text>
				</View>
			</Page>
		</Document>
	);
}

/**
 * Build a safe filename for the invoice PDF.
 * e.g. "INV-2026-V-001.pdf"
 */
export function buildInvoiceFilename(invoiceNumber: string): string {
	return `${invoiceNumber.replace(/\//g, "-")}.pdf`;
}
