"use client";
// Generated by GitHub Copilot
import { useState, useEffect } from "react";
import { useTranslations } from "next-intl";
import type { InvoicePDFProps } from "./InvoicePDF";
import { buildInvoiceFilename } from "./InvoicePDF";

/**
 * Renders a PDF download link for an invoice.
 *
 * Both @react-pdf/renderer and InvoicePDF are loaded together after hydration
 * via useEffect + Promise.all, so InvoicePDF is never undefined when passed
 * as the `document` prop to PDFDownloadLink (avoids the "Uncaught undefined" crash).
 */
export function InvoicePDFDownloadButton({
	pdfProps,
}: {
	pdfProps: InvoicePDFProps;
}) {
	const tActions = useTranslations("common.actions");
	const tDetail = useTranslations("pages.invoiceDetail");
	const filename = buildInvoiceFilename(pdfProps.invoice.invoice_number);
	const [DownloadLink, setDownloadLink] = useState<React.ReactNode>(null);

	useEffect(() => {
		Promise.all([import("@react-pdf/renderer"), import("./InvoicePDF")]).then(
			([renderer, pdfModule]) => {
				const { PDFDownloadLink } = renderer;
				const { InvoicePDF } = pdfModule;

				setDownloadLink(
					<PDFDownloadLink
						document={<InvoicePDF {...pdfProps} />}
						fileName={filename}
						className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-medium text-slate-700 hover:bg-slate-50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
						aria-label={`${tDetail("downloadInvoicePdf")} — ${pdfProps.invoice.invoice_number}`}
					>
						{({ loading }: { loading: boolean }) =>
							loading
								? tActions("generatingPdf")
								: `⬇ ${tDetail("downloadInvoicePdf")}`
						}
					</PDFDownloadLink>,
				);
			},
		);
		// pdfProps is serialisable server data — stable on mount
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	if (!DownloadLink) {
		return (
			<span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-medium text-slate-400 cursor-wait">
				{tActions("loadingPdf")}
			</span>
		);
	}

	return <>{DownloadLink}</>;
}
