"use client";
// Generated by GitHub Copilot
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";
import { formatDate, formatRupiah } from "@/lib/utils";
import { NumericInput } from "@/components/shared/NumericInput";

type Payment = {
	id: string;
	payment_type: string;
	method: string | null;
	amount: number;
	paid_at: string;
	notes: string | null;
};

const PAYMENT_TYPES = ["down_payment", "partial", "final", "refund"];
const PAYMENT_METHODS = ["cash", "transfer", "qris"];

/**
 * Displays payment history and a "Record Payment" form.
 *
 * Payments are FK'd to jobs (not invoices) so a down payment can be taken
 * before an invoice is generated. `totalAmount` is the target the panel
 * compares against — usually the invoice total, or the job revenue if no
 * invoice exists yet. `invoiceStatus` may be `null` when there's no invoice.
 */
export function PaymentsPanel({
	jobId,
	totalAmount,
	payments: initial,
	invoiceStatus,
}: {
	jobId: string;
	totalAmount: number;
	payments: Payment[];
	invoiceStatus: string | null;
}) {
	const router = useRouter();
	const tPanel = useTranslations("panels.payments");
	const tForm = useTranslations("forms.payment");
	const tCommonButtons = useTranslations("common.buttons");
	const tCommonErrors = useTranslations("common.errors");
	const tPaymentType = useTranslations("entity.paymentType");
	const tPaymentMethod = useTranslations("entity.paymentMethod");
	const [isPending, startTransition] = useTransition();
	const [payments, setPayments] = useState(initial);
	const [showForm, setShowForm] = useState(false);
	const [form, setForm] = useState({
		payment_type: "down_payment",
		method: "cash",
		amount: "",
		paid_at: todayISO(),
		notes: "",
	});
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	const totalPaid = payments.reduce(
		(s, p) => s + (p.payment_type === "refund" ? -p.amount : p.amount),
		0,
	);
	const outstanding = totalAmount - totalPaid;
	const isFullyPaid = outstanding <= 0;

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		const amt = Number(form.amount);
		if (!amt || amt <= 0) {
			setError(tCommonErrors("amountMustBePositive"));
			return;
		}
		setSaving(true);
		setError(null);

		try {
			const supabase = createClient();
			const { data, error: insertErr } = await supabase
				.from("payments")
				.insert({
					job_id: jobId,
					payment_type: form.payment_type as
						| "down_payment"
						| "partial"
						| "final"
						| "refund",
					method: form.method as "cash" | "transfer" | "qris",
					amount: amt,
					paid_at: form.paid_at,
					notes: form.notes.trim() || null,
				})
				.select("id, payment_type, method, amount, paid_at, notes")
				.single();

			if (insertErr) throw insertErr;

			setPayments((p) => [...p, data as Payment]);
			setShowForm(false);
			setForm({
				payment_type: "down_payment",
				method: "cash",
				amount: "",
				paid_at: todayISO(),
				notes: "",
			});
			startTransition(() => router.refresh());
		} catch (err: unknown) {
			setError(err instanceof Error ? err.message : "Error");
		} finally {
			setSaving(false);
		}
	}

	return (
		<div className="space-y-4">
			{/* Summary */}
			<div className="grid grid-cols-3 gap-3 text-center">
				<div className="rounded-xl bg-gray-50 dark:bg-gray-800 p-3">
					<p className="text-xs text-gray-500 mb-1">{tPanel("total")}</p>
					<p className="tabular-nums font-bold text-sm">
						{formatRupiah(totalAmount)}
					</p>
				</div>
				<div className="rounded-xl bg-green-50 dark:bg-green-900/20 p-3">
					<p className="text-xs text-gray-500 mb-1">{tPanel("paid")}</p>
					<p className="tabular-nums font-bold text-sm text-green-600">
						{formatRupiah(totalPaid)}
					</p>
				</div>
				<div
					className={`rounded-xl p-3 ${outstanding > 0 ? "bg-red-50 dark:bg-red-900/20" : "bg-gray-50 dark:bg-gray-800"}`}
				>
					<p className="text-xs text-gray-500 mb-1">{tPanel("outstanding")}</p>
					<p
						className={`tabular-nums font-bold text-sm ${outstanding > 0 ? "text-red-600" : "text-gray-400"}`}
					>
						{formatRupiah(outstanding > 0 ? outstanding : 0)}
					</p>
				</div>
			</div>

			{/* Record payment button */}
			{!isFullyPaid && invoiceStatus !== "cancelled" && (
				<button
					type="button"
					onClick={() => setShowForm((v) => !v)}
					className="w-full rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
				>
					{showForm ? tCommonButtons("cancel") : tPanel("recordPayment")}
				</button>
			)}

			{/* Payment form */}
			{showForm && (
				<form
					onSubmit={handleSubmit}
					className="rounded-xl border border-gray-200 dark:border-gray-800 p-4 space-y-3"
				>
					{error && (
						<div
							role="alert"
							className="text-sm text-red-600 dark:text-red-400"
						>
							{error}
						</div>
					)}
					<div className="grid grid-cols-2 gap-3">
						<div>
							<label
								htmlFor="pt-type"
								className="block text-xs font-medium mb-1 text-gray-600 dark:text-gray-400"
							>
								{tForm("type")}
							</label>
							<select
								id="pt-type"
								value={form.payment_type}
								onChange={(e) =>
									setForm((p) => ({ ...p, payment_type: e.target.value }))
								}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-2 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							>
								{PAYMENT_TYPES.map((t) => (
									<option key={t} value={t}>
										{tPaymentType(t)}
									</option>
								))}
							</select>
						</div>
						<div>
							<label
								htmlFor="pt-method"
								className="block text-xs font-medium mb-1 text-gray-600 dark:text-gray-400"
							>
								{tForm("method")}
							</label>
							<select
								id="pt-method"
								value={form.method}
								onChange={(e) =>
									setForm((p) => ({ ...p, method: e.target.value }))
								}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-2 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							>
								{PAYMENT_METHODS.map((m) => (
									<option key={m} value={m}>
										{tPaymentMethod(m)}
									</option>
								))}
							</select>
						</div>
					</div>
					<div className="grid grid-cols-2 gap-3">
						<div>
							<label
								htmlFor="pt-amount"
								className="block text-xs font-medium mb-1 text-gray-600 dark:text-gray-400"
							>
								{tForm("amountIdr")}{" "}
								<span aria-hidden="true" className="text-red-500">
									*
								</span>
							</label>
							<NumericInput
								id="pt-amount"
								required
								value={Number(form.amount) || 0}
								onChange={(v) => setForm((p) => ({ ...p, amount: v > 0 ? String(v) : "" }))}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-2 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							/>
						</div>
						<div>
							<label
								htmlFor="pt-date"
								className="block text-xs font-medium mb-1 text-gray-600 dark:text-gray-400"
							>
								{tForm("date")}
							</label>
							<input
								id="pt-date"
								type="date"
								value={form.paid_at}
								onChange={(e) =>
									setForm((p) => ({ ...p, paid_at: e.target.value }))
								}
								className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-2 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
							/>
						</div>
					</div>
					<div>
						<label
							htmlFor="pt-notes"
							className="block text-xs font-medium mb-1 text-gray-600 dark:text-gray-400"
						>
							{tForm("notes")}
						</label>
						<input
							id="pt-notes"
							type="text"
							value={form.notes}
							onChange={(e) =>
								setForm((p) => ({ ...p, notes: e.target.value }))
							}
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-2 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						/>
					</div>
					<button
						type="submit"
						disabled={saving || isPending}
						className="w-full rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-500 transition-colors"
					>
						{saving ? tCommonButtons("saving") : tForm("savePayment")}
					</button>
				</form>
			)}

			{/* Payment history */}
			<div className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 divide-y divide-gray-100 dark:divide-gray-800">
				<p className="px-4 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wide">
					{tPanel("history")}
				</p>
				{payments.length === 0 && (
					<p className="px-4 py-4 text-sm text-center text-gray-400">
						{tPanel("noPayments")}
					</p>
				)}
				{payments.map((p) => (
					<div
						key={p.id}
						className="flex items-center justify-between px-4 py-3 text-sm"
					>
						<div>
							<span className="font-medium">
								{tPaymentType(p.payment_type)}
							</span>
							<span className="text-xs text-gray-400 ml-2">
								{tPanel("via", {
									method: p.method ? tPaymentMethod(p.method) : "—",
								})}
							</span>
							{p.notes && (
								<span className="block text-xs text-gray-400">{p.notes}</span>
							)}
							<span className="block text-xs text-gray-400">
								{formatDate(p.paid_at)}
							</span>
						</div>
						<span
							className={`tabular-nums font-medium ${p.payment_type === "refund" ? "text-red-600" : "text-green-600"}`}
						>
							{p.payment_type === "refund" ? "−" : "+"}
							{formatRupiah(p.amount)}
						</span>
					</div>
				))}
			</div>
		</div>
	);
}

function todayISO() {
	return new Date().toISOString().slice(0, 10);
}
