"use client";
// Generated by GitHub Copilot
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";

type Vendor = { id: string; name: string };
type Crew = { id: string; name: string; daily_rate: number | null };
type Assignment = {
	id: string;
	assignment_type: string;
	role: string | null;
	vendors: { name: string } | null;
	crew: { name: string } | null;
};

/**
 * Assignments manager — records WHO is working on a job (vendor or crew).
 * Costs are tracked separately via the Expense panel (Log Expense button).
 * Calls check_resource_overlap RPC before adding to warn on double-booking.
 */
export function AssignmentsPanel({
	jobId,
	moveDate,
	assignments: initialAssignments,
	vendors,
	crewList,
}: {
	jobId: string;
	moveDate: string | null;
	assignments: Assignment[];
	vendors: Vendor[];
	crewList: Crew[];
}) {
	const router = useRouter();
	const t = useTranslations("panels.assignments");
	const tCommonButtons = useTranslations("common.buttons");
	const tCommonHints = useTranslations("common.hints");
	const [isPending, startTransition] = useTransition();
	const [assignments, setAssignments] = useState(initialAssignments);
	const [showModal, setShowModal] = useState(false);
	const [overlap, setOverlap] = useState<string | null>(null);
	const [error, setError] = useState<string | null>(null);

	const [form, setForm] = useState({
		type: "vendor" as "vendor" | "crew",
		resourceId: "",
		role: "",
	});

	async function handleAdd(e: React.FormEvent) {
		e.preventDefault();
		if (!form.resourceId) return;
		setOverlap(null);
		setError(null);

		const supabase = createClient();

		// Check overlap if we have a move date
		if (moveDate) {
			const { data: conflicts } = await supabase.rpc("check_resource_overlap", {
				p_type: form.type,
				p_id: form.resourceId,
				p_date: moveDate,
			});
			if (conflicts && (conflicts as unknown[]).length > 0) {
				setOverlap(
					t("overlapWarning", {
						type:
							form.type === "vendor" ? t("vendorLabel") : t("crewLabel"),
						date: moveDate,
					}),
				);
				return;
			}
		}

		await commitAdd();
	}

	async function commitAdd() {
		const supabase = createClient();
		const { data, error: err } = await supabase
			.from("job_assignments")
			.insert({
				job_id: jobId,
				assignment_type: form.type,
				vendor_id: form.type === "vendor" ? form.resourceId : null,
				crew_id: form.type === "crew" ? form.resourceId : null,
				role: form.role.trim() || null,
			})
			.select("id, assignment_type, role, vendors(name), crew(name)")
			.single();

		if (err) {
			setError(err.message);
			return;
		}
		setAssignments((p) => [...p, data as Assignment]);
		setOverlap(null);
		setShowModal(false);
		setForm({ type: "vendor", resourceId: "", role: "" });
		startTransition(() => router.refresh());
	}

	async function handleRemove(assignmentId: string) {
		const supabase = createClient();
		await supabase.from("job_assignments").delete().eq("id", assignmentId);
		setAssignments((p) => p.filter((a) => a.id !== assignmentId));
		startTransition(() => router.refresh());
	}

	const options = form.type === "vendor" ? vendors : crewList;

	return (
		<div className="space-y-4">
			<div className="flex items-center justify-between">
				<h2 className="text-base font-semibold text-gray-900 dark:text-white">
					{t("title")}
				</h2>
				<button
					type="button"
					onClick={() => setShowModal(true)}
					className="rounded-lg bg-brand-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
				>
					+ {t("add")}
				</button>
			</div>

			{error && (
				<div role="alert" className="text-sm text-red-600 dark:text-red-400">
					{error}
				</div>
			)}

			<div className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 divide-y divide-gray-100 dark:divide-gray-800">
				{assignments.length === 0 && (
					<p className="px-4 py-6 text-sm text-center text-gray-400">
						{t("empty")}
					</p>
				)}
				{assignments.map((a) => {
					const name =
						a.assignment_type === "vendor" ? a.vendors?.name : a.crew?.name;
					return (
						<div
							key={a.id}
							className="flex items-center justify-between px-4 py-3 text-sm"
						>
							<div>
								<span className="font-medium text-gray-900 dark:text-white">
									{name ?? "—"}
								</span>
								{a.role && (
									<span className="text-gray-400 text-xs ml-2">({a.role})</span>
								)}
								<span className="ml-2 text-xs text-brand-600 dark:text-brand-400">
									{a.assignment_type === "vendor"
										? t("vendorLabel")
										: t("crewLabel")}
								</span>
							</div>
							<button
								type="button"
								onClick={() => handleRemove(a.id)}
								aria-label={t("removeAria", { name: name ?? "" })}
								className="text-red-500 hover:text-red-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 rounded text-xs"
							>
								{t("remove")}
							</button>
						</div>
					);
				})}
			</div>

			{/* Add modal */}
			{showModal && (
				<div
					role="dialog"
					aria-modal="true"
					aria-labelledby="assign-title"
					className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4"
				>
					<div className="w-full max-w-sm rounded-xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-6 shadow-xl space-y-4">
						<h3
							id="assign-title"
							className="text-base font-semibold text-gray-900 dark:text-white"
						>
							{t("addAssignment")}
						</h3>

						{overlap && (
							<div
								role="alert"
								className="rounded bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-300 px-3 py-2 text-sm text-yellow-800 dark:text-yellow-300"
							>
								{overlap}
								<div className="mt-2 flex gap-2">
									<button
										type="button"
										onClick={commitAdd}
										className="rounded bg-yellow-600 px-3 py-1 text-xs font-medium text-white hover:bg-yellow-700"
									>
										{tCommonButtons("addAnyway")}
									</button>
									<button
										type="button"
										onClick={() => setOverlap(null)}
										className="rounded border border-yellow-400 px-3 py-1 text-xs font-medium text-yellow-700"
									>
										{tCommonButtons("cancel")}
									</button>
								</div>
							</div>
						)}

						{!overlap && (
							<form onSubmit={handleAdd} className="space-y-4">
								{/* Vendor / Crew toggle */}
								<div>
									<label className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">
										{t("type")}
									</label>
									<div className="flex gap-4">
										{(["vendor", "crew"] as const).map((opt) => (
											<label
												key={opt}
												className="flex items-center gap-1.5 cursor-pointer"
											>
												<input
													type="radio"
													name="assign-type"
													value={opt}
													checked={form.type === opt}
													onChange={() =>
														setForm((p) => ({ ...p, type: opt, resourceId: "" }))
													}
													className="text-brand-600 focus:ring-brand-500"
												/>
												<span className="text-sm">
													{opt === "vendor"
														? t("vendorLabel")
														: t("crewLabel")}
												</span>
											</label>
										))}
									</div>
								</div>

								{/* Resource selector */}
								<div>
									<label
										htmlFor="assign-res"
										className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
									>
										{form.type === "vendor" ? t("vendor") : t("crewMember")}{" "}
										<span aria-hidden="true" className="text-red-500">
											*
										</span>
									</label>
									<select
										id="assign-res"
										required
										value={form.resourceId}
										onChange={(e) =>
											setForm((p) => ({ ...p, resourceId: e.target.value }))
										}
										className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
									>
										<option value="">{tCommonHints("select")}</option>
										{options.map((o) => (
											<option key={o.id} value={o.id}>
												{o.name}
											</option>
										))}
									</select>
								</div>

								{/* Role */}
								<div>
									<label
										htmlFor="assign-role"
										className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
									>
										{t("role")}
									</label>
									<input
										id="assign-role"
										type="text"
										value={form.role}
										onChange={(e) =>
											setForm((p) => ({ ...p, role: e.target.value }))
										}
										placeholder={t("rolePlaceholder")}
										className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
									/>
								</div>

								<div className="flex gap-2">
									<button
										type="submit"
										disabled={isPending}
										className="flex-1 rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
									>
										{tCommonButtons("add")}
									</button>
									<button
										type="button"
										onClick={() => setShowModal(false)}
										className="flex-1 rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
									>
										{tCommonButtons("cancel")}
									</button>
								</div>
							</form>
						)}
					</div>
				</div>
			)}
		</div>
	);
}
