"use client";
// Generated by GitHub Copilot
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";
import { Button, Card, Field, Input, Select, EmptyState } from "@/components/ui";

type FleetMember = { id: string; name: string };
type Crew = { id: string; name: string; daily_rate: number | null };
type Assignment = {
	id: string;
	assignment_type: string;
	role: string | null;
	fleet: { name: string } | null;
	crew: { name: string } | null;
};

/**
 * Assignments manager — records WHO is working on a job (fleet or crew).
 * Costs are tracked separately via the Expense panel (Log Expense button).
 * Calls check_resource_overlap RPC before adding to warn on double-booking.
 */
export function AssignmentsPanel({
	jobId,
	moveDate,
	assignments: initialAssignments,
	fleetList,
	crewList,
}: {
	jobId: string;
	moveDate: string | null;
	assignments: Assignment[];
	fleetList: FleetMember[];
	crewList: Crew[];
}) {
	const router = useRouter();
	const t = useTranslations("panels.assignments");
	const tCommonButtons = useTranslations("common.buttons");
	const tCommonHints = useTranslations("common.hints");
	const [isPending, startTransition] = useTransition();
	const [assignments, setAssignments] = useState(initialAssignments);
	const [showModal, setShowModal] = useState(false);
	const [overlap, setOverlap] = useState<string | null>(null);
	const [error, setError] = useState<string | null>(null);

	const [form, setForm] = useState({
		type: "fleet" as "fleet" | "crew",
		resourceId: "",
		role: "",
	});

	async function handleAdd(e: React.FormEvent) {
		e.preventDefault();
		if (!form.resourceId) return;
		setOverlap(null);
		setError(null);

		const supabase = createClient();

		// Check overlap if we have a move date
		if (moveDate) {
			const { data: conflicts } = await supabase.rpc("check_resource_overlap", {
				p_type: form.type,
				p_id: form.resourceId,
				p_date: moveDate,
			});
			if (conflicts && (conflicts as unknown[]).length > 0) {
				setOverlap(
					t("overlapWarning", {
						type:
							form.type === "fleet" ? t("fleetLabel") : t("crewLabel"),
						date: moveDate,
					}),
				);
				return;
			}
		}

		await commitAdd();
	}

	async function commitAdd() {
		const supabase = createClient();
		const { data, error: err } = await supabase
			.from("job_assignments")
			.insert({
				job_id: jobId,
				assignment_type: form.type,
				fleet_id: form.type === "fleet" ? form.resourceId : null,
				crew_id: form.type === "crew" ? form.resourceId : null,
				role: form.role.trim() || null,
			})
			.select("id, assignment_type, role, fleet(name), crew(name)")
			.single();

		if (err) {
			setError(err.message);
			return;
		}
		setAssignments((p) => [...p, data as Assignment]);
		setOverlap(null);
		setShowModal(false);
		setForm({ type: "fleet", resourceId: "", role: "" });
		startTransition(() => router.refresh());
	}

	async function handleRemove(assignmentId: string) {
		const supabase = createClient();
		await supabase.from("job_assignments").delete().eq("id", assignmentId);
		setAssignments((p) => p.filter((a) => a.id !== assignmentId));
		startTransition(() => router.refresh());
	}

	const options = form.type === "fleet" ? fleetList : crewList;

	return (
		<div className="space-y-4">
			<div className="flex items-center justify-between">
				<h2 className="text-base font-semibold text-ink">
					{t("title")}
				</h2>
				<Button
					type="button"
					variant="primary"
					size="sm"
					onClick={() => setShowModal(true)}
				>
					+ {t("add")}
				</Button>
			</div>

			{error && (
				<p role="alert" className="text-sm text-danger">
					{error}
				</p>
			)}

			<Card className="divide-y divide-line">
				{assignments.length === 0 && (
					<EmptyState title={t("empty")} />
				)}
				{assignments.map((a) => {
					const name =
						a.assignment_type === "fleet" ? a.fleet?.name : a.crew?.name;
					return (
						<div
							key={a.id}
							className="flex items-center justify-between px-4 py-3 text-sm"
						>
							<div>
								<span className="font-medium text-ink">
									{name ?? "—"}
								</span>
								{a.role && (
									<span className="text-ink-faint text-xs ml-2">({a.role})</span>
								)}
								<span className="ml-2 text-xs text-primary-text">
									{a.assignment_type === "fleet"
										? t("fleetLabel")
										: t("crewLabel")}
								</span>
							</div>
							<button
								type="button"
								onClick={() => handleRemove(a.id)}
								aria-label={t("removeAria", { name: name ?? "" })}
								className="text-danger hover:opacity-80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] rounded text-xs"
							>
								{t("remove")}
							</button>
						</div>
					);
				})}
			</Card>

			{/* Add modal */}
			{showModal && (
				<div
					role="dialog"
					aria-modal="true"
					aria-labelledby="assign-title"
					className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4"
				>
					<div className="w-full max-w-sm bg-surface border border-line rounded-xl p-6 shadow-token-md space-y-4">
						<h3
							id="assign-title"
							className="text-base font-semibold text-ink"
						>
							{t("addAssignment")}
						</h3>

						{overlap && (
							<div
								role="alert"
								className="rounded bg-warning-bg border border-warning px-3 py-2 text-sm text-warning-text"
							>
								{overlap}
								<div className="mt-2 flex gap-2">
									<Button
										type="button"
										variant="subtle"
										size="sm"
										onClick={commitAdd}
									>
										{tCommonButtons("addAnyway")}
									</Button>
									<Button
										type="button"
										variant="ghost"
										size="sm"
										onClick={() => setOverlap(null)}
									>
										{tCommonButtons("cancel")}
									</Button>
								</div>
							</div>
						)}

						{!overlap && (
							<form onSubmit={handleAdd} className="space-y-4">
								{/* Fleet / Crew toggle */}
								<div>
									<label className="block text-sm font-medium mb-1 text-ink">
										{t("type")}
									</label>
									<div className="flex gap-4">
										{(["fleet", "crew"] as const).map((opt) => (
											<label
												key={opt}
												className="flex items-center gap-1.5 cursor-pointer"
											>
												<input
													type="radio"
													name="assign-type"
													value={opt}
													checked={form.type === opt}
													onChange={() =>
														setForm((p) => ({ ...p, type: opt, resourceId: "" }))
													}
													className="text-primary focus:ring-[var(--ring)]"
												/>
												<span className="text-sm text-ink">
													{opt === "fleet"
														? t("fleetLabel")
														: t("crewLabel")}
												</span>
											</label>
										))}
									</div>
								</div>

								{/* Resource selector */}
								<Field
									label={
										<>
											{form.type === "fleet" ? t("fleet") : t("crewMember")}{" "}
											<span aria-hidden="true" className="text-danger">
												*
											</span>
										</>
									}
									htmlFor="assign-res"
								>
									<Select
										id="assign-res"
										required
										value={form.resourceId}
										onChange={(e) =>
											setForm((p) => ({ ...p, resourceId: e.target.value }))
										}
									>
										<option value="">{tCommonHints("select")}</option>
										{options.map((o) => (
											<option key={o.id} value={o.id}>
												{o.name}
											</option>
										))}
									</Select>
								</Field>

								{/* Role */}
								<Field label={t("role")} htmlFor="assign-role">
									<Input
										id="assign-role"
										type="text"
										value={form.role}
										onChange={(e) =>
											setForm((p) => ({ ...p, role: e.target.value }))
										}
										placeholder={t("rolePlaceholder")}
									/>
								</Field>

								<div className="flex gap-2">
									<Button
										type="submit"
										loading={isPending}
										variant="primary"
										size="md"
										className="flex-1"
									>
										{tCommonButtons("add")}
									</Button>
									<Button
										type="button"
										variant="secondary"
										size="md"
										className="flex-1"
										onClick={() => setShowModal(false)}
									>
										{tCommonButtons("cancel")}
									</Button>
								</div>
							</form>
						)}
					</div>
				</div>
			)}
		</div>
	);
}
