"use client";
// Generated by GitHub Copilot
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";
import { formatRupiah, resizeImage } from "@/lib/utils";
import { NumericInput } from "@/components/shared/NumericInput";
import {
	enqueueExpense,
	flushQueue,
	isOfflineError,
	queuedCount,
	subscribe,
} from "@/lib/offline/expenseQueue";
import { Button, Badge, Card, CardHeader, Field, Input, FormError } from "@/components/ui";

type Expense = {
	id: string;
	category: string;
	description: string | null;
	amount: number;
	incurred_at: string;
	receipt_url: string | null;
};

const CATEGORIES: { value: string; key: string }[] = [
	{ value: "Fuel", key: "fuel" },
	{ value: "Toll", key: "toll" },
	{ value: "Food", key: "food" },
	{ value: "Labor", key: "labor" },
	{ value: "Packing materials", key: "packing_materials" },
	{ value: "Transport", key: "transport" },
	{ value: "Parking", key: "parking" },
	{ value: "Other", key: "other" },
];

const CATEGORY_KEY_BY_VALUE: Record<string, string> = CATEGORIES.reduce(
	(acc, c) => {
		acc[c.value] = c.key;
		return acc;
	},
	{} as Record<string, string>,
);

/**
 * Mobile-optimized expense entry panel.
 * Design target: < 5 seconds for a standard entry.
 */
export function ExpensePanel({
	jobId,
	expenses: initial,
}: {
	jobId: string;
	expenses: Expense[];
}) {
	const router = useRouter();
	const tExpense = useTranslations("forms.expense");
	const tCommonButtons = useTranslations("common.buttons");
	const tCommonHints = useTranslations("common.hints");
	const tCommonErrors = useTranslations("common.errors");
	const tEntityCategory = useTranslations("entity.expenseCategory");
	const tOffline = useTranslations("offline");
	const tJobDetail = useTranslations("pages.jobDetail");
	const [isPending, startTransition] = useTransition();
	const [expenses, setExpenses] = useState(initial);
	const [form, setForm] = useState({
		amount: "",
		category: "Fuel",
		note: "",
		date: todayISO(),
	});
	const [saving, setSaving] = useState(false);
	const [receiptFile, setReceiptFile] = useState<File | null>(null);
	const [error, setError] = useState<string | null>(null);
	const [showMore, setShowMore] = useState(false);
	const [pendingCount, setPendingCount] = useState(0);
	const [info, setInfo] = useState<string | null>(null);

	// Keep the pending badge in sync with the queue + auto-flush when back online.
	useEffect(() => {
		setPendingCount(queuedCount());
		const unsub = subscribe(() => setPendingCount(queuedCount()));
		const onOnline = async () => {
			const supabase = createClient();
			const result = await flushQueue(supabase);
			if (result.succeeded > 0) {
				setInfo(tOffline("syncedCount", { count: result.succeeded }));
				startTransition(() => router.refresh());
			}
		};
		window.addEventListener("online", onOnline);
		// Try one flush on mount in case we came back online before this view did.
		if (navigator.onLine) void onOnline();
		return () => {
			unsub();
			window.removeEventListener("online", onOnline);
		};
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	function resetForm() {
		setForm({ amount: "", category: "Fuel", note: "", date: todayISO() });
		setReceiptFile(null);
	}

	function queueLocally(amt: number) {
		const entry = enqueueExpense({
			job_id: jobId,
			category: form.category,
			description: form.note.trim() || null,
			amount: amt,
			incurred_at: form.date,
		});
		// Render the queued expense in the list with a synthetic id so the
		// operator gets immediate feedback. It'll be replaced on next refresh
		// after a successful flush.
		setExpenses((p) => [
			{
				id: `pending:${entry.id}`,
				category: form.category,
				description: form.note.trim() || null,
				amount: amt,
				incurred_at: form.date,
				receipt_url: null,
			},
			...p,
		]);
		setInfo(tOffline("savedOffline"));
	}

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		const amt = Number(form.amount);
		if (!amt || amt <= 0) {
			setError(tCommonErrors("amountMustBePositive"));
			return;
		}
		setSaving(true);
		setError(null);
		setInfo(null);

		// If we're already offline, queue immediately and skip the network try.
		// Receipt photos can't be queued — surface that so the operator can retry.
		if (typeof navigator !== "undefined" && navigator.onLine === false) {
			if (receiptFile) {
				setError(tOffline("removeReceiptToSave"));
				setSaving(false);
				return;
			}
			queueLocally(amt);
			resetForm();
			setSaving(false);
			return;
		}

		try {
			const supabase = createClient();
			let receipt_url: string | null = null;

			if (receiptFile) {
				const resized = await resizeImage(receiptFile);
				const path = `${jobId}/${Date.now()}.webp`;
				const { error: uploadErr } = await supabase.storage
					.from("receipts")
					.upload(path, resized);
				if (!uploadErr) {
					const { data: urlData } = supabase.storage
						.from("receipts")
						.getPublicUrl(path);
					receipt_url = urlData.publicUrl;
				}
			}

			const { data, error: insertErr } = await supabase
				.from("expenses")
				.insert({
					job_id: jobId,
					category: form.category,
					description: form.note.trim() || null,
					amount: amt,
					incurred_at: form.date,
					receipt_url,
				})
				.select("id, category, description, amount, incurred_at, receipt_url")
				.single();

			if (insertErr) throw insertErr;

			setExpenses((p) => [data as Expense, ...p]);
			resetForm();
			startTransition(() => router.refresh());
		} catch (err: unknown) {
			if (isOfflineError(err) && !receiptFile) {
				queueLocally(amt);
				resetForm();
			} else {
				setError(err instanceof Error ? err.message : "Error");
			}
		} finally {
			setSaving(false);
		}
	}

	const total = expenses.reduce((s, e) => s + e.amount, 0);

	return (
		<div className="space-y-6">
			{/* Entry form — large touch targets for mobile */}
			<form onSubmit={handleSubmit}>
			<Card className="p-5 space-y-4">
				<div className="flex items-center justify-between gap-3">
					<h2 className="text-base font-semibold text-ink">
						{tExpense("title")}
					</h2>
					{pendingCount > 0 && (
						<Badge tone="pending" dot>
							{tOffline("pendingSync", { count: pendingCount })}
						</Badge>
					)}
				</div>

				{info && (
					<div
						role="status"
						className="rounded bg-warning-bg border border-warning px-3 py-2 text-sm text-warning-text"
					>
						{info}
					</div>
				)}

				{error && <FormError>{error}</FormError>}

				{/* Amount — large input for thumb-friendly entry */}
				<div>
					<label
						htmlFor="exp-amount"
						className="block text-sm font-medium mb-1 text-ink"
					>
						{tExpense("amountIdr")}{" "}
						<span aria-hidden="true" className="text-danger">
							*
						</span>
					</label>
					<NumericInput
						id="exp-amount"
						required
						autoFocus
						value={Number(form.amount) || 0}
						onChange={(v) => setForm((p) => ({ ...p, amount: v > 0 ? String(v) : "" }))}
						className="w-full rounded-lg border border-line-strong bg-surface px-4 py-4 text-2xl tabular-nums font-bold focus:outline-none focus:ring-2 focus:ring-[var(--ring)] text-right text-ink"
					/>
					{form.amount && Number(form.amount) > 0 && (
						<p className="text-xs text-ink-faint mt-1 text-right">
							{formatRupiah(Number(form.amount))}
						</p>
					)}
				</div>

				{/* Category chips */}
				<div>
					<span className="block text-sm font-medium mb-2 text-ink">
						{tExpense("category")}
					</span>
					<div
						role="group"
						aria-label={tExpense("category")}
						className="flex flex-wrap gap-2"
					>
						{CATEGORIES.map((c) => (
							<button
								key={c.value}
								type="button"
								onClick={() => setForm((p) => ({ ...p, category: c.value }))}
								aria-pressed={form.category === c.value}
								className={`rounded-full min-h-[44px] px-4 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] ${
									form.category === c.value
										? "bg-primary text-primary-fg"
										: "bg-subtle text-ink-muted hover:bg-subtle hover:text-ink"
								}`}
							>
								{tEntityCategory(c.key)}
							</button>
						))}
					</div>
				</div>

				<Button
					type="submit"
					disabled={saving || isPending}
					loading={saving}
					variant="primary"
					size="lg"
					className="w-full"
				>
					{saving ? tCommonButtons("saving") : tExpense("saveExpense")}
				</Button>

				{/* Secondary fields — toggle to keep critical path short */}
				<div>
					<button
						type="button"
						onClick={() => setShowMore((p) => !p)}
						aria-expanded={showMore}
						className="text-sm text-primary-text hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] rounded"
					>
						{showMore ? `▲ ${tExpense("hideOptions")}` : `▼ ${tExpense("moreOptions")}`}
					</button>
					{showMore && (
						<div className="mt-3 space-y-3">
							<Field label={tExpense("note")} htmlFor="exp-note">
								<Input
									id="exp-note"
									type="text"
									value={form.note}
									onChange={(e) =>
										setForm((p) => ({ ...p, note: e.target.value }))
									}
									placeholder="e.g. Jakarta–Bandung toll"
								/>
							</Field>
							<Field label={tExpense("date")} htmlFor="exp-date">
								<Input
									id="exp-date"
									type="date"
									value={form.date}
									onChange={(e) =>
										setForm((p) => ({ ...p, date: e.target.value }))
									}
								/>
							</Field>
							<div>
								<label
									htmlFor="exp-receipt"
									className="block text-sm font-medium mb-1 text-ink"
								>
									{tExpense("receipt")}{" "}
									<span className="text-ink-faint font-normal">{tCommonHints("optionalParen")}</span>
								</label>
								<input
									id="exp-receipt"
									type="file"
									accept="image/*"
									capture="environment"
									onChange={(e) => setReceiptFile(e.target.files?.[0] ?? null)}
									className="block text-sm text-ink-muted file:mr-3 file:rounded-lg file:border-0 file:bg-primary-subtle file:px-3 file:py-1.5 file:text-sm file:font-medium file:text-primary-text hover:file:opacity-80"
								/>
								{receiptFile && (
									<p className="text-xs text-ink-faint mt-1">
										{receiptFile.name}
									</p>
								)}
							</div>
						</div>
					)}
				</div>
			</Card>
			</form>

			{/* List */}
			<Card>
				<CardHeader
					title={tJobDetail("expenses")}
					action={
						<span className="tabular-nums text-sm font-bold text-ink">
							{formatRupiah(total)}
						</span>
					}
				/>
				{expenses.length === 0 && (
					<p className="px-4 py-6 text-center text-sm text-ink-faint">
						{tJobDetail("noExpenses")}
					</p>
				)}
				{expenses.map((e) => {
					const isPendingItem = e.id.startsWith("pending:");
					return (
						<div
							key={e.id}
							className={`flex items-center justify-between px-4 py-3 border-b border-line last:border-0 text-sm ${isPendingItem ? "bg-warning-bg" : ""}`}
						>
							<div>
								<span className="font-medium text-ink">
									{CATEGORY_KEY_BY_VALUE[e.category]
										? tEntityCategory(CATEGORY_KEY_BY_VALUE[e.category])
										: e.category}
								</span>
								{e.description && (
									<span className="text-ink-faint text-xs ml-2">
										{e.description}
									</span>
								)}
								<span className="block text-xs text-ink-faint">
									{e.incurred_at}
									{isPendingItem && (
										<span className="ml-1 text-warning-text">· {tOffline("pending")}</span>
									)}
								</span>
							</div>
							<span className="tabular-nums font-medium text-ink">
								{formatRupiah(e.amount)}
							</span>
						</div>
					);
				})}
			</Card>
		</div>
	);
}

function todayISO() {
	return new Date().toISOString().slice(0, 10);
}
