"use client";
// Generated by GitHub Copilot
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";

/**
 * Create / edit customer form.
 * @param customer - if provided, renders in edit mode with pre-filled values.
 */
export function CustomerForm({
	customer,
}: {
	customer?: {
		id: string;
		name: string;
		phone: string | null;
		email: string | null;
		type: "individual" | "corporate";
		company_name: string | null;
		notes: string | null;
	};
}) {
	const router = useRouter();
	const t = useTranslations("forms.customer");
	const tButtons = useTranslations("common.buttons");
	const tActions = useTranslations("actions");
	const tCustomerType = useTranslations("entity.customerType");
	const isEdit = Boolean(customer);

	const [form, setForm] = useState({
		name: customer?.name ?? "",
		phone: customer?.phone ?? "",
		email: customer?.email ?? "",
		type: customer?.type ?? "individual",
		company_name: customer?.company_name ?? "",
		notes: customer?.notes ?? "",
	});
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	function handleChange(
		e: React.ChangeEvent<
			HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
		>,
	) {
		setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
	}

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setError(null);
		setSaving(true);

		try {
			const supabase = createClient();
			const payload = {
				name: form.name.trim(),
				phone: form.phone.trim() || null,
				email: form.email.trim() || null,
				type: form.type as "individual" | "corporate",
				company_name: form.company_name.trim() || null,
				notes: form.notes.trim() || null,
			};

			if (isEdit && customer) {
				const { error: err } = await supabase
					.from("customers")
					.update(payload)
					.eq("id", customer.id);
				if (err) throw err;
				router.push(`/customers/${customer.id}`);
			} else {
				const { data, error: err } = await supabase
					.from("customers")
					.insert(payload)
					.select("id")
					.single();
				if (err) throw err;
				router.push(`/customers/${data.id}`);
			}
		} catch (err: unknown) {
			setError(
				err instanceof Error
					? err.message
					: "An error occurred. Please try again.",
			);
		} finally {
			setSaving(false);
		}
	}

	return (
		<form onSubmit={handleSubmit} className="space-y-5 max-w-lg" noValidate>
			{error && (
				<div
					role="alert"
					className="rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 px-4 py-3 text-sm text-red-700 dark:text-red-300"
				>
					{error}
				</div>
			)}

			<div>
				<label
					htmlFor="name"
					className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
				>
					{t("fullName")}{" "}
					<span aria-hidden="true" className="text-red-500">
						*
					</span>
				</label>
				<input
					id="name"
					name="name"
					type="text"
					required
					value={form.name}
					onChange={handleChange}
					autoComplete="name"
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<div>
				<label
					htmlFor="type"
					className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
				>
					{t("type")}
				</label>
				<select
					id="type"
					name="type"
					value={form.type}
					onChange={handleChange}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				>
					<option value="individual">{tCustomerType("individual")}</option>
					<option value="corporate">{tCustomerType("corporate")}</option>
				</select>
			</div>

			{form.type === "corporate" && (
				<div>
					<label
						htmlFor="company_name"
						className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
					>
						{t("companyName")}
					</label>
					<input
						id="company_name"
						name="company_name"
						type="text"
						value={form.company_name}
						onChange={handleChange}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>
			)}

			<div>
				<label
					htmlFor="phone"
					className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
				>
					{t("phone")}
				</label>
				<input
					id="phone"
					name="phone"
					type="tel"
					value={form.phone}
					onChange={handleChange}
					autoComplete="tel"
					placeholder={t("phonePlaceholder")}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<div>
				<label
					htmlFor="email"
					className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
				>
					{t("email")}
				</label>
				<input
					id="email"
					name="email"
					type="email"
					value={form.email}
					onChange={handleChange}
					autoComplete="email"
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<div>
				<label
					htmlFor="notes"
					className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
				>
					{t("notes")}
				</label>
				<textarea
					id="notes"
					name="notes"
					rows={3}
					value={form.notes}
					onChange={handleChange}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none"
				/>
			</div>

			<div className="flex gap-3">
				<button
					type="submit"
					disabled={saving}
					className="rounded-lg bg-brand-600 px-5 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
				>
					{saving
						? tButtons("saving")
						: isEdit
							? tButtons("saveChanges")
							: tActions("createCustomer")}
				</button>
				<button
					type="button"
					onClick={() => router.back()}
					className="rounded-lg border border-gray-300 dark:border-gray-700 px-5 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
				>
					{tButtons("cancel")}
				</button>
			</div>
		</form>
	);
}
