// Generated by GitHub Copilot
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

/**
 * Root page — redirect authenticated users to /dashboard, others to /login.
 */
export default async function RootPage() {
	const supabase = await createClient();
	const {
		data: { user },
	} = await supabase.auth.getUser();
	redirect(user ? "/dashboard" : "/login");
}
