"use client";
// Generated by GitHub Copilot
import { useState, useRef } from "react";
import Image from "next/image";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";
import { resizeImage } from "@/lib/utils";
import { Upload, X, ZoomIn } from "lucide-react";
import {
	PhotoLightbox,
	type LightboxPhoto,
} from "@/components/shared/PhotoLightbox";

type Photo = {
	id: string;
	storage_path: string;
	caption: string | null;
	uploaded_at: string;
};

/**
 * Lead photo gallery with upload support.
 * Images are resized client-side to max 1600px WebP before upload.
 *
 * @security - Only authenticated users can upload (enforced by Supabase RLS + Storage policies)
 * - Client-side resize limits uploaded file sizes (green software principle)
 */
export function LeadPhotoGallery({
	leadId,
	photos: initialPhotos,
}: {
	leadId: string;
	photos: Photo[];
}) {
	const t = useTranslations("panels.photos");
	const tActions = useTranslations("actions");
	const tErrors = useTranslations("common.errors");
	const [photos, setPhotos] = useState<Photo[]>(initialPhotos);
	const [uploading, setUploading] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [lightboxIndex, setLightboxIndex] = useState<number | null>(null);
	const fileInputRef = useRef<HTMLInputElement>(null);

	async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
		const files = Array.from(e.target.files ?? []);
		if (files.length === 0) return;
		setError(null);
		setUploading(true);

		try {
			const supabase = createClient();

			for (const file of files) {
				// Validate file type
				if (!file.type.startsWith("image/")) {
					setError(tErrors("notAnImage", { name: file.name }));
					continue;
				}

				// Resize + convert to WebP
				const blob = await resizeImage(file);
				const fileName = `${crypto.randomUUID()}.webp`;
				const storagePath = `${leadId}/${fileName}`;

				const { error: uploadErr } = await supabase.storage
					.from("lead-photos")
					.upload(storagePath, blob, { contentType: "image/webp" });

				if (uploadErr) throw uploadErr;

				const { data: record, error: dbErr } = await supabase
					.from("lead_photos")
					.insert({ lead_id: leadId, storage_path: storagePath })
					.select("id, storage_path, caption, uploaded_at")
					.single();

				if (dbErr) throw dbErr;

				// Optimistic UI update
				setPhotos((prev) => [...prev, record]);
			}
		} catch (err: unknown) {
			setError(err instanceof Error ? err.message : tErrors("uploadFailed"));
		} finally {
			setUploading(false);
			// Reset input so the same file can be re-selected
			if (fileInputRef.current) fileInputRef.current.value = "";
		}
	}

	async function handleDelete(photo: Photo) {
		const supabase = createClient();
		await supabase.storage.from("lead-photos").remove([photo.storage_path]);
		await supabase.from("lead_photos").delete().eq("id", photo.id);
		setPhotos((prev) => prev.filter((p) => p.id !== photo.id));
	}

	function getPublicUrl(storagePath: string): string {
		const supabase = createClient();
		const { data } = supabase.storage
			.from("lead-photos")
			.getPublicUrl(storagePath);
		return data.publicUrl;
	}

	return (
		<section
			aria-label={t("sectionAria")}
			className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-5 space-y-4"
		>
			<div className="flex items-center justify-between">
				<h2 className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">
					{t("titleCount", { count: photos.length })}
				</h2>
				<label
					htmlFor="photo-upload"
					className="inline-flex items-center gap-2 cursor-pointer rounded-lg border border-gray-300 dark:border-gray-700 px-3 py-1.5 text-xs font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-within:ring-2 focus-within:ring-brand-500 transition-colors"
				>
					<Upload size={14} aria-hidden="true" />
					{uploading ? t("uploading") : t("upload")}
					<input
						id="photo-upload"
						ref={fileInputRef}
						type="file"
						accept="image/*"
						multiple
						className="sr-only"
						onChange={handleFileChange}
						disabled={uploading}
						aria-label={tActions("uploadPhoto")}
					/>
				</label>
			</div>

			{error && (
				<div role="alert" className="text-xs text-red-600 dark:text-red-400">
					{error}
				</div>
			)}

			{photos.length === 0 ? (
				<p className="text-sm text-gray-400 text-center py-4">{t("empty")}</p>
			) : (
				<ul
					className="grid grid-cols-2 sm:grid-cols-3 gap-3"
					aria-label={t("listAria")}
				>
					{photos.map((photo, i) => (
						<li
							key={photo.id}
							className="relative group rounded-lg overflow-hidden aspect-square bg-gray-100 dark:bg-gray-800"
						>
							<Image
								src={getPublicUrl(photo.storage_path)}
								alt={photo.caption ?? t("fallbackAlt")}
								fill
								className="object-cover transition-transform duration-200 group-hover:scale-105"
								sizes="(max-width: 640px) 50vw, 200px"
							/>
							{/* Overlay buttons */}
							<div className="absolute inset-0 bg-black/0 group-hover:bg-black/30 transition-colors" />
							<button
								type="button"
								onClick={() => setLightboxIndex(i)}
								className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 focus-visible:opacity-100 transition-opacity focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-white"
								aria-label={t("viewPhoto", {
									n: i + 1,
									total: photos.length,
								})}
							>
								<ZoomIn
									size={22}
									className="text-white drop-shadow-lg"
									aria-hidden="true"
								/>
							</button>
							<button
								type="button"
								onClick={() => handleDelete(photo)}
								className="absolute top-1.5 right-1.5 rounded-full bg-black/60 p-1 text-white opacity-0 group-hover:opacity-100 focus-visible:opacity-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white transition-opacity z-10"
								aria-label={t("deletePhoto")}
							>
								<X size={12} aria-hidden="true" />
							</button>
						</li>
					))}
				</ul>
			)}

			{/* Lightbox */}
			{lightboxIndex !== null && (
				<PhotoLightbox
					photos={photos.map(
						(p): LightboxPhoto => ({
							src: getPublicUrl(p.storage_path),
							alt: p.caption ?? t("fallbackAlt"),
							caption: p.caption,
						}),
					)}
					index={lightboxIndex}
					onClose={() => setLightboxIndex(null)}
					onPrev={() => setLightboxIndex((i) => Math.max(0, (i ?? 0) - 1))}
					onNext={() =>
						setLightboxIndex((i) => Math.min(photos.length - 1, (i ?? 0) + 1))
					}
				/>
			)}
		</section>
	);
}
