"use client";
// Generated by GitHub Copilot
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";
import { syncSurveyToCalendar } from "@/lib/gcal/actions";
import Link from "next/link";
import { formatDate, formatRupiah } from "@/lib/utils";
import {
	StatusChip,
	proposalStatusVariant,
} from "@/components/shared/StatusChip";

type Lead = {
	id: string;
	status: string;
	customer_id: string;
	preferred_date: string | null;
};

type Survey = {
	id: string;
	scheduled_at: string;
	conducted_at: string | null;
	gcal_event_id: string | null;
} | null;

type Proposal = {
	id: string;
	proposal_number: string;
	status: string;
	final_price: number | null;
};

/**
 * Status-driven action panel on the Lead detail page.
 * Changes available actions based on lead.status.
 */
export function LeadActionPanel({
	lead,
	survey,
	proposals,
}: {
	lead: Lead;
	survey: Survey;
	proposals: Proposal[];
}) {
	const router = useRouter();
	const t = useTranslations("panels.leadActions");
	const tButtons = useTranslations("common.buttons");
	const [isPending, startTransition] = useTransition();
	const [showSurveyModal, setShowSurveyModal] = useState(false);
	const [error, setError] = useState<string | null>(null);

	// ── Skip → Estimate ───────────────────────────────────────────────
	async function handleSkipToEstimate() {
		setError(null);
		const supabase = createClient();

		// Generate proposal number via RPC
		const { data: proposalNumber } = await supabase.rpc(
			"generate_proposal_number",
			{
				service_type: "DOM",
			},
		);

		const { data: proposal, error: err } = await supabase
			.from("proposals")
			.insert({
				lead_id: lead.id,
				proposal_number: proposalNumber!,
				service_type: "DOM",
				status: "draft",
			})
			.select("id")
			.single();

		if (err) {
			setError(err.message);
			return;
		}

		await supabase
			.from("leads")
			.update({ status: "estimating" })
			.eq("id", lead.id);

		router.push(`/estimations/new?proposal_id=${proposal.id}`);
	}

	// ── Mark Survey Done ──────────────────────────────────────────────
	async function handleMarkSurveyDone() {
		setError(null);
		if (!survey) return;
		const supabase = createClient();
		const [surveyRes, leadRes] = await Promise.all([
			supabase
				.from("surveys")
				.update({ conducted_at: new Date().toISOString() })
				.eq("id", survey.id),
			supabase
				.from("leads")
				.update({ status: "survey_done" })
				.eq("id", lead.id),
		]);
		if (surveyRes.error || leadRes.error) {
			setError(surveyRes.error?.message ?? leadRes.error?.message ?? "Error");
			return;
		}
		startTransition(() => router.refresh());
	}

	// ── Create Estimation (after survey) ─────────────────────────────
	async function handleCreateEstimation() {
		setError(null);
		const supabase = createClient();
		const { data: proposalNumber } = await supabase.rpc(
			"generate_proposal_number",
			{
				service_type: "DOM",
			},
		);
		const { data: proposal, error: err } = await supabase
			.from("proposals")
			.insert({
				lead_id: lead.id,
				proposal_number: proposalNumber!,
				service_type: "DOM",
				status: "draft",
			})
			.select("id")
			.single();

		if (err) {
			setError(err.message);
			return;
		}

		await supabase
			.from("leads")
			.update({ status: "estimating" })
			.eq("id", lead.id);
		router.push(`/estimations/new?proposal_id=${proposal.id}`);
	}

	return (
		<div className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-5 space-y-4">
			<h2 className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">
				{t("title")}
			</h2>

			{error && (
				<div
					role="alert"
					className="rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 px-3 py-2 text-xs text-red-700 dark:text-red-300"
				>
					{error}
				</div>
			)}

			{/* ── STATUS: new ── */}
			{lead.status === "new" && (
				<div className="space-y-2">
					<button
						type="button"
						onClick={() => setShowSurveyModal(true)}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{t("scheduleSurvey")}
					</button>
					<button
						type="button"
						onClick={handleSkipToEstimate}
						disabled={isPending}
						className="w-full rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{t("skipToEstimate")}
					</button>
				</div>
			)}

			{/* ── STATUS: survey_scheduled ── */}
			{lead.status === "survey_scheduled" && survey && (
				<div className="space-y-3">
					<div className="text-sm">
						<p className="text-gray-500 dark:text-gray-400">{t("surveyScheduled")}</p>
						<p className="font-medium mt-0.5">
							{formatDate(survey.scheduled_at)}
						</p>
					</div>
					<div className="flex gap-2">
						<Link
							href={`/surveys/${survey.id}`}
							className="flex-1 text-center rounded-lg border border-gray-300 dark:border-gray-700 px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{t("viewSurvey")}
						</Link>
						<button
							type="button"
							onClick={handleMarkSurveyDone}
							disabled={isPending}
							className="flex-1 rounded-lg bg-brand-600 px-3 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{t("markDone")}
						</button>
					</div>
				</div>
			)}

			{/* ── STATUS: survey_done ── */}
			{lead.status === "survey_done" && (
				<div className="space-y-3">
					<p className="text-sm text-gray-500 dark:text-gray-400">
						{t("surveyCompleted")}{" "}
						{survey?.conducted_at ? formatDate(survey.conducted_at) : ""}
					</p>
					<button
						type="button"
						onClick={handleCreateEstimation}
						disabled={isPending}
						className="w-full rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{t("createEstimation")}
					</button>
				</div>
			)}

			{/* ── STATUS: estimating ── */}
			{lead.status === "estimating" && proposals.length > 0 && (
				<div className="space-y-2">
					<p className="text-sm text-gray-500 dark:text-gray-400">
						{t("estimationInProgress")}
					</p>
					<Link
						href={`/proposals/${proposals[0].id}`}
						className="block w-full text-center rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
					>
						{t("openProposal")}
					</Link>
				</div>
			)}

			{/* ── STATUS: proposal_sent ── */}
			{lead.status === "proposal_sent" && proposals.length > 0 && (
				<div className="space-y-2">
					{proposals.map((p) => (
						<div
							key={p.id}
							className="flex items-center justify-between text-sm"
						>
							<span className="font-mono text-xs text-gray-600 dark:text-gray-400">
								{p.proposal_number}
							</span>
							<div className="flex items-center gap-2">
								{p.final_price && (
									<span className="text-xs">{formatRupiah(p.final_price)}</span>
								)}
								<StatusChip
									label={p.status}
									variant={proposalStatusVariant(p.status)}
								/>
								<Link
									href={`/proposals/${p.id}`}
									className="text-brand-600 text-xs hover:underline focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-brand-500 rounded"
								>
										{tButtons("view")} →
								</Link>
							</div>
						</div>
					))}
				</div>
			)}

			{/* ── STATUS: converted ── */}
			{lead.status === "converted" && (
				<p className="text-sm text-green-600 dark:text-green-400 font-medium">
					{t("convertedToJob")}
				</p>
			)}

			{/* ── STATUS: closed_lost ── */}
			{lead.status === "closed_lost" && (
				<p className="text-sm text-red-500 font-medium">{t("closedLost")}</p>
			)}

			{/* Schedule survey modal */}
			{showSurveyModal && (
				<SurveyScheduleModal
					leadId={lead.id}
					onClose={() => setShowSurveyModal(false)}
					onDone={() => {
						setShowSurveyModal(false);
						startTransition(() => router.refresh());
					}}
				/>
			)}
		</div>
	);
}

// ── Schedule Survey Modal ─────────────────────────────────────────────────────
function SurveyScheduleModal({
	leadId,
	onClose,
	onDone,
}: {
	leadId: string;
	onClose: () => void;
	onDone: () => void;
}) {
	const tModal = useTranslations("modals.scheduleSurvey");
	const tButtons = useTranslations("common.buttons");
	const [form, setForm] = useState({ scheduled_at: "", notes: "" });
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const tErrors = useTranslations("common.errors");

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		if (!form.scheduled_at) {
			setError(tErrors("dateTimeRequired"));
			return;
		}
		setSaving(true);
		setError(null);

		try {
			const supabase = createClient();
			const { data: survey, error: survErr } = await supabase
				.from("surveys")
				.insert({
					lead_id: leadId,
					scheduled_at: new Date(form.scheduled_at).toISOString(),
					notes: form.notes.trim() || null,
				})
				.select("id")
				.single();
			if (survErr) throw survErr;

			await supabase
				.from("leads")
				.update({ status: "survey_scheduled" })
				.eq("id", leadId);

			// Best-effort calendar push — failures are surfaced via the retry button.
			if (survey?.id) {
				void syncSurveyToCalendar(survey.id).catch(() => {});
			}

			onDone();
		} catch (err: unknown) {
			setError(err instanceof Error ? err.message : "Error");
		} finally {
			setSaving(false);
		}
	}

	return (
		<div
			role="dialog"
			aria-modal="true"
			aria-labelledby="survey-modal-title"
			className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4"
		>
			<div className="w-full max-w-sm rounded-xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-6 shadow-xl space-y-4">
				<h3
					id="survey-modal-title"
					className="text-base font-semibold text-gray-900 dark:text-white"
				>
					{tModal("title")}
				</h3>

				{error && (
					<div
						role="alert"
						className="rounded bg-red-50 dark:bg-red-900/20 border border-red-200 px-3 py-2 text-xs text-red-700 dark:text-red-300"
					>
						{error}
					</div>
				)}

				<form onSubmit={handleSubmit} className="space-y-4">
					<div>
						<label
							htmlFor="survey_scheduled_at"
							className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
						>
							{tModal("dateTime")}{" "}
							<span aria-hidden="true" className="text-red-500">
								*
							</span>
						</label>
						<input
							id="survey_scheduled_at"
							type="datetime-local"
							value={form.scheduled_at}
							onChange={(e) =>
								setForm((p) => ({ ...p, scheduled_at: e.target.value }))
							}
							required
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
						/>
					</div>
					<div>
						<label
							htmlFor="survey_notes"
							className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
						>
							{tModal("notes")}
						</label>
						<textarea
							id="survey_notes"
							rows={2}
							value={form.notes}
							onChange={(e) =>
								setForm((p) => ({ ...p, notes: e.target.value }))
							}
							className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none"
						/>
					</div>
					<div className="flex gap-2">
						<button
							type="submit"
							disabled={saving}
							className="flex-1 rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{saving ? tButtons("scheduling") : tButtons("confirm")}
						</button>
						<button
							type="button"
							onClick={onClose}
							className="flex-1 rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
						>
							{tButtons("cancel")}
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}
