// Generated by GitHub Copilot
import { createClient } from "@/lib/supabase/server";
import Link from "next/link";
import { Suspense } from "react";
import { getTranslations, getLocale } from "next-intl/server";
import {
	Truck,
	FileText,
	Receipt,
	CalendarDays,
	TrendingUp,
	ArrowUpRight,
	CheckCircle2,
	ClipboardList,
	Clock,
	Users,
	Banknote,
	AlertCircle,
} from "lucide-react";
import { formatRupiah, formatDate } from "@/lib/utils";
import { DashboardTabBar } from "@/components/dashboard/DashboardTabBar";

function startOfMonth() {
	const d = new Date();
	return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().split("T")[0];
}
function todayISO() {
	return new Date().toISOString().split("T")[0];
}

/** Map job status to a display-friendly pill style */
async function JobStatusPill({ status }: { status: string }) {
	const tStatus = await getTranslations("status.job");
	const cfg: Record<string, { cls: string }> = {
		scheduled: { cls: "bg-slate-100 text-slate-600" },
		in_progress: { cls: "bg-blue-100 text-blue-700" },
		completed: { cls: "bg-green-100 text-green-700" },
		closed: { cls: "bg-green-50 text-green-600" },
		cancelled: { cls: "bg-red-100 text-red-600" },
	};
	const cls = cfg[status]?.cls ?? "bg-slate-100 text-slate-600";
	let label = status;
	try {
		label = tStatus(status as Parameters<typeof tStatus>[0]);
	} catch {
		// Fallback to raw status if no translation key exists
	}
	return (
		<span
			className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${cls}`}
		>
			<span
				className="w-1.5 h-1.5 rounded-full bg-current opacity-70"
				aria-hidden="true"
			/>
			{label}
		</span>
	);
}

/**
 * Operations Dashboard — rich multi-section layout with KPIs, jobs table,
 * financial health, upcoming events and operational tasks.
 */
export default async function DashboardPage({
	searchParams,
}: {
	searchParams: Promise<{ tab?: string }>;
}) {
	const { tab: rawTab } = await searchParams;
	const tab = (rawTab ?? "overview").toLowerCase() as
		| "overview"
		| "dispatch"
		| "financials";

	const t = await getTranslations("dashboard");
	const tTabs = await getTranslations("dashboard.tabs");
	const tKpi = await getTranslations("dashboard.kpi");
	const tSections = await getTranslations("dashboard.sections");
	const tColumns = await getTranslations("dashboard.columns");
	const tEmpty = await getTranslations("dashboard.empty");
	const tActions = await getTranslations("dashboard.actions");
	const tProgress = await getTranslations("dashboard.progress");
	const tInvoiceLegend = await getTranslations("dashboard.invoiceLegend");
	const tDispatch = await getTranslations("dashboard.dispatch");
	const tCommon = await getTranslations("common");
	const locale = await getLocale();
	const supabase = await createClient();
	const today = todayISO();
	const monthStart = startOfMonth();

	const [
		{ count: activeJobsCount },
		{ count: openProposalsCount },
		{ data: unpaidInvoices },
		{ count: movesTodayCount },
		{ data: recentJobs },
		{ data: upcomingJobs },
		{ data: monthlyPaid },
		{ data: monthlyExp },
		{ data: pendingSurveys },
		{ data: draftProposals },
		{ data: revenueTargetSetting },
	] = await Promise.all([
		supabase
			.from("jobs")
			.select("*", { count: "exact", head: true })
			.in("status", ["scheduled", "in_progress"]),
		supabase
			.from("proposals")
			.select("*", { count: "exact", head: true })
			.in("status", ["draft", "sent", "negotiating"]),
		supabase
			.from("invoice_outstanding")
			.select("outstanding")
			.neq("effective_status", "paid"),
		supabase
			.from("jobs")
			.select("*", { count: "exact", head: true })
			.eq("move_date", today),
		supabase
			.from("jobs")
			.select(
				"id, job_number, status, move_date, revenue, proposals(lead_id, leads(customers(name, type)))",
			)
			.in("status", ["scheduled", "in_progress"])
			.order("move_date")
			.limit(5),
		supabase
			.from("jobs")
			.select("id, job_number, move_date, status, notes")
			.gte("move_date", today)
			.order("move_date")
			.limit(4),
		supabase
			.from("invoices")
			.select("paid_amount")
			.in("status", ["paid", "partially_paid"])
			.gte("created_at", monthStart),
		supabase.from("expenses").select("amount").gte("incurred_at", monthStart),
		supabase
			.from("leads")
			.select("id, status, pickup_address, customers(name)")
			.eq("status", "survey_scheduled")
			.order("created_at")
			.limit(2),
		supabase
			.from("proposals")
			.select("id, proposal_number")
			.eq("status", "draft")
			.order("created_at")
			.limit(2),
		supabase
			.from("system_settings")
			.select("value")
			.eq("key", "revenue_target_monthly")
			.maybeSingle(),
	]);

	// ── Tab-specific data ──────────────────────────────────────────────────────
	// Dispatch: jobs in next 7 days with assignments + customer
	type DispatchJob = {
		id: string;
		job_number: string;
		status: string;
		move_date: string;
		notes: string | null;
		proposals: {
			leads: {
				pickup_address: string | null;
				destination_address: string | null;
				customers: { name: string; phone: string | null } | null;
			} | null;
		} | null;
		job_assignments: {
			id: string;
			assignment_type: string;
			role: string | null;
			vendors: { name: string } | null;
			crew: { name: string } | null;
		}[];
	};
	let dispatchJobs: DispatchJob[] = [];

	// Financials: recent payments + invoice status breakdown
	type Payment = {
		id: string;
		amount: number;
		paid_at: string;
		method: string | null;
		jobs: {
			job_number: string;
			invoices: { invoice_number: string }[];
		} | null;
	};
	type InvoiceStatusRow = { status: string; total_amount: number };
	let recentPayments: Payment[] = [];
	let invoicesByStatus: InvoiceStatusRow[] = [];

	if (tab === "dispatch") {
		const next7 = new Date();
		next7.setDate(next7.getDate() + 7);
		const next7ISO = next7.toISOString().split("T")[0];

		const { data } = await supabase
			.from("jobs")
			.select(`
				id, job_number, status, move_date, notes,
				proposals(leads(pickup_address, destination_address, customers(name, phone))),
				job_assignments(id, assignment_type, role, vendors(name), crew(name))
			`)
			.in("status", ["scheduled", "in_progress"])
			.gte("move_date", today)
			.lte("move_date", next7ISO)
			.order("move_date");
		dispatchJobs = (data ?? []) as DispatchJob[];
	}

	if (tab === "financials") {
		const [{ data: paymentsData }, { data: invStatusData }] = await Promise.all(
			[
				supabase
					.from("payments")
					.select(
						"id, amount, paid_at, method, jobs(job_number, invoices(invoice_number))",
					)
					.order("paid_at", { ascending: false })
					.limit(8),
				supabase
					.from("invoices")
					.select("status, total_amount")
					.neq("status", "cancelled"),
			],
		);
		recentPayments = (paymentsData ?? []) as Payment[];
		invoicesByStatus = (invStatusData ?? []) as InvoiceStatusRow[];
	}

	const totalOutstanding = (unpaidInvoices ?? []).reduce(
		(s, i) => s + (i.outstanding ?? 0),
		0,
	);
	const unpaidCount = unpaidInvoices?.length ?? 0;
	const monthRevenue = (monthlyPaid ?? []).reduce(
		(s, i) => s + (i.paid_amount ?? 0),
		0,
	);
	const monthExpenses = (monthlyExp ?? []).reduce(
		(s, i) => s + (i.amount ?? 0),
		0,
	);
	const revenueTarget = revenueTargetSetting?.value
		? Number(revenueTargetSetting.value)
		: 50_000_000; // fallback if not set in system_settings
	const revenueProgress = Math.min(
		100,
		Math.round((monthRevenue / revenueTarget) * 100),
	);

	// Derive quick tasks
	type Task = {
		id: string;
		icon: "survey" | "proposal" | "job";
		title: string;
		subtitle: string;
		action: string;
		href: string;
	};
	const tasks: Task[] = [
		...(pendingSurveys ?? []).map((l) => ({
			id: `survey-${l.id}`,
			icon: "survey" as const,
			title: tActions("inHomeSurvey", {
				name:
					(l.customers as { name: string } | null)?.name ??
					tCommon("labels.customer"),
			}),
			subtitle: tActions("scheduledAt", {
				address: l.pickup_address ?? tActions("addressTbd"),
			}),
			action: tActions("markSurveyDone"),
			href: `/leads/${l.id}`,
		})),
		...(draftProposals ?? []).map((p) => ({
			id: `proposal-${p.id}`,
			icon: "proposal" as const,
			title: tActions("generateProposal", { number: p.proposal_number }),
			subtitle: tActions("draftReady"),
			action: tActions("generateProposalAction"),
			href: `/proposals/${p.id}`,
		})),
	].slice(0, 3);

	const MONTH_NAMES = [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Oct",
		"Nov",
		"Dec",
	];
	const now = new Date();
	const headerDate = now.toLocaleDateString(locale, {
		month: "short",
		day: "numeric",
		year: "numeric",
	});

	return (
		<div className="space-y-5">
			{/* Page header */}
			<div className="flex items-center justify-between flex-wrap gap-3">
				<div>
					<h1 className="text-2xl font-bold text-slate-800">{t("title")}</h1>
					<p className="text-sm text-slate-500 mt-0.5">
						{t("subtitle", { date: headerDate })}
					</p>
				</div>
				<div className="flex items-center gap-2">
					<Suspense
						fallback={
							<div className="flex items-center gap-1">
								{(["overview", "dispatch", "financials"] as const).map((k) => (
									<span
										key={k}
										className="px-3.5 py-1.5 rounded-lg text-sm font-medium text-slate-400 bg-slate-100 animate-pulse"
									>
										{tTabs(k)}
									</span>
								))}
							</div>
						}
					>
						<DashboardTabBar />
					</Suspense>
				</div>
			</div>

			{/* KPI Cards — always visible */}
			{tab === "overview" && (
				<>
					{/* KPI Cards */}
					<div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
						<KpiCard
							icon={<Truck size={18} />}
							iconBg="bg-blue-500"
							badge={{
								label: tKpi("active"),
								color: "text-blue-600 bg-blue-50",
							}}
							title={tKpi("activeJobs")}
							value={String(activeJobsCount ?? 0)}
							sub={tKpi("movesTodayCount", { count: movesTodayCount ?? 0 })}
							href="/jobs"
						/>
						<KpiCard
							icon={<FileText size={18} />}
							iconBg="bg-orange-500"
							badge={{
								label: tKpi("highValue"),
								color: "text-orange-600 bg-orange-50",
							}}
							title={tKpi("openProposals")}
							value={String(openProposalsCount ?? 0)}
							sub={tKpi("pendingApproval")}
							href="/proposals"
						/>
						<KpiCard
							icon={<Receipt size={18} />}
							iconBg="bg-red-500"
							badge={{
								label: tKpi("actionRequired"),
								color: "text-red-600 bg-red-50",
							}}
							title={tKpi("unpaidInvoices")}
							value={String(unpaidCount)}
							sub={tKpi("amountOverdue", {
								amount: formatRupiah(totalOutstanding),
							})}
							href="/invoices"
						/>
						<KpiCard
							icon={<CalendarDays size={18} />}
							iconBg="bg-purple-500"
							badge={{
								label: tKpi("scheduledBadge"),
								color: "text-purple-600 bg-purple-50",
							}}
							title={tKpi("movesToday")}
							value={String(movesTodayCount ?? 0)}
							sub={tKpi("confirmedBookings")}
							href="/calendar"
						/>
					</div>

					{/* Middle row: jobs table + financial panel */}
					<div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
						{/* Priority Active Jobs */}
						<div className="lg:col-span-2 bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
							<div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
								<h2 className="text-sm font-semibold text-slate-800">
									{tSections("priorityActiveJobs")}
								</h2>
								<Link
									href="/jobs"
									className="text-xs font-medium text-brand-600 hover:text-brand-700 flex items-center gap-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
								>
									{tActions("viewAll")}{" "}
									<ArrowUpRight size={13} aria-hidden="true" />
								</Link>
							</div>

							<table
								className="w-full text-sm"
								aria-label={tSections("priorityActiveJobs")}
							>
								<thead>
									<tr className="text-xs text-slate-500 uppercase tracking-wider">
										<th className="px-5 py-3 text-left font-semibold">
											{tColumns("jobId")}
										</th>
										<th className="px-3 py-3 text-left font-semibold">
											{tColumns("customer")}
										</th>
										<th className="px-3 py-3 text-left font-semibold">
											{tColumns("status")}
										</th>
										<th className="px-3 py-3 text-right font-semibold">
											{tColumns("revenue")}
										</th>
									</tr>
								</thead>
								<tbody className="divide-y divide-slate-50">
									{(recentJobs ?? []).length === 0 ? (
										<tr>
											<td
												colSpan={4}
												className="px-5 py-8 text-center text-slate-400 text-sm"
											>
												{tEmpty("noJobs")}
											</td>
										</tr>
									) : (
										(recentJobs ?? []).map((job) => {
											const proposal = job.proposals as {
												leads: {
													customers: { name: string; type: string } | null;
												} | null;
											} | null;
											const customerName =
												proposal?.leads?.customers?.name ?? "—";
											const customerType =
												proposal?.leads?.customers?.type ?? "";
											return (
												<tr
													key={job.id}
													className="hover:bg-slate-50 transition-colors"
												>
													<td className="px-5 py-3.5">
														<Link
															href={`/jobs/${job.id}`}
															className="font-mono text-xs font-bold text-slate-700 hover:text-brand-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
														>
															#{job.job_number}
														</Link>
													</td>
													<td className="px-3 py-3.5">
														<p className="font-medium text-slate-800 text-[13px]">
															{customerName}
														</p>
														<p className="text-xs text-slate-400 capitalize">
															{customerType.replace("_", " ")}
														</p>
													</td>
													<td className="px-3 py-3.5">
														<JobStatusPill status={job.status} />
													</td>
													<td className="px-3 py-3.5 text-right font-semibold text-slate-700 text-[13px] tabular-nums">
														{formatRupiah(job.revenue)}
													</td>
												</tr>
											);
										})
									)}
								</tbody>
							</table>
						</div>

						{/* Financial Health */}
						<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-5 flex flex-col gap-4">
							<div className="flex items-center justify-between">
								<h2 className="text-sm font-semibold text-slate-800">
									{tSections("financialHealth")}
								</h2>
							</div>

							{/* Revenue target */}
							<div>
								<div className="flex justify-between text-xs text-slate-500 mb-1.5">
									<span>{tSections("revenueMonthlyTarget")}</span>
									<span className="font-semibold text-slate-700">
										{formatRupiah(monthRevenue)} / {formatRupiah(revenueTarget)}
									</span>
								</div>
								<div
									className="h-2 rounded-full bg-slate-100 overflow-hidden"
									role="progressbar"
									aria-valuenow={revenueProgress}
									aria-valuemin={0}
									aria-valuemax={100}
									aria-label={tProgress("monthlyTargetAria", {
										pct: revenueProgress,
									})}
								>
									<div
										className="h-full rounded-full bg-brand-600 transition-all duration-500"
										style={{ width: `${revenueProgress}%` }}
									/>
								</div>
							</div>

							{/* Revenue + Expenses mini cards */}
							<div className="grid grid-cols-2 gap-3">
								<div className="bg-slate-50 rounded-xl p-3">
									<p className="text-xs text-slate-500 mb-1">
										{tSections("monthRevenueLabel")}
									</p>
									<p className="text-base font-bold text-slate-800 tabular-nums">
										{formatRupiah(monthRevenue)}
									</p>
								</div>
								<div className="bg-slate-50 rounded-xl p-3">
									<p className="text-xs text-slate-500 mb-1">
										{tSections("monthExpensesLabel")}
									</p>
									<p className="text-base font-bold text-red-600 tabular-nums">
										{formatRupiah(monthExpenses)}
									</p>
								</div>
							</div>

							{/* Profit line */}
							<div className="flex items-center gap-2 text-sm">
								<TrendingUp
									size={15}
									className="text-green-500 shrink-0"
									aria-hidden="true"
								/>
								<span className="text-slate-500 text-xs">
									{tSections("netThisMonth")}
								</span>
								<span className="ml-auto font-bold text-slate-800 tabular-nums text-sm">
									{formatRupiah(monthRevenue - monthExpenses)}
								</span>
							</div>

							<Link
								href="/reports"
								className="mt-auto text-center text-xs font-medium text-brand-600 hover:text-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
							>
								{tActions("viewFullReport")}
							</Link>
						</div>
					</div>

					{/* Bottom row: Upcoming + Tasks */}
					<div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
						{/* Upcoming */}
						<div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
							<div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
								<h2 className="text-sm font-semibold text-slate-800">
									{tSections("upcoming")}
								</h2>
								<Link
									href="/calendar"
									className="text-xs font-medium text-brand-600 hover:text-brand-700 flex items-center gap-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
								>
									<CalendarDays size={13} aria-hidden="true" />
								</Link>
							</div>
							<div className="divide-y divide-slate-50">
								{(upcomingJobs ?? []).length === 0 ? (
									<p className="px-5 py-6 text-sm text-slate-400 text-center">
										{tEmpty("noJobs")}
									</p>
								) : (
									(upcomingJobs ?? []).map((job) => {
										const d = new Date(job.move_date + "T00:00:00");
										return (
											<Link
												key={job.id}
												href={`/jobs/${job.id}`}
												className="flex items-center gap-4 px-5 py-3.5 hover:bg-slate-50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-brand-500"
											>
												<div className="shrink-0 w-10 text-center">
													<p className="text-[10px] font-bold text-brand-600 uppercase">
														{MONTH_NAMES[d.getMonth()]}
													</p>
													<p className="text-lg font-bold text-slate-800 leading-none">
														{d.getDate()}
													</p>
												</div>
												<div className="min-w-0">
													<p className="text-[13px] font-semibold text-slate-800 truncate">
														#{job.job_number}
													</p>
													<p className="text-xs text-slate-400 flex items-center gap-1">
														<Clock size={10} aria-hidden="true" />
														{formatDate(job.move_date)}
													</p>
												</div>
												<JobStatusPill status={job.status} />
											</Link>
										);
									})
								)}
							</div>
						</div>

						{/* Current Operational Tasks */}
						<div className="lg:col-span-2 bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
							<div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
								<h2 className="text-sm font-semibold text-slate-800">
									{tSections("actionItems")}
								</h2>
								<Link
									href="/leads"
									className="text-xs font-medium text-brand-600 hover:text-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
								>
									{tActions("viewAll")}
								</Link>
							</div>
							<div className="divide-y divide-slate-50">
								{tasks.length === 0 ? (
									<div className="px-5 py-8 text-center">
										<CheckCircle2
											size={28}
											className="text-green-400 mx-auto mb-2"
											aria-hidden="true"
										/>
										<p className="text-sm font-medium text-slate-600">
											{tEmpty("noActions")}
										</p>
										<p className="text-xs text-slate-400 mt-0.5">
											{tEmpty("noActionsHint")}
										</p>
									</div>
								) : (
									tasks.map((task) => (
										<div
											key={task.id}
											className="flex items-center gap-4 px-5 py-4"
										>
											<div
												className={`w-9 h-9 rounded-full flex items-center justify-center shrink-0 ${
													task.icon === "survey"
														? "bg-blue-50 text-blue-600"
														: task.icon === "proposal"
															? "bg-orange-50 text-orange-600"
															: "bg-green-50 text-green-600"
												}`}
											>
												{task.icon === "survey" && (
													<ClipboardList size={16} aria-hidden="true" />
												)}
												{task.icon === "proposal" && (
													<FileText size={16} aria-hidden="true" />
												)}
												{task.icon === "job" && (
													<CheckCircle2 size={16} aria-hidden="true" />
												)}
											</div>
											<div className="flex-1 min-w-0">
												<p className="text-[13px] font-semibold text-slate-800 truncate">
													{task.title}
												</p>
												<p className="text-xs text-slate-400 truncate">
													{task.subtitle}
												</p>
											</div>
											<Link
												href={task.href}
												className={`shrink-0 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${
													task.icon === "survey"
														? "bg-navy-900 text-white hover:bg-navy-800"
														: "bg-brand-600 text-white hover:bg-brand-700"
												}`}
											>
												{task.action}
											</Link>
										</div>
									))
								)}
							</div>
						</div>
					</div>
				</>
			)}

			{/* ── DISPATCH TAB ───────────────────────────────────────────────── */}
			{tab === "dispatch" && (
				<div className="space-y-4">
					<div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
						<div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
							<h2 className="text-sm font-semibold text-slate-800">
								{tSections("dispatchBoard")}
							</h2>
							<Link
								href="/jobs"
								className="text-xs font-medium text-brand-600 hover:text-brand-700 flex items-center gap-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
							>
								{tActions("viewAll")}{" "}
								<ArrowUpRight size={13} aria-hidden="true" />
							</Link>
						</div>

						{dispatchJobs.length === 0 ? (
							<div className="px-5 py-12 text-center text-slate-400 text-sm">
								{tEmpty("noDispatch")}
							</div>
						) : (
							<div className="divide-y divide-slate-50">
								{dispatchJobs.map((job) => {
									const lead = job.proposals?.leads ?? null;
									const customer = lead?.customers ?? null;
									const d = new Date(job.move_date + "T00:00:00");
									const isToday = job.move_date === today;
									return (
										<div key={job.id} className="px-5 py-4 space-y-3">
											{/* Row 1: date + job number + status */}
											<div className="flex items-start justify-between gap-3 flex-wrap">
												<div className="flex items-center gap-3">
													<div
														className={`shrink-0 w-12 text-center rounded-xl py-1 ${isToday ? "bg-brand-600 text-white" : "bg-slate-100 text-slate-600"}`}
													>
														<p className="text-[9px] font-bold uppercase tracking-wide">
															{MONTH_NAMES[d.getMonth()]}
														</p>
														<p className="text-lg font-bold leading-none">
															{d.getDate()}
														</p>
													</div>
													<div>
														<Link
															href={`/jobs/${job.id}`}
															className="font-mono text-sm font-bold text-slate-700 hover:text-brand-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
														>
															#{job.job_number}
														</Link>
														{customer && (
															<p className="text-xs text-slate-500 mt-0.5 flex items-center gap-1">
																<Users size={11} aria-hidden="true" />
																{customer.name}
																{customer.phone && ` · ${customer.phone}`}
															</p>
														)}
													</div>
												</div>
												<JobStatusPill status={job.status} />
											</div>

											{/* Row 2: pickup → destination */}
											{(lead?.pickup_address || lead?.destination_address) && (
												<div className="flex items-center gap-2 text-xs text-slate-500 bg-slate-50 rounded-lg px-3 py-2">
													<Truck
														size={13}
														className="shrink-0 text-brand-500"
														aria-hidden="true"
													/>
													<span className="truncate">
														{lead.pickup_address ?? "—"}
													</span>
													<span className="shrink-0 text-slate-300">→</span>
													<span className="truncate">
														{lead.destination_address ?? "—"}
													</span>
												</div>
											)}

											{/* Row 3: assignments */}
											{job.job_assignments.length > 0 && (
												<div className="flex flex-wrap gap-2">
													{job.job_assignments.map((a) => {
														const name =
															a.assignment_type === "vendor"
																? a.vendors?.name
																: a.crew?.name;
														return (
															<span
																key={a.id}
																className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-navy-900/5 text-navy-900 text-[11px] font-medium"
															>
																<Users size={10} aria-hidden="true" />
																{name ?? "—"}
																{a.role && (
																	<span className="text-slate-400">
																		· {a.role}
																	</span>
																)}
															</span>
														);
													})}
												</div>
											)}
											{job.job_assignments.length === 0 && (
												<p className="text-[11px] text-amber-600 flex items-center gap-1">
													<AlertCircle size={11} aria-hidden="true" />
													{tDispatch("noAssignments")}
												</p>
											)}
										</div>
									);
								})}
							</div>
						)}
					</div>
				</div>
			)}

			{/* ── FINANCIALS TAB ─────────────────────────────────────────────── */}
			{tab === "financials" && (
				<div className="space-y-4">
					{/* Summary KPIs */}
					<div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
						<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-4 space-y-1">
							<p className="text-xs text-slate-500 font-medium">
								{tSections("monthRevenueLabel")}
							</p>
							<p className="text-xl font-bold text-slate-800 tabular-nums">
								{formatRupiah(monthRevenue)}
							</p>
							<div
								className="h-1.5 rounded-full bg-slate-100 overflow-hidden mt-2"
								role="progressbar"
								aria-valuenow={revenueProgress}
								aria-valuemin={0}
								aria-valuemax={100}
								aria-label={tProgress("ofTargetAria", { pct: revenueProgress })}
							>
								<div
									className="h-full rounded-full bg-brand-600"
									style={{ width: `${revenueProgress}%` }}
								/>
							</div>
							<p className="text-[10px] text-slate-400">
								{tProgress("ofTargetAria", { pct: revenueProgress })}
							</p>
						</div>
						<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-4 space-y-1">
							<p className="text-xs text-slate-500 font-medium">
								{tSections("monthExpensesLabel")}
							</p>
							<p className="text-xl font-bold text-red-600 tabular-nums">
								{formatRupiah(monthExpenses)}
							</p>
						</div>
						<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-4 space-y-1">
							<p className="text-xs text-slate-500 font-medium">
								{tSections("netProfit")}
							</p>
							<p
								className={`text-xl font-bold tabular-nums ${monthRevenue - monthExpenses >= 0 ? "text-green-600" : "text-red-600"}`}
							>
								{formatRupiah(monthRevenue - monthExpenses)}
							</p>
						</div>
						<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-4 space-y-1">
							<p className="text-xs text-slate-500 font-medium">
								{tKpi("outstanding")}
							</p>
							<p className="text-xl font-bold text-amber-600 tabular-nums">
								{formatRupiah(totalOutstanding)}
							</p>
							<p className="text-[10px] text-slate-400">
								{tKpi("unpaidInvoicesCount", { count: unpaidCount })}
							</p>
						</div>
					</div>

					<div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
						{/* Invoice breakdown by status */}
						<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-5">
							<h2 className="text-sm font-semibold text-slate-800 mb-4">
								{tSections("invoiceStatus")}
							</h2>
							{(() => {
								const groups: Record<string, { count: number; total: number }> =
									{};
								for (const inv of invoicesByStatus) {
									if (!groups[inv.status])
										groups[inv.status] = { count: 0, total: 0 };
									groups[inv.status].count++;
									groups[inv.status].total += inv.total_amount;
								}
								const STATUS_CFG: Record<
									string,
									{ label: string; dot: string }
								> = {
									draft: { label: tInvoiceLegend("draft"), dot: "bg-slate-400" },
									sent: { label: tInvoiceLegend("sent"), dot: "bg-blue-500" },
									partially_paid: {
										label: tInvoiceLegend("partiallyPaid"),
										dot: "bg-yellow-500",
									},
									paid: { label: tInvoiceLegend("paid"), dot: "bg-green-500" },
									overdue: {
										label: tInvoiceLegend("overdue"),
										dot: "bg-red-500",
									},
								};
								return (
									<div className="space-y-2.5">
										{Object.entries(groups).map(
											([status, { count, total }]) => (
												<div
													key={status}
													className="flex items-center gap-3 text-sm"
												>
													<span
														className={`w-2.5 h-2.5 rounded-full shrink-0 ${STATUS_CFG[status]?.dot ?? "bg-slate-300"}`}
														aria-hidden="true"
													/>
													<span className="flex-1 text-slate-600">
														{STATUS_CFG[status]?.label ?? status} ({count})
													</span>
													<span className="tabular-nums font-medium text-slate-800">
														{formatRupiah(total)}
													</span>
												</div>
											),
										)}
										{Object.keys(groups).length === 0 && (
											<p className="text-sm text-slate-400">
												{tEmpty("noInvoices")}
											</p>
										)}
									</div>
								);
							})()}
							<Link
								href="/invoices"
								className="mt-4 block text-xs font-medium text-brand-600 hover:text-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
							>
								{tActions("manageInvoices")}
							</Link>
						</div>

						{/* Recent payments */}
						<div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-5">
							<h2 className="text-sm font-semibold text-slate-800 mb-4">
								{tSections("recentPayments")}
							</h2>
							{recentPayments.length === 0 ? (
								<p className="text-sm text-slate-400">
									{tEmpty("noPayments")}
								</p>
							) : (
								<div className="space-y-3">
									{recentPayments.map((p) => (
										<div key={p.id} className="flex items-center gap-3 text-sm">
											<div className="w-7 h-7 rounded-full bg-green-50 flex items-center justify-center shrink-0">
												<Banknote
													size={13}
													className="text-green-600"
													aria-hidden="true"
												/>
											</div>
											<div className="flex-1 min-w-0">
												<p className="font-medium text-slate-800 text-[13px] tabular-nums">
													{formatRupiah(p.amount)}
												</p>
												<p className="text-xs text-slate-400 truncate">
													{p.jobs?.invoices?.[0]?.invoice_number ??
														p.jobs?.job_number ??
														"—"}
													{p.method && ` · ${p.method}`}
												</p>
											</div>
											<span className="text-xs text-slate-400 shrink-0">
												{p.paid_at ? formatDate(p.paid_at) : "—"}
											</span>
										</div>
									))}
								</div>
							)}
							<Link
								href="/invoices"
								className="mt-4 block text-xs font-medium text-brand-600 hover:text-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 rounded"
							>
								{tActions("viewAll")}
							</Link>
						</div>
					</div>
				</div>
			)}
		</div>
	);
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function KpiCard({
	icon,
	iconBg,
	badge,
	title,
	value,
	sub,
	href,
}: {
	icon: React.ReactNode;
	iconBg: string;
	badge: { label: string; color: string };
	title: string;
	value: string;
	sub: string;
	href: string;
}) {
	return (
		<Link
			href={href}
			className="bg-white rounded-2xl shadow-sm border border-slate-100 p-4 hover:shadow-md transition-shadow focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 group"
		>
			<div className="flex items-start justify-between mb-3">
				<div
					className={`w-10 h-10 rounded-xl ${iconBg} text-white flex items-center justify-center shrink-0`}
				>
					{icon}
				</div>
				<span
					className={`text-[11px] font-bold px-2.5 py-1 rounded-full ${badge.color}`}
				>
					{badge.label}
				</span>
			</div>
			<p className="text-xs text-slate-500 font-semibold uppercase tracking-wide mb-1">{title}</p>
			<p className="text-3xl font-bold text-slate-800 leading-none mb-1.5 tabular-nums group-hover:text-brand-600 transition-colors">
				{value}
			</p>
			<p className="text-xs text-slate-500">{sub}</p>
		</Link>
	);
}
