"use client";
// Generated by GitHub Copilot
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { useTranslations } from "next-intl";

const TABS = ["overview", "dispatch", "financials"] as const;
type Tab = (typeof TABS)[number];

/**
 * Tab bar for the Operations Dashboard.
 * Reads active tab from the `?tab=` search param and navigates via Link.
 */
export function DashboardTabBar() {
	const searchParams = useSearchParams();
	const t = useTranslations("dashboard.tabs");
	const rawTab = (searchParams.get("tab") ?? "overview").toLowerCase();
	const activeTab: Tab = (TABS.find((x) => x === rawTab) as Tab) ?? "overview";

	return (
		<div
			className="flex items-center gap-1"
			role="tablist"
			aria-label="Dashboard views"
		>
			{TABS.map((tab) => {
				const isActive = tab === activeTab;
				return (
					<Link
						key={tab}
						href={tab === "overview" ? "/dashboard" : `/dashboard?tab=${tab}`}
						role="tab"
						aria-selected={isActive}
						className={`px-3.5 py-1.5 rounded-lg text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${
							isActive
								? "bg-white text-slate-800 shadow-sm border border-slate-200"
								: "text-slate-500 hover:text-slate-700 hover:bg-white/60"
						}`}
					>
						{t(tab)}
					</Link>
				);
			})}
		</div>
	);
}
