// Generated by GitHub Copilot
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { formatDate, formatRupiah } from "@/lib/utils";
import {
	buildCompanySettings,
	buildInvoiceTemplateSettings,
} from "@/lib/pdfSettings";
import { StatusChip } from "@/components/shared/StatusChip";
import { PaymentsPanel } from "@/components/invoices/PaymentsPanel";
import { InvoicePDFDownloadButton } from "@/components/invoices/InvoicePDFDownloadButton";

const STATUS_COLOR: Record<string, string> = {
	draft: "gray",
	sent: "blue",
	partially_paid: "yellow",
	paid: "green",
	overdue: "red",
	cancelled: "gray",
};

export default async function InvoiceDetailPage({
	params,
}: {
	params: Promise<{ id: string }>;
}) {
	const { id } = await params;
	const supabase = await createClient();
	const t = await getTranslations("pages.invoiceDetail");
	const tStatus = await getTranslations("status.invoice");

	const [{ data: invoice }, { data: settingsRows }] = await Promise.all([
		supabase
			.from("invoices")
			.select(`
        *,
        jobs(
          id, job_number, move_date,
          proposals(leads(customers(id, name, phone, email)))
        )
      `)
			.eq("id", id)
			.single(),
		supabase
			.from("system_settings")
			.select("key, value")
			.in("key", ["company_name", "company_tagline", "invoice_footer_note"]),
	]);

	if (!invoice) notFound();

	// Payments now live on the job, not the invoice — fetch via job_id.
	const { data: payments } = await supabase
		.from("payments")
		.select("id, payment_type, method, amount, paid_at, notes")
		.eq("job_id", invoice.job_id)
		.order("paid_at");

	const settingsMap = Object.fromEntries(
		(settingsRows ?? []).map((s) => [s.key, s.value]),
	);
	const pdfCompany = buildCompanySettings(settingsMap);
	const pdfTemplate = buildInvoiceTemplateSettings(settingsMap);

	const job = invoice.jobs as {
		id: string;
		job_number: string;
		move_date: string | null;
		proposals: {
			leads: {
				customers: {
					id: string;
					name: string;
					phone: string | null;
					email: string | null;
				} | null;
			} | null;
		} | null;
	} | null;

	const customer = job?.proposals?.leads?.customers ?? null;

	return (
		<div className="space-y-6">
			{/* Header */}
			<div className="flex items-start justify-between flex-wrap gap-4">
				<div>
					<div className="flex items-center gap-3 mb-1">
						<h1 className="text-2xl font-bold font-mono text-gray-900 dark:text-white">
							{invoice.invoice_number}
						</h1>
						<StatusChip
							label={tStatus(invoice.status as never)}
							variant={
								(STATUS_COLOR[invoice.status] as Parameters<
									typeof StatusChip
								>[0]["variant"]) ?? "gray"
							}
						/>
					</div>
					<p className="text-sm text-gray-500 dark:text-gray-400">
						{customer?.name ?? "—"}
						{invoice.due_date &&
							` · ${t("due", { date: formatDate(invoice.due_date) })}`}
						{job && (
							<>
								{" "}
								·{" "}
								<Link
									href={`/jobs/${job.id}`}
									className="text-brand-600 hover:underline"
								>
									{job.job_number}
								</Link>
							</>
						)}
					</p>
				</div>
				{customer && job && (
					<InvoicePDFDownloadButton
						pdfProps={{
							invoice: {
								invoice_number: invoice.invoice_number,
								total_amount: invoice.total_amount,
								paid_amount: invoice.paid_amount ?? 0,
								status: invoice.status,
								due_date: invoice.due_date ?? null,
								notes: invoice.notes ?? null,
								created_at: invoice.created_at,
							},
							job: {
								job_number: job.job_number,
								move_date: job.move_date ?? null,
							},
							customer: {
								name: customer.name,
								phone: customer.phone ?? null,
								email: customer.email ?? null,
							},
							company: pdfCompany,
							template: pdfTemplate,
						}}
					/>
				)}
			</div>

			<div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
				<div className="lg:col-span-2 space-y-6">
					<section className="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-5 text-sm space-y-3">
						{customer && (
							<>
								<div className="flex gap-4">
									<span className="w-32 text-gray-500">{t("customer")}</span>
									<span className="font-medium">{customer.name}</span>
								</div>
								{customer.phone && (
									<div className="flex gap-4">
										<span className="w-32 text-gray-500">{t("phone")}</span>
										<span>{customer.phone}</span>
									</div>
								)}
								{customer.email && (
									<div className="flex gap-4">
										<span className="w-32 text-gray-500">{t("email")}</span>
										<span>{customer.email}</span>
									</div>
								)}
							</>
						)}
						{job?.move_date && (
							<div className="flex gap-4">
								<span className="w-32 text-gray-500">{t("moveDate")}</span>
								<span>{formatDate(job.move_date)}</span>
							</div>
						)}
						<div className="flex gap-4">
							<span className="w-32 text-gray-500">{t("invoiceDate")}</span>
							<span>{formatDate(invoice.created_at)}</span>
						</div>
						{invoice.due_date && (
							<div className="flex gap-4">
								<span className="w-32 text-gray-500">{t("dueDate")}</span>
								<span>{formatDate(invoice.due_date)}</span>
							</div>
						)}
						{invoice.notes && (
							<div className="flex gap-4">
								<span className="w-32 text-gray-500">{t("notes")}</span>
								<span className="whitespace-pre-line">{invoice.notes}</span>
							</div>
						)}
						<div className="pt-2 border-t border-gray-100 dark:border-gray-800 flex justify-between font-bold text-base">
							<span>{t("total")}</span>
							<span className="tabular-nums text-brand-600">
								{formatRupiah(invoice.total_amount)}
							</span>
						</div>
					</section>
				</div>

				{/* Right: payments */}
				<div className="lg:col-span-1">
					<PaymentsPanel
						jobId={invoice.job_id}
						totalAmount={invoice.total_amount}
						payments={payments ?? []}
						invoiceStatus={invoice.status}
					/>
				</div>
			</div>
		</div>
	);
}
