// Generated by GitHub Copilot
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { formatDate, formatRupiah } from "@/lib/utils";
import {
	buildCompanySettings,
	buildInvoiceTemplateSettings,
} from "@/lib/pdfSettings";
import { PaymentsPanel } from "@/components/invoices/PaymentsPanel";
import { InvoicePDFDownloadButton } from "@/components/invoices/InvoicePDFDownloadButton";
import {
	PageHeader,
	Card,
	Badge,
	toneFor,
	Money,
} from "@/components/ui";

export default async function InvoiceDetailPage({
	params,
}: {
	params: Promise<{ id: string }>;
}) {
	const { id } = await params;
	const supabase = await createClient();
	const t = await getTranslations("pages.invoiceDetail");
	const tStatus = await getTranslations("status.invoice");

	const [{ data: invoice }, { data: settingsRows }] = await Promise.all([
		supabase
			.from("invoices")
			.select(`
        *,
        jobs(
          id, job_number, move_date,
          proposals(leads(customers(id, name, phone, email)))
        )
      `)
			.eq("id", id)
			.single(),
		supabase
			.from("system_settings")
			.select("key, value")
			.in("key", ["company_name", "company_tagline", "invoice_footer_note"]),
	]);

	if (!invoice) notFound();

	// Payments now live on the job, not the invoice — fetch via job_id.
	const { data: payments } = await supabase
		.from("payments")
		.select("id, payment_type, method, amount, paid_at, notes")
		.eq("job_id", invoice.job_id)
		.order("paid_at");

	const settingsMap = Object.fromEntries(
		(settingsRows ?? []).map((s) => [s.key, s.value]),
	);
	const pdfCompany = buildCompanySettings(settingsMap);
	const pdfTemplate = buildInvoiceTemplateSettings(settingsMap);

	const job = invoice.jobs as {
		id: string;
		job_number: string;
		move_date: string | null;
		proposals: {
			leads: {
				customers: {
					id: string;
					name: string;
					phone: string | null;
					email: string | null;
				} | null;
			} | null;
		} | null;
	} | null;

	const customer = job?.proposals?.leads?.customers ?? null;

	return (
		<div className="space-y-6">
			{/* Header */}
			<PageHeader
				title={
					<span className="flex items-center gap-3">
						<span className="font-mono">{invoice.invoice_number}</span>
						<Badge tone={toneFor("invoice", invoice.status)} dot>
							{tStatus(invoice.status as never)}
						</Badge>
					</span>
				}
				subtitle={
					<>
						{customer?.name ?? "—"}
						{invoice.due_date &&
							` · ${t("due", { date: formatDate(invoice.due_date) })}`}
						{job && (
							<>
								{" "}
								·{" "}
								<Link
									href={`/jobs/${job.id}`}
									className="text-primary-text hover:underline"
								>
									{job.job_number}
								</Link>
							</>
						)}
					</>
				}
				actions={
					customer && job ? (
						<InvoicePDFDownloadButton
							pdfProps={{
								invoice: {
									invoice_number: invoice.invoice_number,
									total_amount: invoice.total_amount,
									paid_amount: invoice.paid_amount ?? 0,
									status: invoice.status,
									due_date: invoice.due_date ?? null,
									notes: invoice.notes ?? null,
									created_at: invoice.created_at,
								},
								job: {
									job_number: job.job_number,
									move_date: job.move_date ?? null,
								},
								customer: {
									name: customer.name,
									phone: customer.phone ?? null,
									email: customer.email ?? null,
								},
								company: pdfCompany,
								template: pdfTemplate,
							}}
						/>
					) : undefined
				}
			/>

			<div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
				<div className="lg:col-span-2 space-y-6">
					<Card className="p-5 text-sm space-y-3">
						{customer && (
							<>
								<div className="flex gap-4">
									<span className="w-32 text-ink-muted">{t("customer")}</span>
									<span className="font-medium text-ink">{customer.name}</span>
								</div>
								{customer.phone && (
									<div className="flex gap-4">
										<span className="w-32 text-ink-muted">{t("phone")}</span>
										<span className="text-ink">{customer.phone}</span>
									</div>
								)}
								{customer.email && (
									<div className="flex gap-4">
										<span className="w-32 text-ink-muted">{t("email")}</span>
										<span className="text-ink">{customer.email}</span>
									</div>
								)}
							</>
						)}
						{job?.move_date && (
							<div className="flex gap-4">
								<span className="w-32 text-ink-muted">{t("moveDate")}</span>
								<span className="text-ink">{formatDate(job.move_date)}</span>
							</div>
						)}
						<div className="flex gap-4">
							<span className="w-32 text-ink-muted">{t("invoiceDate")}</span>
							<span className="text-ink">{formatDate(invoice.created_at)}</span>
						</div>
						{invoice.due_date && (
							<div className="flex gap-4">
								<span className="w-32 text-ink-muted">{t("dueDate")}</span>
								<span className="text-ink">{formatDate(invoice.due_date)}</span>
							</div>
						)}
						{invoice.notes && (
							<div className="flex gap-4">
								<span className="w-32 text-ink-muted">{t("notes")}</span>
								<span className="whitespace-pre-line text-ink">{invoice.notes}</span>
							</div>
						)}
						<div className="pt-2 border-t border-line flex justify-between font-bold text-base">
							<span className="text-ink">{t("total")}</span>
							<Money value={invoice.total_amount} tone="positive" />
						</div>
					</Card>
				</div>

				{/* Right: payments */}
				<div className="lg:col-span-1">
					<PaymentsPanel
						jobId={invoice.job_id}
						totalAmount={invoice.total_amount}
						payments={payments ?? []}
						invoiceStatus={invoice.status}
					/>
				</div>
			</div>
		</div>
	);
}
