-- Generated by GitHub Copilot
-- IM Ops — Full Database Migration (consolidated)
-- Run this in your Supabase SQL editor (Dashboard → SQL Editor → New query)
-- Execute in one shot. All objects are created in dependency order.
--
-- This is the single source of truth for the schema: every historical
-- migration has been folded into the end state below. Safe to run on a fresh
-- database, and re-runnable on an existing one (guarded by IF NOT EXISTS /
-- ON CONFLICT DO NOTHING / policy existence checks).

-- ============================================================
-- ENABLE EXTENSIONS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- CUSTOMERS
-- ============================================================
CREATE TABLE IF NOT EXISTS customers (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name         TEXT NOT NULL,
  phone        TEXT,
  email        TEXT,
  type         TEXT DEFAULT 'individual' CHECK (type IN ('individual','corporate')),
  company_name TEXT,
  notes        TEXT,
  created_at   TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- LEADS
-- ============================================================
CREATE TABLE IF NOT EXISTS leads (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id         UUID REFERENCES customers(id) ON DELETE RESTRICT,
  pickup_address      TEXT,
  destination_address TEXT,
  preferred_date      DATE,
  lead_type           TEXT CHECK (lead_type IN ('whatsapp','onsite','returning','corporate')),
  origin_channel      TEXT CHECK (origin_channel IN ('whatsapp','call','referral','walkin')),
  status              TEXT DEFAULT 'new' CHECK (status IN (
                        'new',
                        'survey_scheduled',
                        'survey_done',
                        'estimating',
                        'proposal_sent',
                        'converted',
                        'closed_lost'
                      )),
  notes               TEXT,
  created_by          UUID REFERENCES auth.users(id),
  created_at          TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- LEAD PHOTOS
-- ============================================================
CREATE TABLE IF NOT EXISTS lead_photos (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id      UUID REFERENCES leads(id) ON DELETE CASCADE,
  storage_path TEXT NOT NULL,
  caption      TEXT,
  uploaded_by  UUID REFERENCES auth.users(id),
  uploaded_at  TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- SURVEYS
-- ============================================================
CREATE TABLE IF NOT EXISTS surveys (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id         UUID REFERENCES leads(id) ON DELETE RESTRICT UNIQUE,
  scheduled_at    TIMESTAMPTZ NOT NULL,
  conducted_at    TIMESTAMPTZ,
  surveyor_id     UUID REFERENCES auth.users(id),
  access_notes    TEXT,
  special_items   JSONB DEFAULT '[]',
  notes           TEXT,
  gcal_event_id   TEXT,
  created_at      TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- SURVEY MEDIA
-- ============================================================
CREATE TABLE IF NOT EXISTS survey_media (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  survey_id    UUID REFERENCES surveys(id) ON DELETE CASCADE,
  media_type   TEXT CHECK (media_type IN ('photo','video')),
  storage_path TEXT NOT NULL,
  caption      TEXT,
  uploaded_at  TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- PROPOSALS
-- ============================================================
CREATE TABLE IF NOT EXISTS proposals (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id         UUID REFERENCES leads(id) ON DELETE RESTRICT,
  proposal_number TEXT UNIQUE NOT NULL,
  service_type    TEXT DEFAULT 'DOM',
  status          TEXT DEFAULT 'draft' CHECK (status IN (
                    'draft','sent','negotiating','approved','lost','expired'
                  )),
  final_price     BIGINT,
  closed_reason   TEXT,
  approved_at     TIMESTAMPTZ,
  pdf_url         TEXT,
  created_by      UUID REFERENCES auth.users(id),
  created_at      TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- ESTIMATIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS estimations (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id       UUID REFERENCES proposals(id) ON DELETE CASCADE UNIQUE,
  engine_version    TEXT NOT NULL,
  inputs            JSONB NOT NULL,
  settings_snapshot JSONB NOT NULL,
  outputs           JSONB NOT NULL,
  overrides         JSONB,
  created_by        UUID REFERENCES auth.users(id),
  created_at        TIMESTAMPTZ DEFAULT now(),
  updated_at        TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- PROPOSAL REVISIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS proposal_revisions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id    UUID REFERENCES proposals(id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL,
  price          BIGINT NOT NULL,
  changed_by     TEXT NOT NULL, -- 'operator' | 'customer'
  note           TEXT,
  created_at     TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- JOBS
-- ============================================================
CREATE TABLE IF NOT EXISTS jobs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id   UUID REFERENCES proposals(id) ON DELETE RESTRICT UNIQUE,
  job_number    TEXT UNIQUE NOT NULL,
  status        TEXT DEFAULT 'scheduled' CHECK (status IN (
                  'scheduled','in_progress','completed','closed','cancelled'
                )),
  move_date     DATE NOT NULL,
  move_time     TIME,  -- optional start time on move_date
  move_end_date DATE,  -- end date for multi-day moves; NULL = same day as move_date
  move_end_time TIME,  -- optional end time; NULL → downstream defaults to move_time + 8h, or 18:00
  revenue       BIGINT NOT NULL,
  gcal_event_id TEXT,
  notes         TEXT,
  created_by    UUID REFERENCES auth.users(id),
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- FLEET
-- ============================================================
CREATE TABLE IF NOT EXISTS fleet (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name             TEXT NOT NULL,
  phone            TEXT,
  contact_person   TEXT,
  vehicle_types    TEXT[] DEFAULT '{}',
  service_areas    TEXT[] DEFAULT '{}',
  rate_assumptions JSONB DEFAULT '{}',
  bank_name        TEXT,
  bank_account     TEXT,
  notes            TEXT,
  is_active        BOOLEAN DEFAULT true,
  created_at       TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- CREW
-- ============================================================
CREATE TABLE IF NOT EXISTS crew (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                TEXT NOT NULL,
  phone               TEXT,
  skills              TEXT[] DEFAULT '{}',
  daily_rate          BIGINT,
  availability_status TEXT DEFAULT 'available',
  emergency_contact   TEXT,
  notes               TEXT,
  is_active           BOOLEAN DEFAULT true,
  created_at          TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- JOB ASSIGNMENTS (explicit FK per type)
-- ============================================================
CREATE TABLE IF NOT EXISTS job_assignments (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id          UUID REFERENCES jobs(id) ON DELETE CASCADE,
  assignment_type TEXT NOT NULL CHECK (assignment_type IN ('fleet', 'crew')),
  fleet_id       UUID REFERENCES fleet(id) ON DELETE SET NULL,
  crew_id         UUID REFERENCES crew(id) ON DELETE SET NULL,
  role            TEXT,
  daily_rate      BIGINT,
  days            INTEGER DEFAULT 1,
  created_at      TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- EXPENSES
-- ============================================================
CREATE TABLE IF NOT EXISTS expenses (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id       UUID REFERENCES jobs(id) ON DELETE RESTRICT,
  amount       BIGINT NOT NULL CHECK (amount > 0),
  category     TEXT NOT NULL,
  description  TEXT,
  receipt_url  TEXT,
  incurred_at  DATE NOT NULL DEFAULT CURRENT_DATE,
  logged_by    UUID REFERENCES auth.users(id),
  created_at   TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- INVOICES
-- ============================================================
CREATE TABLE IF NOT EXISTS invoices (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id         UUID REFERENCES jobs(id) ON DELETE RESTRICT UNIQUE,
  invoice_number TEXT UNIQUE NOT NULL,
  total_amount   BIGINT NOT NULL,
  paid_amount    BIGINT NOT NULL DEFAULT 0,
  status         TEXT DEFAULT 'draft' CHECK (status IN (
                   'draft','sent','partially_paid','paid','overdue','cancelled'
                 )),
  due_date       DATE,
  notes          TEXT,
  pdf_url        TEXT,
  created_at     TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- PAYMENTS (from customer, linked to the job)
-- ============================================================
-- Payments live at the job level so a down payment can be taken on a
-- scheduled (not yet invoiced) job. The invoice's paid_amount/status is kept
-- in sync by the update_invoice_status trigger, matched by job_id.
CREATE TABLE IF NOT EXISTS payments (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id       UUID NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
  amount       BIGINT NOT NULL CHECK (amount > 0),
  payment_type TEXT NOT NULL CHECK (payment_type IN (
                 'down_payment','partial','final','refund'
               )),
  method       TEXT CHECK (method IN ('cash','transfer','qris')),
  paid_at      DATE NOT NULL DEFAULT CURRENT_DATE,
  notes        TEXT,
  created_at   TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- JOB TIMELINE
-- ============================================================
CREATE TABLE IF NOT EXISTS job_timeline (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id       UUID REFERENCES jobs(id) ON DELETE CASCADE,
  occurred_at  TIMESTAMPTZ DEFAULT now(),
  event_type   TEXT NOT NULL,
  notes        TEXT,
  logged_by    UUID REFERENCES auth.users(id)
);

-- ============================================================
-- SYSTEM SETTINGS
-- ============================================================
CREATE TABLE IF NOT EXISTS system_settings (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  category    TEXT,
  description TEXT,
  updated_at  TIMESTAMPTZ DEFAULT now(),
  updated_by  UUID REFERENCES auth.users(id)
);

-- Seed default system settings
INSERT INTO system_settings (key, value, category, description) VALUES
  ('crew_day_rate',                '175000',  'crew',    'Default crew cost per person per day (IDR)'),
  ('crew_overtime_rate',           '25000',   'crew',    'Additional per hour overtime (IDR)'),
  ('overnight_fee',                '100000',  'crew',    'Fee if job runs overnight (IDR)'),
  ('food_per_crew',                '35000',   'crew',    'Default food allowance per crew member (IDR)'),
  ('default_margin_pct',           '30',      'pricing', 'Default margin percentage (used as fallback; tiered margin auto-applies)'),
  ('negotiation_buffer_pct',       '3',       'pricing', 'Fixed negotiation buffer added to internal target price'),
  ('operational_buffer_pct',       '10',      'pricing', 'Operational buffer added to raw job cost'),
  ('margin_tiers',                 '[{"max":1000000,"rate_pct":45,"min_profit":300000},{"max":3000000,"rate_pct":35,"min_profit":500000},{"max":7000000,"rate_pct":25,"min_profit":750000},{"max":15000000,"rate_pct":20,"min_profit":1300000},{"max":null,"rate_pct":15,"min_profit":2100000}]', 'pricing', 'Tiered margin table: margin rate and minimum profit by adjusted-cost bracket'),
  ('price_round_increment',        '50000',   'pricing', 'Round prices up to the nearest this many IDR'),
  ('vehicle_rate_pickup',          '500000',  'vehicle', 'Pickup truck daily rate (IDR)'),
  ('vehicle_rate_box_truck',       '800000',  'vehicle', 'Box truck daily rate (IDR)'),
  ('min_target_profit',            '500000',  'safety',  'Minimum acceptable profit per job (IDR)'),
  ('invoice_due_days',             '7',       'invoice',   'Default invoice due days after issue'),
  ('gcal_calendar_id',             '',        'gcal',      'Google Calendar ID for event sync (leave blank to disable)'),
  ('revenue_target_monthly',       '50000000','dashboard', 'Monthly revenue target shown on the dashboard (IDR). Edit this value to change the goal bar.'),
  ('company_name',                 'IM Moving',                          'company',   'Company name shown on proposals and invoices'),
  ('company_tagline',              'Professional Relocation Services',   'company',   'Tagline shown below company name on all PDFs'),
  ('proposal_terms',               E'1. This proposal is valid for 7 days from the date of issue.\n2. A down payment of 50% is required to confirm the booking.\n3. Remaining balance is due on the day of the move before unloading.\n4. Prices may be revised if the scope of work changes significantly.\n5. IM Moving is not liable for pre-existing damage to items.\n6. Cancellation less than 48 hours before the move date may incur a penalty.', 'documents', 'Terms & conditions text shown on proposals (edit freely — each line becomes a numbered term)'),
  ('proposal_signature_name',      'IM Moving Operations',  'documents', 'Signatory name shown on the proposal signature block'),
  ('proposal_signature_role',      'Authorized Signatory',  'documents', 'Signatory role/title shown on the proposal signature block'),
  ('invoice_footer_note',          'Thank you for your business', 'documents', 'Footer note shown at the bottom of every invoice')
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- VIEWS
-- ============================================================

-- Live profit per job
CREATE OR REPLACE VIEW job_profit_summary AS
SELECT
  j.id AS job_id,
  j.job_number,
  j.revenue,
  j.status,
  COALESCE(SUM(e.amount), 0)::BIGINT AS actual_spend,
  (j.revenue - COALESCE(SUM(e.amount), 0))::BIGINT AS current_profit,
  COALESCE(i.paid_amount, 0)::BIGINT AS cash_received
FROM jobs j
LEFT JOIN expenses e ON e.job_id = j.id
LEFT JOIN invoices i ON i.job_id = j.id
GROUP BY j.id, i.paid_amount;

-- Outstanding invoices
CREATE OR REPLACE VIEW invoice_outstanding AS
SELECT
  i.id,
  i.invoice_number,
  i.total_amount,
  i.paid_amount AS paid,
  (i.total_amount - i.paid_amount) AS outstanding,
  i.due_date,
  CASE
    WHEN i.due_date < CURRENT_DATE AND i.status NOT IN ('paid','cancelled') THEN 'overdue'
    ELSE i.status
  END AS effective_status
FROM invoices i;

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Auto-generate proposal number: {SEQ}/{SERVICE_TYPE}-IM/{MONTH_ROMAN}/{YEAR}
CREATE OR REPLACE FUNCTION generate_proposal_number(service_type TEXT DEFAULT 'DOM')
RETURNS TEXT AS $$
DECLARE
  seq         INTEGER;
  month_roman TEXT;
  year_val    TEXT;
  roman_months TEXT[] := ARRAY['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII'];
BEGIN
  SELECT COALESCE(MAX(
    CAST(SPLIT_PART(proposal_number, '/', 1) AS INTEGER)
  ), 0) + 1
  INTO seq
  FROM proposals
  WHERE EXTRACT(YEAR FROM created_at) = EXTRACT(YEAR FROM now());

  month_roman := roman_months[EXTRACT(MONTH FROM now())];
  year_val    := TO_CHAR(now(), 'YYYY');

  RETURN seq || '/' || service_type || '-IM/' || month_roman || '/' || year_val;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Check resource overlap (warning only — does not block)
CREATE OR REPLACE FUNCTION check_resource_overlap(
  p_type      TEXT,
  p_id        UUID,
  p_date      DATE
)
RETURNS TABLE(job_id UUID, job_number TEXT, move_date DATE) AS $$
BEGIN
  RETURN QUERY
  SELECT j.id, j.job_number, j.move_date
  FROM job_assignments ja
  JOIN jobs j ON j.id = ja.job_id
  WHERE ja.assignment_type = p_type
    AND (
      (p_type = 'fleet' AND ja.fleet_id = p_id)
      OR
      (p_type = 'crew'   AND ja.crew_id   = p_id)
    )
    AND j.move_date = p_date
    AND j.status NOT IN ('cancelled','closed');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Auto-update invoice paid_amount and status after a payment change.
-- Payments are matched to the invoice by job_id; if no invoice exists yet the
-- payment is still persisted (the down-payment-before-invoice case).
CREATE OR REPLACE FUNCTION update_invoice_status()
RETURNS TRIGGER AS $$
DECLARE
  total_paid    BIGINT;
  invoice_total BIGINT;
  target_job_id UUID;
BEGIN
  target_job_id := COALESCE(NEW.job_id, OLD.job_id);

  SELECT
    COALESCE(SUM(amount) FILTER (WHERE payment_type != 'refund'), 0)
    - COALESCE(SUM(amount) FILTER (WHERE payment_type = 'refund'), 0)
  INTO total_paid
  FROM payments
  WHERE job_id = target_job_id;

  SELECT total_amount INTO invoice_total
  FROM invoices WHERE job_id = target_job_id;

  IF invoice_total IS NULL THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  UPDATE invoices
  SET paid_amount = total_paid,
      status = CASE
        WHEN total_paid >= invoice_total THEN 'paid'
        WHEN total_paid > 0              THEN 'partially_paid'
        ELSE 'sent'
      END
  WHERE job_id = target_job_id;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS after_payment_insert ON payments;
CREATE TRIGGER after_payment_insert
  AFTER INSERT OR UPDATE OR DELETE ON payments
  FOR EACH ROW EXECUTE FUNCTION update_invoice_status();

-- ============================================================
-- ROW LEVEL SECURITY
-- All tables locked to authenticated users only.
-- Single-org app — all authenticated users see all data.
-- ============================================================

ALTER TABLE customers        ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads            ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead_photos      ENABLE ROW LEVEL SECURITY;
ALTER TABLE surveys          ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey_media     ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposals        ENABLE ROW LEVEL SECURITY;
ALTER TABLE estimations      ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposal_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs             ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet          ENABLE ROW LEVEL SECURITY;
ALTER TABLE crew             ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_assignments  ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses         ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments         ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices         ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_timeline     ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings  ENABLE ROW LEVEL SECURITY;

-- Authenticated users can do everything (single-org app)
DO $$
DECLARE
  tbl TEXT;
  tables TEXT[] := ARRAY[
    'customers','leads','lead_photos','surveys','survey_media',
    'proposals','estimations','proposal_revisions','jobs',
    'fleet','crew','job_assignments','expenses','payments',
    'invoices','job_timeline','system_settings'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename  = tbl
        AND policyname = 'authenticated_all_' || tbl
    ) THEN
      EXECUTE format('
        CREATE POLICY "authenticated_all_%s"
        ON %I
        FOR ALL
        TO authenticated
        USING (true)
        WITH CHECK (true)
      ', tbl, tbl);
    END IF;
  END LOOP;
END $$;

-- ============================================================
-- STORAGE BUCKETS + POLICIES
-- Supabase Storage uses PostgreSQL RLS on storage.objects.
-- The public-table DO-block above does NOT cover storage.*.
-- ============================================================

-- 1. Ensure buckets exist and are public (safe to re-run).
--    Public buckets allow getPublicUrl() to return a directly loadable URL.
--    Paths are UUID-based so they are not guessable.
INSERT INTO storage.buckets (id, name, public)
  VALUES
    ('lead-photos',  'lead-photos',  true),
    ('survey-media', 'survey-media', true),
    ('invoices',     'invoices',     true),
    ('proposals',    'proposals',    true)
  ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

-- 2. Storage policies — authenticated users can SELECT / INSERT / UPDATE / DELETE
--    in every bucket used by this application.
DO $$
DECLARE
  bucket TEXT;
  buckets TEXT[] := ARRAY['lead-photos', 'survey-media', 'invoices', 'proposals'];
BEGIN
  FOREACH bucket IN ARRAY buckets LOOP
    -- SELECT
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'storage' AND tablename = 'objects'
        AND policyname = 'authenticated_select_' || bucket
    ) THEN
      EXECUTE format(
        'CREATE POLICY "authenticated_select_%s"
         ON storage.objects FOR SELECT TO authenticated
         USING (bucket_id = %L)',
        bucket, bucket
      );
    END IF;

    -- INSERT
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'storage' AND tablename = 'objects'
        AND policyname = 'authenticated_insert_' || bucket
    ) THEN
      EXECUTE format(
        'CREATE POLICY "authenticated_insert_%s"
         ON storage.objects FOR INSERT TO authenticated
         WITH CHECK (bucket_id = %L)',
        bucket, bucket
      );
    END IF;

    -- UPDATE
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'storage' AND tablename = 'objects'
        AND policyname = 'authenticated_update_' || bucket
    ) THEN
      EXECUTE format(
        'CREATE POLICY "authenticated_update_%s"
         ON storage.objects FOR UPDATE TO authenticated
         USING (bucket_id = %L)',
        bucket, bucket
      );
    END IF;

    -- DELETE
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'storage' AND tablename = 'objects'
        AND policyname = 'authenticated_delete_' || bucket
    ) THEN
      EXECUTE format(
        'CREATE POLICY "authenticated_delete_%s"
         ON storage.objects FOR DELETE TO authenticated
         USING (bucket_id = %L)',
        bucket, bucket
      );
    END IF;
  END LOOP;
END $$;
