"use client";
// Generated by GitHub Copilot
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { createClient } from "@/lib/supabase/client";

type VendorRow = {
	id: string;
	name: string;
	contact_person: string | null;
	phone: string | null;
	vehicle_types: string[] | null;
	service_areas: string[] | null;
	bank_name: string | null;
	bank_account: string | null;
	notes: string | null;
	is_active: boolean;
};

const VEHICLE_OPTIONS: { value: string; tKey: string }[] = [
	{ value: "Box Small", tKey: "box_small" },
	{ value: "Box Medium", tKey: "box_medium" },
	{ value: "Box Large", tKey: "box_large" },
	{ value: "Truck L300", tKey: "truck_l300" },
	{ value: "Fuso", tKey: "fuso" },
	{ value: "CDE", tKey: "cde" },
	{ value: "CDD", tKey: "cdd" },
	{ value: "Wingbox", tKey: "wingbox" },
];

/**
 * Create or edit a vendor.
 * @param vendor - existing vendor data for edit mode; omit for create mode
 */
export function VendorForm({ vendor }: { vendor?: VendorRow }) {
	const router = useRouter();
	const t = useTranslations("forms.vendor");
	const tButtons = useTranslations("common.buttons");
	const tActions = useTranslations("actions");
	const tErrors = useTranslations("common.errors");
	const tHints = useTranslations("common.hints");
	const tVehicleType = useTranslations("entity.vehicleType");
	const isEdit = Boolean(vendor);

	const [form, setForm] = useState({
		name: vendor?.name ?? "",
		contact_person: vendor?.contact_person ?? "",
		phone: vendor?.phone ?? "",
		vehicle_types: vendor?.vehicle_types ?? [],
		service_areas: vendor?.service_areas?.join(", ") ?? "",
		bank_name: vendor?.bank_name ?? "",
		bank_account: vendor?.bank_account ?? "",
		notes: vendor?.notes ?? "",
		is_active: vendor?.is_active ?? true,
	});
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	function toggleVehicle(v: string) {
		setForm((p) => ({
			...p,
			vehicle_types: p.vehicle_types.includes(v)
				? p.vehicle_types.filter((x) => x !== v)
				: [...p.vehicle_types, v],
		}));
	}

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		if (!form.name.trim()) {
			setError(tErrors("nameRequired"));
			return;
		}
		setSaving(true);
		setError(null);

		const payload = {
			name: form.name.trim(),
			contact_person: form.contact_person.trim() || null,
			phone: form.phone.trim() || null,
			vehicle_types: form.vehicle_types.length ? form.vehicle_types : [],
			service_areas: form.service_areas.trim()
				? form.service_areas
						.split(",")
						.map((s) => s.trim())
						.filter(Boolean)
				: [],
			bank_name: form.bank_name.trim() || null,
			bank_account: form.bank_account.trim() || null,
			notes: form.notes.trim() || null,
			is_active: form.is_active,
		};

		const supabase = createClient();

		if (isEdit && vendor) {
			const { error: err } = await supabase
				.from("vendors")
				.update(payload)
				.eq("id", vendor.id);
			if (err) {
				setError(err.message);
				setSaving(false);
				return;
			}
			router.push(`/vendors/${vendor.id}`);
		} else {
			const { data, error: err } = await supabase
				.from("vendors")
				.insert(payload)
				.select("id")
				.single();
			if (err || !data) {
				setError(err?.message ?? "Error");
				setSaving(false);
				return;
			}
			router.push(`/vendors/${data.id}`);
		}
	}

	return (
		<form onSubmit={handleSubmit} className="max-w-lg space-y-5" noValidate>
			{error && (
				<div
					role="alert"
					className="rounded bg-red-50 dark:bg-red-900/20 border border-red-200 px-3 py-2 text-sm text-red-700 dark:text-red-300"
				>
					{error}
				</div>
			)}

			<div>
				<label
					htmlFor="v-name"
					className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
				>
					{t("name")}{" "}
					<span aria-hidden="true" className="text-red-500">
						*
					</span>
				</label>
				<input
					id="v-name"
					type="text"
					required
					value={form.name}
					onChange={(e) => setForm((p) => ({ ...p, name: e.target.value }))}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<div className="grid grid-cols-2 gap-4">
				<div>
					<label
						htmlFor="v-contact"
						className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
					>
						{t("contactPerson")}
					</label>
					<input
						id="v-contact"
						type="text"
						value={form.contact_person}
						onChange={(e) =>
							setForm((p) => ({ ...p, contact_person: e.target.value }))
						}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>
				<div>
					<label
						htmlFor="v-phone"
						className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
					>
						{t("phone")}
					</label>
					<input
						id="v-phone"
						type="tel"
						value={form.phone}
						onChange={(e) => setForm((p) => ({ ...p, phone: e.target.value }))}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>
			</div>

			<div>
				<span className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">
					{t("vehicleTypes")}
				</span>
				<div
					role="group"
					aria-label={t("vehicleTypes")}
					className="flex flex-wrap gap-2"
				>
					{VEHICLE_OPTIONS.map((v) => (
						<label
							key={v.value}
							className="flex items-center gap-1.5 cursor-pointer select-none"
						>
							<input
								type="checkbox"
								checked={form.vehicle_types.includes(v.value)}
								onChange={() => toggleVehicle(v.value)}
								className="rounded border-gray-400 text-brand-600 focus:ring-brand-500"
							/>
							<span className="text-sm">{tVehicleType(v.tKey)}</span>
						</label>
					))}
				</div>
			</div>

			<div>
				<label
					htmlFor="v-areas"
					className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
				>
					{t("serviceAreas")}{" "}
					<span className="text-gray-400 font-normal">
						{tHints("commaSeparated")}
					</span>
				</label>
				<input
					id="v-areas"
					type="text"
					value={form.service_areas}
					onChange={(e) =>
						setForm((p) => ({ ...p, service_areas: e.target.value }))
					}
					placeholder="Jakarta, Bekasi, Tangerang"
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<div className="grid grid-cols-2 gap-4">
				<div>
					<label
						htmlFor="v-bank"
						className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
					>
						{t("bankName")}
					</label>
					<input
						id="v-bank"
						type="text"
						value={form.bank_name}
						onChange={(e) =>
							setForm((p) => ({ ...p, bank_name: e.target.value }))
						}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>
				<div>
					<label
						htmlFor="v-account"
						className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
					>
						{t("bankAccount")}
					</label>
					<input
						id="v-account"
						type="text"
						value={form.bank_account}
						onChange={(e) =>
							setForm((p) => ({ ...p, bank_account: e.target.value }))
						}
						className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
					/>
				</div>
			</div>

			<div>
				<label
					htmlFor="v-notes"
					className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300"
				>
					{t("notes")}
				</label>
				<textarea
					id="v-notes"
					rows={3}
					value={form.notes}
					onChange={(e) => setForm((p) => ({ ...p, notes: e.target.value }))}
					className="w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
				/>
			</div>

			<label className="flex items-center gap-2 cursor-pointer">
				<input
					type="checkbox"
					checked={form.is_active}
					onChange={(e) =>
						setForm((p) => ({ ...p, is_active: e.target.checked }))
					}
					className="rounded border-gray-400 text-brand-600 focus:ring-brand-500"
				/>
				<span className="text-sm text-gray-700 dark:text-gray-300">{t("active")}</span>
			</label>

			<div className="flex gap-3 pt-2">
				<button
					type="submit"
					disabled={saving}
					className="rounded-lg bg-brand-600 px-5 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
				>
					{saving
						? tButtons("saving")
						: isEdit
							? tButtons("saveChanges")
							: tActions("addVendor")}
				</button>
				<button
					type="button"
					onClick={() => router.back()}
					className="rounded-lg border border-gray-300 dark:border-gray-700 px-5 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 transition-colors"
				>
					{tButtons("cancel")}
				</button>
			</div>
		</form>
	);
}
